"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { Building2, CalendarDays, ClipboardList, Download, GraduationCap, LayoutDashboard, Megaphone, Plus, Search, Settings, Trash2, UsersRound } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import {
  archiveAnnouncementAction, assignFacultyAction, deleteAnnouncementAction, deleteClassAction, deleteDepartmentAction, deleteTimetableAction,
  saveAcademicYearAction, saveAnnouncementAction, saveClassAction, saveDepartmentAction, saveInstitutionPreferencesAction,
  saveInstitutionProfileAction, saveTermAction, saveTimetableAction
} from "@/features/institution-workspace/actions";
import type { getInstitutionWorkspaceData, InstitutionModule } from "@/services/institution-workspace-service";

type Data = NonNullable<Awaited<ReturnType<typeof getInstitutionWorkspaceData>>>;
const modules: { slug: InstitutionModule; label: string; icon: typeof Building2 }[] = [
  { slug: "dashboard", label: "Dashboard", icon: LayoutDashboard }, { slug: "profile", label: "Profile", icon: Building2 },
  { slug: "departments", label: "Departments", icon: GraduationCap }, { slug: "faculty", label: "Faculty", icon: UsersRound },
  { slug: "academics", label: "Academic Structure", icon: CalendarDays }, { slug: "classes", label: "Classes", icon: ClipboardList },
  { slug: "timetable", label: "Timetable", icon: CalendarDays }, { slug: "announcements", label: "Announcements", icon: Megaphone },
  { slug: "reports", label: "Reports", icon: Download }, { slug: "settings", label: "Settings", icon: Settings }
];
const descriptions: Record<InstitutionModule, string> = {
  dashboard: "A live overview of teachers, classes, students, academics, notifications, and activity.",
  profile: "Manage public institution identity, contact details, accreditation, and profile preview.",
  departments: "Create, edit, search, filter, and review departments, subjects, teachers, and performance.",
  faculty: "Find faculty, review assignments and activity, and allocate teachers to classes.",
  academics: "Manage academic years, terms, courses, subjects, sections, and the academic calendar.",
  classes: "Create classes, set capacity, assign teachers, and review classroom operations.",
  timetable: "Coordinate weekly, class, and teacher schedules with conflict visibility and print view.",
  announcements: "Publish or schedule institution, department, and teacher notices with attachments.",
  reports: "Review teacher, department, academic, resource, AI, and platform activity reports.",
  settings: "Control general, academic, branding, permission, notification, integration, and subscription settings."
};
const val = (x: unknown) => typeof x === "string" ? x : "";
function when(x: Date | string | null | undefined) { return x ? new Date(x).toLocaleString() : "Not scheduled"; }
function exportJson(name: string, value: unknown) { const u = URL.createObjectURL(new Blob([JSON.stringify(value, null, 2)], { type: "application/json" })); const a = document.createElement("a"); a.href = u; a.download = `teachx-${name}.json`; a.click(); URL.revokeObjectURL(u); }
function Metric({ label, value }: { label: string; value: string | number }) { return <Card className="p-4"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></Card>; }
function Submit({ children, danger }: { children: React.ReactNode; danger?: boolean }) { return <button className={`rounded-full border px-3 py-1.5 text-xs font-medium hover:bg-muted ${danger ? "text-red-600" : ""}`} type="submit">{children}</button>; }

function Dashboard({ d }: { d: Data }) {
  return <div className="space-y-6"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Metric label="Active Teachers" value={d.stats.activeTeachers}/><Metric label="Active Classes" value={d.stats.activeClasses}/><Metric label="Active Students" value={d.activeStudents}/><Metric label="Courses" value={d.stats.courses}/><Metric label="Departments" value={d.stats.departments}/><Metric label="AI Requests" value={d.aiUsage.requests}/></div>
    <div className="grid gap-5 xl:grid-cols-2"><Card className="p-5"><h2 className="text-xl font-semibold">Quick actions</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{modules.slice(2,8).map(x=><Link className="rounded-xl border p-4 text-sm font-medium hover:bg-muted" href={`/institution/${x.slug}`} key={x.slug}><Plus className="mr-2 inline h-4 w-4"/>{x.label}</Link>)}</div></Card>
    <Card className="p-5"><h2 className="text-xl font-semibold">Notifications</h2><div className="mt-4 space-y-3">{d.notifications.length?d.notifications.slice(0,6).map(x=><div className="rounded-xl bg-background p-3" key={x.id}><p className="font-medium">{x.title}</p><p className="text-sm text-muted-foreground">{x.body || when(x.createdAt)}</p></div>):<p className="text-sm text-muted-foreground">No institution notifications.</p>}</div></Card></div>
    <Card className="p-5"><h2 className="text-xl font-semibold">Recent activities</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{d.activities.length?d.activities.slice(0,8).map(x=><div className="rounded-xl border p-3 text-sm" key={x.id}><strong>{x.title}</strong><span className="block text-muted-foreground">{x.actor?.name || "TeachX"} · {when(x.createdAt)}</span></div>):<p className="text-sm text-muted-foreground">Activities appear as the institution uses TeachX.</p>}</div></Card></div>;
}
function Profile({ d }: { d: Data }) { const p=d.profile; return <div className="grid gap-6 xl:grid-cols-[1fr_360px]"><Card className="p-5"><h2 className="text-xl font-semibold">Institution information</h2><form action={saveInstitutionProfileAction} className="mt-5 grid gap-4 md:grid-cols-2"><div><Label>Name</Label><Input defaultValue={d.institution.name} name="name" required/></div><div><Label>Logo URL</Label><Input defaultValue={d.institution.logoUrl??""} name="logoUrl" type="url"/></div><div><Label>Cover image URL</Label><Input defaultValue={val(p.coverImage)} name="coverImage" type="url"/></div><div><Label>Accreditation</Label><Input defaultValue={val(p.accreditation)} name="accreditation"/></div><div><Label>Email</Label><Input defaultValue={d.institution.email??""} name="email" type="email"/></div><div><Label>Phone</Label><Input defaultValue={d.institution.phone??""} name="phone"/></div><div><Label>Website</Label><Input defaultValue={d.institution.website??""} name="website" type="url"/></div><div><Label>LinkedIn</Label><Input defaultValue={val(p.linkedin)} name="linkedin" type="url"/></div><div><Label>Facebook</Label><Input defaultValue={val(p.facebook)} name="facebook" type="url"/></div><div><Label>Instagram</Label><Input defaultValue={val(p.instagram)} name="instagram" type="url"/></div><div className="md:col-span-2"><Label>Address</Label><Textarea defaultValue={d.institution.address??""} name="address"/></div><div className="md:col-span-2"><Label>Description</Label><Textarea defaultValue={val(p.description)} name="description"/></div><Button className="md:w-fit" type="submit">Save profile</Button></form></Card>
  <Card className="h-fit overflow-hidden"><div className="h-32 bg-sky-100 bg-cover bg-center" style={p.coverImage?{backgroundImage:`url(${val(p.coverImage)})`}:undefined}/><div className="p-5"><div className="-mt-12 h-20 w-20 rounded-2xl border-4 border-white bg-white bg-contain bg-center bg-no-repeat" style={d.institution.logoUrl?{backgroundImage:`url(${d.institution.logoUrl})`}:undefined}/><h2 className="mt-3 text-xl font-semibold">{d.institution.name}</h2><p className="mt-2 text-sm text-muted-foreground">{val(p.accreditation)||"Accreditation not added"}</p><p className="mt-3 text-sm">{val(p.description)||"Add an institution description."}</p>{d.institution.website?<Link className="mt-5 inline-flex text-sm font-semibold text-sky-700" href={d.institution.website} target="_blank">Public profile preview</Link>:null}</div></Card></div>; }
function Departments({ d }: { d: Data }) { const [q,setQ]=useState("");const [status,setStatus]=useState("ALL");const rows=d.departments.filter(x=>`${x.name} ${x.code??""}`.toLowerCase().includes(q.toLowerCase())).filter(x=>status==="ALL"||x.status===status); return <div className="space-y-5"><details className="rounded-2xl border bg-surface p-5"><summary className="cursor-pointer font-semibold"><Plus className="mr-2 inline h-4 w-4"/>Create department</summary><DepartmentForm/></details><div className="grid gap-3 md:grid-cols-[1fr_220px]"><Input onChange={e=>setQ(e.target.value)} placeholder="Search departments…"/><Select onChange={e=>setStatus(e.target.value)}><option>ALL</option><option>ACTIVE</option><option>INACTIVE</option></Select></div>{rows.length?<div className="grid gap-4 lg:grid-cols-2">{rows.map(x=>{const teachers=new Set(x.courses.flatMap(c=>c.batches.flatMap(b=>b.faculty.map(f=>f.facultyId))));return <Card className="p-5" key={x.id}><div className="flex justify-between"><div><Badge>{x.status}</Badge><h2 className="mt-2 text-xl font-semibold">{x.name}</h2><p className="text-sm text-muted-foreground">{x.code||"No code"} · {x.courses.length} courses · {x.courses.reduce((n,c)=>n+c.subjects.length,0)} subjects · {teachers.size} teachers</p></div></div><details className="mt-4"><summary className="cursor-pointer text-sm font-medium">Edit and statistics</summary><DepartmentForm item={x}/><p className="mt-3 text-sm">Students: {x.courses.reduce((n,c)=>n+c.batches.reduce((m,b)=>m+b.students.length,0),0)} · Classes: {x.courses.reduce((n,c)=>n+c.batches.length,0)}</p></details><form action={deleteDepartmentAction} className="mt-3"><input name="id" type="hidden" value={x.id}/><Submit danger>Delete empty department</Submit></form></Card>})}</div>:<EmptyState icon={<GraduationCap/>} title="No departments found" description="Create a department or adjust the filters."/>}</div>; }
function DepartmentForm({item}:{item?:Data["departments"][number]}) { return <form action={saveDepartmentAction} className="mt-4 grid gap-3 sm:grid-cols-3">{item?<input name="id" type="hidden" value={item.id}/>:null}<Input defaultValue={item?.name} name="name" placeholder="Department name" required/><Input defaultValue={item?.code??""} name="code" placeholder="Code"/><Select defaultValue={item?.status??"ACTIVE"} name="status"><option>ACTIVE</option><option>INACTIVE</option></Select><Button type="submit">{item?"Save changes":"Create"}</Button></form>; }
function Faculty({d}:{d:Data}) { const [q,setQ]=useState("");const rows=d.faculty.filter(x=>`${x.name} ${x.email}`.toLowerCase().includes(q.toLowerCase()));return <div className="space-y-5"><Input className="max-w-xl" onChange={e=>setQ(e.target.value)} placeholder="Search faculty by name or email…"/><Card className="p-5"><h2 className="text-xl font-semibold">Assign faculty</h2><form action={assignFacultyAction} className="mt-4 grid gap-3 md:grid-cols-3"><Select name="facultyId" required><option value="">Faculty member</option>{d.faculty.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select><Select name="batchId" required><option value="">Class / section</option>{d.batches.map(x=><option key={x.id} value={x.id}>{x.course.name} · {x.name}</option>)}</Select><label className="flex items-center gap-2"><input name="isLead" type="checkbox"/>Department/class lead</label><Button className="md:w-fit" type="submit">Assign</Button></form></Card><div className="grid gap-4 lg:grid-cols-2">{rows.map(x=><Card className="p-5" key={x.id}><Badge>{x.status}</Badge><h2 className="mt-2 text-lg font-semibold">{x.name}</h2><p className="text-sm text-muted-foreground">{x.email} · {x.roles.map(r=>r.role.name).join(", ")}</p><div className="mt-3 flex flex-wrap gap-2">{x.facultyBatches.map(f=><span className="rounded-full bg-muted px-3 py-1 text-xs" key={f.id}>{f.batch.course.name} · {f.batch.name}</span>)}</div><p className="mt-3 text-xs text-muted-foreground">Activity: {d.activities.filter(a=>a.actorId===x.id).length} recent events</p></Card>)}</div></div>; }
function Academics({d}:{d:Data}) { return <div className="space-y-6"><div className="grid gap-5 xl:grid-cols-2"><Card className="p-5"><h2 className="text-xl font-semibold">Academic year</h2><form action={saveAcademicYearAction} className="mt-4 grid gap-3 sm:grid-cols-2"><Input name="name" placeholder="2026–27" required/><Input name="startDate" type="date" required/><Input name="endDate" type="date" required/><label className="flex items-center gap-2"><input name="isCurrent" type="checkbox"/>Current year</label><Button className="w-fit" type="submit">Create year</Button></form></Card><Card className="p-5"><h2 className="text-xl font-semibold">Academic term</h2><form action={saveTermAction} className="mt-4 grid gap-3 sm:grid-cols-2"><Select name="academicYearId" required><option value="">Academic year</option>{d.years.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select><Input name="name" placeholder="Term 1" required/><Input name="startDate" type="date" required/><Input name="endDate" type="date" required/><Input defaultValue="1" min="1" name="order" type="number"/><Button className="w-fit" type="submit">Add term</Button></form></Card></div><div className="grid gap-4 lg:grid-cols-2">{d.years.map(x=><Card className="p-5" key={x.id}><Badge>{x.isCurrent?"CURRENT":x.status}</Badge><h2 className="mt-2 text-xl font-semibold">{x.name}</h2><p className="text-sm text-muted-foreground">{new Date(x.startDate).toLocaleDateString()} – {new Date(x.endDate).toLocaleDateString()}</p><div className="mt-3 space-y-2">{x.terms.map(t=><p className="rounded-xl bg-muted p-3 text-sm" key={t.id}>{t.name} · {new Date(t.startDate).toLocaleDateString()} – {new Date(t.endDate).toLocaleDateString()}</p>)}</div></Card>)}</div><Card className="p-5"><h2 className="text-xl font-semibold">Courses, subjects, and calendar</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{d.courses.map(x=><div className="rounded-xl border p-3" key={x.id}><strong>{x.name}</strong><span className="block text-sm text-muted-foreground">{x.department?.name||"Unassigned"} · {x.subjects.map(s=>s.name).join(", ")||"No subjects"}</span></div>)}</div><div className="mt-5 space-y-2">{d.events.slice(0,8).map(x=><p className="rounded-xl bg-muted p-3 text-sm" key={x.id}><strong>{x.title}</strong> · {x.type} · {when(x.startsAt)}</p>)}</div><Link className="mt-4 inline-flex text-sm font-semibold text-sky-700" href="/academic">Manage shared course setup and calendar</Link></Card></div>; }
function Classes({d}:{d:Data}) { return <div className="space-y-5"><details className="rounded-2xl border bg-surface p-5"><summary className="cursor-pointer font-semibold"><Plus className="mr-2 inline h-4 w-4"/>Create class</summary><form action={saveClassAction} className="mt-4 grid gap-3 md:grid-cols-2"><Select name="courseId" required><option value="">Course</option>{d.courses.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select><Input name="name" placeholder="Section / batch name" required/><Input name="title" placeholder="Classroom title"/><Input defaultValue="30" min="1" name="capacity" type="number"/><Button className="w-fit" type="submit">Create class</Button></form></details><div className="grid gap-4 lg:grid-cols-2">{d.classrooms.map(x=><Card className="p-5" key={x.id}><Badge>{x.status}</Badge><h2 className="mt-2 text-xl font-semibold">{x.title}</h2><p className="text-sm text-muted-foreground">{x.course.name} · {x.batch.name}</p><div className="mt-3 grid grid-cols-3 gap-2 text-sm"><span>{x.batch.students.length}/{x.batch.maximumStrength} students</span><span>{x.batch.faculty.length} teachers</span><span>{d.timetable.filter(t=>t.batchId===x.batchId).length} periods</span></div><div className="mt-4 flex gap-3"><Link className="rounded-full border px-3 py-1.5 text-xs font-medium" href={`/classrooms/${x.id}`}>Open classroom</Link><form action={deleteClassAction}><input name="id" type="hidden" value={x.id}/><Submit danger>Delete</Submit></form></div></Card>)}</div></div>; }
function Timetable({d}:{d:Data}) { const conflicts=useMemo(()=>new Set(d.timetable.filter((x,i,a)=>a.some((y,j)=>j!==i&&y.day===x.day&&y.timeSlotId===x.timeSlotId&&((x.facultyId&&x.facultyId===y.facultyId)||(x.roomId&&x.roomId===y.roomId)))).map(x=>x.id)),[d.timetable]);return <div className="space-y-5"><Card className="p-5 print:hidden"><h2 className="text-xl font-semibold">Allocate period</h2><form action={saveTimetableAction} className="mt-4 grid gap-3 md:grid-cols-3"><Select name="batchId" required><option value="">Class</option>{d.batches.map(x=><option key={x.id} value={x.id}>{x.course.name} · {x.name}</option>)}</Select><Select name="day" required>{["MONDAY","TUESDAY","WEDNESDAY","THURSDAY","FRIDAY","SATURDAY","SUNDAY"].map(x=><option key={x}>{x}</option>)}</Select><Select name="timeSlotId" required><option value="">Time slot</option>{d.timeSlots.map(x=><option key={x.id} value={x.id}>{x.name} · {x.startsAt}-{x.endsAt}</option>)}</Select><Select name="subjectId"><option value="">Subject</option>{d.courses.flatMap(c=>c.subjects).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select><Select name="facultyId"><option value="">Teacher</option>{d.faculty.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select><Select name="roomId"><option value="">Room</option>{d.rooms.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select><Button className="w-fit" type="submit">Add period</Button></form></Card><div className="flex items-center justify-between"><p className="text-sm text-muted-foreground">{conflicts.size} scheduling conflicts detected</p><Button onClick={()=>window.print()} type="button" variant="secondary">Print view</Button></div>{d.timetable.length?<div className="overflow-x-auto rounded-2xl border"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-muted"><tr>{["Day / Time","Class","Subject","Teacher","Room","Status",""].map(x=><th className="p-3" key={x}>{x}</th>)}</tr></thead><tbody>{d.timetable.map(x=><tr className="border-t" key={x.id}><td className="p-3">{x.day}<br/><span className="text-xs text-muted-foreground">{x.timeSlot.startsAt}-{x.timeSlot.endsAt}</span></td><td className="p-3">{x.course.name} · {x.batch.name}</td><td className="p-3">{x.subject?.name||"—"}</td><td className="p-3">{x.faculty?.name||"—"}</td><td className="p-3">{x.room?.name||"—"}</td><td className="p-3"><Badge>{conflicts.has(x.id)?"CONFLICT":"CLEAR"}</Badge></td><td className="p-3 print:hidden"><form action={deleteTimetableAction}><input name="id" type="hidden" value={x.id}/><Submit danger>Delete</Submit></form></td></tr>)}</tbody></table></div>:<EmptyState icon={<CalendarDays/>} title="No timetable entries" description="Add a time slot in academic setup, then allocate the first period."/>}</div>; }
function Announcements({d}:{d:Data}) { const [q,setQ]=useState("");const rows=d.announcements.filter(x=>`${x.title} ${x.body}`.toLowerCase().includes(q.toLowerCase()));return <div className="space-y-5"><details className="rounded-2xl border bg-surface p-5"><summary className="cursor-pointer font-semibold"><Plus className="mr-2 inline h-4 w-4"/>Create announcement</summary><AnnouncementForm/></details><Input className="max-w-xl" onChange={e=>setQ(e.target.value)} placeholder="Search notices…"/>{rows.map(x=><Card className="p-5" key={x.id}><div className="flex flex-wrap justify-between gap-3"><div><Badge>{x.status}</Badge><h2 className="mt-2 text-lg font-semibold">{x.title}</h2><p className="text-sm text-muted-foreground">{x.roleKey||"Entire institution"} · {x.priority} · {when(x.scheduledAt||x.publishedAt||x.createdAt)}</p></div></div><p className="mt-3 text-sm">{x.body}</p>{x.attachmentUrl?<Link className="mt-3 inline-flex text-sm font-semibold text-sky-700" href={x.attachmentUrl}>Open attachment</Link>:null}<details className="mt-4"><summary className="cursor-pointer text-sm font-medium">Edit</summary><AnnouncementForm item={x}/></details><div className="mt-3 flex gap-2"><form action={archiveAnnouncementAction}><input name="id" type="hidden" value={x.id}/><Submit>Archive</Submit></form><form action={deleteAnnouncementAction}><input name="id" type="hidden" value={x.id}/><Submit danger>Delete</Submit></form></div></Card>)}</div>; }
function AnnouncementForm({item}:{item?:Data["announcements"][number]}) { return <form action={saveAnnouncementAction} className="mt-4 grid gap-3 md:grid-cols-2">{item?<input name="id" type="hidden" value={item.id}/>:null}<Input defaultValue={item?.title} name="title" placeholder="Notice title" required/><Select defaultValue={item?.roleKey??""} name="audience"><option value="">Entire institution</option><option>DEPARTMENT</option><option>ACADEMIC_FACULTY</option><option>STUDENT</option></Select><Select defaultValue={item?.priority??"NORMAL"} name="priority"><option>LOW</option><option>NORMAL</option><option>HIGH</option><option>URGENT</option></Select><Input defaultValue={item?.attachmentUrl??""} name="attachmentUrl" placeholder="Attachment URL" type="url"/><Input defaultValue={item?.scheduledAt?new Date(item.scheduledAt).toISOString().slice(0,16):""} name="scheduledAt" type="datetime-local"/><Textarea className="md:col-span-2" defaultValue={item?.body} name="body" placeholder="Professional announcement" required/><Button className="w-fit" type="submit">{item?"Save changes":"Publish or schedule"}</Button></form>; }
function Reports({d}:{d:Data}) { const departmentRows=d.departments.map(x=>({name:x.name,courses:x.courses.length,subjects:x.courses.reduce((n,c)=>n+c.subjects.length,0),students:x.courses.reduce((n,c)=>n+c.batches.reduce((m,b)=>m+b.students.length,0),0)}));return <div className="space-y-6"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Faculty Utilization" value={`${d.faculty.filter(x=>x.facultyBatches.length).length}/${d.faculty.length}`}/><Metric label="Student Enrollment" value={d.activeStudents}/><Metric label="Resource Usage" value={d.activities.filter(x=>x.type==="CONTENT").length}/><Metric label="AI Credits Used" value={d.aiUsage.credits}/></div><div className="grid gap-5 lg:grid-cols-2"><Card className="p-5"><h2 className="text-xl font-semibold">Department report</h2>{departmentRows.map(x=><div className="mt-3 rounded-xl border p-3 text-sm" key={x.name}><strong>{x.name}</strong><span className="block text-muted-foreground">{x.courses} courses · {x.subjects} subjects · {x.students} enrolled</span></div>)}</Card><Card className="p-5"><h2 className="text-xl font-semibold">Platform activity</h2>{d.activities.slice(0,10).map(x=><p className="mt-3 rounded-xl bg-muted p-3 text-sm" key={x.id}>{x.title}<span className="block text-muted-foreground">{x.type} · {when(x.createdAt)}</span></p>)}</Card></div><Button onClick={()=>exportJson("institution-reports",{generatedAt:new Date(),stats:d.stats,activeStudents:d.activeStudents,aiUsage:d.aiUsage,departments:departmentRows,faculty:d.faculty.map(x=>({name:x.name,status:x.status,classes:x.facultyBatches.length})),activity:d.activities})} type="button"><Download className="mr-2 h-4 w-4"/>Export reports</Button></div>; }
function InstitutionSettings({d}:{d:Data}) { const p=d.preferences;return <Card className="p-5"><h2 className="text-xl font-semibold">Institution settings</h2><form action={saveInstitutionPreferencesAction} className="mt-5 grid gap-4 md:grid-cols-2"><div><Label>Academic year label</Label><Input defaultValue={d.institution.academicYear??""} name="academicYear"/></div><div><Label>Timezone</Label><Input defaultValue={d.institution.timezone} name="timezone"/></div><div><Label>Currency</Label><Input defaultValue={d.institution.currency} name="currency"/></div><div><Label>Primary color</Label><Input defaultValue={d.institution.primaryColor} name="primaryColor" type="color"/></div><div><Label>Secondary color</Label><Input defaultValue={d.institution.secondaryColor} name="secondaryColor" type="color"/></div><div><Label>Permission policy</Label><Input defaultValue={val(p.permissions)} name="permissions" placeholder="Role-based institutional access"/></div><div><Label>Notification preferences</Label><Input defaultValue={val(p.notifications)} name="notifications" placeholder="Email and in-app"/></div><div><Label>Integrations</Label><Input defaultValue={val(p.integrations)} name="integrations" placeholder="Connected services"/></div><div><Label>Subscription information</Label><Input defaultValue={val(p.subscription)} name="subscription" placeholder="Institution plan"/></div><Button className="md:w-fit" type="submit">Save settings</Button></form></Card>; }

export function InstitutionWorkspacePage({module,data}:{module:InstitutionModule;data:Data}) { const label=modules.find(x=>x.slug===module)?.label;return <div className="space-y-6"><nav className="text-sm text-muted-foreground"><Link href="/admin">Admin</Link><span className="mx-2">/</span><Link href="/institution/dashboard">Institution Workspace</Link><span className="mx-2">/</span><span className="text-foreground">{label}</span></nav><section className="rounded-[2rem] border bg-gradient-to-br from-sky-50 via-white to-indigo-50 p-6 shadow-soft sm:p-8"><div className="flex flex-wrap justify-between gap-4"><div><Badge>Institution Workspace</Badge><h1 className="mt-4 text-4xl font-semibold tracking-tight">{label}</h1><p className="mt-3 max-w-3xl text-lg text-muted-foreground">{descriptions[module]}</p></div><Button onClick={()=>exportJson(module,data)} type="button" variant="secondary"><Download className="mr-2 h-4 w-4"/>Export</Button></div></section><nav className="flex gap-2 overflow-x-auto pb-2">{modules.map(x=>{const Icon=x.icon;return <Link className={`inline-flex shrink-0 items-center gap-2 rounded-full px-4 py-2 text-sm font-medium ${module===x.slug?"bg-primary text-primary-foreground":"border bg-surface"}`} href={`/institution/${x.slug}`} key={x.slug}><Icon className="h-4 w-4"/>{x.label}</Link>})}</nav>{module==="dashboard"?<Dashboard d={data}/>:module==="profile"?<Profile d={data}/>:module==="departments"?<Departments d={data}/>:module==="faculty"?<Faculty d={data}/>:module==="academics"?<Academics d={data}/>:module==="classes"?<Classes d={data}/>:module==="timetable"?<Timetable d={data}/>:module==="announcements"?<Announcements d={data}/>:module==="reports"?<Reports d={data}/>:<InstitutionSettings d={data}/>}</div>; }
