"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { ArrowUpRight, Bot, Download, Heart, PackageOpen, Search, ShoppingBag, Sparkles, Store, Wallet } from "lucide-react";
import type { getMarketXData } from "@/services/marketx-service";
import { EmptyState } from "@/components/ui/empty-state";

type Data = Awaited<ReturnType<typeof getMarketXData>>;
type View = "discover" | "creator" | "library" | "insights";

const views: { id: View; label: string; icon: typeof Store }[] = [
  { id: "discover", label: "Discover", icon: Sparkles }, { id: "creator", label: "Creator studio", icon: Store }, { id: "library", label: "My library", icon: PackageOpen }, { id: "insights", label: "AI growth", icon: Bot }
];

const formatMoney = (value: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value);

export function MarketXWorkspace({ data }: { data: Data }) {
  const [view, setView] = useState<View>("discover");
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("All");
  const items = useMemo(() => data.products.filter((product) => (category === "All" || product.category === category) && [product.title, product.description, product.creator, product.category].join(" ").toLowerCase().includes(query.toLowerCase())), [data.products, query, category]);
  const exportData = () => {
    const values = items.map(({ id, title, category: productCategory, creator, price, currency, downloads, views }) => ({ id, title, category: productCategory, creator, price, currency, downloads, views }));
    const blob = new Blob([JSON.stringify(values, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "marketx-discovery.json"; link.click(); URL.revokeObjectURL(url);
  };
  return <main className="mx-auto max-w-7xl space-y-6 pb-10">
    <header className="relative overflow-hidden border border-amber-200 bg-[#19130e] px-6 py-8 text-amber-50 shadow-2xl sm:px-9">
      <div className="absolute -right-20 -top-24 h-72 w-72 rounded-full bg-amber-400/20 blur-3xl"/><div className="absolute bottom-0 left-1/2 h-px w-1/2 bg-gradient-to-r from-transparent via-amber-300 to-transparent"/>
      <div className="relative flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.28em] text-amber-300">MarketX Guru · creator economy</p><h1 className="mt-3 max-w-3xl text-4xl font-black tracking-tight sm:text-5xl">Make knowledge travel further.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-amber-100/80">One shared marketplace for resources, creator evidence, purchases and commerce handoffs—built on the existing platform engine.</p></div><div className="flex gap-6 border-l border-amber-50/20 pl-5"><Stat label="Cart" value={data.buyer.cartCount}/><Stat label="Library" value={data.buyer.entitlements.length}/><Stat label="Wishlist" value={data.buyer.wishlistCount}/></div></div>
    </header>
    <nav className="flex gap-2 overflow-x-auto border-b border-border pb-3" aria-label="MarketX workspaces">{views.map(({ id, label, icon: Icon }) => <button key={id} onClick={() => setView(id)} className={`inline-flex shrink-0 items-center gap-2 border px-4 py-2.5 text-sm font-bold transition ${view === id ? "border-amber-700 bg-amber-700 text-white" : "border-border bg-surface text-muted-foreground hover:border-amber-500 hover:text-foreground"}`}><Icon className="h-4 w-4"/>{label}</button>)}</nav>
    {view === "discover" && <section className="space-y-6"><div className="grid gap-3 border border-border bg-surface p-3 md:grid-cols-[1fr_auto_auto]"><label className="flex items-center gap-2 border border-border bg-background px-3"><Search className="h-4 w-4 text-muted-foreground"/><input value={query} onChange={(event) => setQuery(event.target.value)} className="w-full bg-transparent py-3 text-sm outline-none" placeholder="Search lessons, templates, question banks…"/></label><select value={category} onChange={(event) => setCategory(event.target.value)} className="border border-border bg-background px-3 text-sm font-medium"><option>All</option>{data.categories.map((item) => <option key={item}>{item}</option>)}</select><button onClick={exportData} className="inline-flex items-center justify-center gap-2 border border-border px-4 text-sm font-bold hover:bg-muted"><Download className="h-4 w-4"/>Export</button></div><Collection title="Featured creators’ picks" sub="Curated from existing published marketplace listings" products={items.slice(0, 6)}/><div className="grid gap-6 xl:grid-cols-2"><Collection title="Trending now" sub="Ranked by existing resource views" products={data.collections.trending.filter((item) => items.some((match) => match.id === item.id)).slice(0, 4)}/><Collection title="Top downloads" sub="Based on fulfilled resource activity" products={data.collections.topSelling.filter((item) => items.some((match) => match.id === item.id)).slice(0, 4)}/></div></section>}
    {view === "creator" && <section className="space-y-6"><div className="grid overflow-hidden border border-border bg-border sm:grid-cols-2 xl:grid-cols-5">{[["Products",data.creator.products],["Published",data.creator.published],["Views",data.creator.views],["Downloads",data.creator.downloads],["Sales",formatMoney(data.creator.revenue)]].map(([label,value]) => <div className="bg-surface p-5" key={String(label)}><p className="text-xs font-bold uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-black">{value}</p></div>)}</div>{data.creator.hasStore ? <div className="grid gap-5 lg:grid-cols-2"><Panel title="Store & products" icon={Store}><p className="text-sm text-muted-foreground">Manage publishing, product approvals, portfolio and store evidence in the existing Teacher Business OS.</p><Link className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-amber-800" href="/teacher/business/marketplace">Open creator workspace <ArrowUpRight className="h-4 w-4"/></Link></Panel><Panel title="Revenue & orders" icon={Wallet}><p className="text-sm text-muted-foreground">{data.creator.orders} order records, with revenue calculated from paid and fulfilled shared commerce orders.</p><Link className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-amber-800" href="/teacher/business/orders">Open shared order records <ArrowUpRight className="h-4 w-4"/></Link></Panel></div> : <EmptyState icon={<Store className="h-5 w-5"/>} title="Your creator studio is ready" description="Publish a first resource through the existing Teacher Business workspace. Store branding, followers and reputation remain readiness states until their shared profile sources are available."/>}</section>}
    {view === "library" && <section className="grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><Panel title="Purchased library" icon={ShoppingBag}>{data.buyer.entitlements.length ? <div className="divide-y divide-border">{data.buyer.entitlements.map((item) => <div className="flex items-center justify-between gap-4 py-4" key={item.id}><div><p className="font-bold">{item.title}</p><p className="mt-1 text-xs text-muted-foreground">{item.type.replaceAll("_", " ")} · acquired {new Date(item.acquiredAt).toLocaleDateString()}</p></div><Link className="text-sm font-bold text-amber-800" href="/student/marketplace">Access</Link></div>)}</div> : <EmptyState icon={<PackageOpen className="h-5 w-5"/>} title="No entitlements yet" description="Purchases and downloads appear here automatically through the shared commerce entitlement service."/>}</Panel><div className="space-y-5"><Panel title="Shopping handoffs" icon={Heart}><p className="text-sm leading-6 text-muted-foreground">Your cart has {data.buyer.cartCount} item(s), and your wishlist has {data.buyer.wishlistCount}. Checkout, invoices, licenses and downloads remain owned by the existing buyer marketplace flow.</p><Link className="mt-4 inline-flex text-sm font-bold text-amber-800" href="/student/marketplace">Open buyer marketplace →</Link></Panel><Panel title="Review evidence" icon={Sparkles}><p className="text-sm text-muted-foreground">{data.buyer.reviews.length ? `${data.buyer.reviews.length} review record(s) are connected to your verified purchase evidence.` : "Your verified purchase reviews will appear after marketplace activity."}</p></Panel></div></section>}
    {view === "insights" && <section className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><Panel title="AI marketplace lens" icon={Bot}><p className="text-3xl font-black">{data.ai.requests}</p><p className="mt-1 text-sm text-muted-foreground">shared AI request(s) · {data.ai.tokens.toLocaleString()} tokens tracked</p><Link href="/tara" className="mt-5 inline-flex text-sm font-bold text-amber-800">Ask TARA about a listing →</Link></Panel><Panel title="Non-mutating suggestions" icon={Sparkles}><ol className="space-y-3">{data.ai.suggestions.map((item, index) => <li className="flex gap-3 text-sm leading-6" key={item}><span className="grid h-6 w-6 shrink-0 place-items-center bg-amber-100 text-xs font-black text-amber-900">0{index + 1}</span>{item}</li>)}</ol></Panel><aside className="border-l-2 border-amber-500 bg-amber-50 p-5 text-sm leading-6 text-amber-950 lg:col-span-2"><p className="font-black">Commerce integrity</p>{data.readiness.map((item) => <p className="mt-2" key={item}>{item}</p>)}</aside></section>}
  </main>;
}

function Stat({ label, value }: { label: string; value: number }) { return <div><p className="text-xs uppercase tracking-wider text-amber-200">{label}</p><p className="mt-1 text-xl font-black">{value}</p></div>; }
function Panel({ title, icon: Icon, children }: { title: string; icon: typeof Store; children: React.ReactNode }) { return <section className="border border-border bg-surface p-5 shadow-sm"><div className="flex items-center gap-2"><Icon className="h-4 w-4 text-amber-700"/><h2 className="font-black">{title}</h2></div><div className="mt-4">{children}</div></section>; }
function Collection({ title, sub, products }: { title: string; sub: string; products: Data["products"] }) { return <section><div className="mb-3"><h2 className="text-xl font-black">{title}</h2><p className="text-sm text-muted-foreground">{sub}</p></div>{products.length ? <div className="grid gap-px border border-border bg-border sm:grid-cols-2 xl:grid-cols-3">{products.map((product) => <article className="group bg-surface p-5" key={product.id}><p className="text-[11px] font-black uppercase tracking-wider text-amber-800">{product.category}</p><h3 className="mt-3 line-clamp-2 text-lg font-black">{product.title}</h3><p className="mt-2 line-clamp-2 text-sm leading-6 text-muted-foreground">{product.description}</p><div className="mt-4 flex items-end justify-between gap-3"><div><p className="text-sm font-bold">{formatMoney(product.price)}</p><p className="mt-1 text-xs text-muted-foreground">{product.creator} · {product.downloads} downloads</p></div><Link className="grid h-9 w-9 place-items-center border border-amber-700 text-amber-800 transition group-hover:bg-amber-700 group-hover:text-white" href={product.href} aria-label={`View ${product.title}`}><ArrowUpRight className="h-4 w-4"/></Link></div></article>)}</div> : <EmptyState icon={<Search className="h-5 w-5"/>} title="No resources match" description="Try a broader search or choose another category."/>}</section>; }
