"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { Bell, FileText, Search, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { setStudentNotificationStateAction } from "@/features/student-platform/actions";
import type { getStudentPlatform, StudentPlatformView } from "@/services/student-platform-service";

type Data = NonNullable<Awaited<ReturnType<typeof getStudentPlatform>>>;
const copy: Record<StudentPlatformView, [string, string]> = { search: ["Find your learning evidence", "Search resources, assignments, saved notes, and AI conversations in one student-safe space."], notifications: ["Your learning inbox", "Keep up with personal and institution notices without leaving LearnX."], timeline: ["Your learning timeline", "A concise record of the academic activity that matters to your next action."], files: ["Your learning files", "Published class material, saved notes, and download history—together."] };

export function StudentPlatformWorkspace({ data, initialView }: { data: Data; initialView: StudentPlatformView }) {
  const [query, setQuery] = useState(""); const [filter, setFilter] = useState("ALL"); const [title, description] = copy[initialView];
  return <main className="min-h-screen bg-gradient-to-br from-indigo-50 via-white to-cyan-50 px-4 py-7 sm:px-6"><div className="mx-auto max-w-6xl space-y-6"><section className="rounded-[2rem] border border-indigo-100 bg-white/85 p-6 shadow-soft sm:p-8"><p className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[.18em] text-indigo-700"><Sparkles className="h-4 w-4"/> LearnX command strip</p><div className="mt-4 flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">{title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">{description}</p></div><nav aria-label="Student command center" className="flex flex-wrap gap-2">{(["search", "notifications", "timeline", "files"] as const).map((view) => <Link className={`rounded-xl px-3 py-2 text-sm font-medium ${view === initialView ? "bg-indigo-600 text-white" : "border bg-white hover:bg-indigo-50"}`} href={`/student/${view}`} key={view}>{view[0].toUpperCase() + view.slice(1)}</Link>)}<Link className="rounded-xl border bg-white px-3 py-2 text-sm font-medium hover:bg-indigo-50" href="/student/profile">Profile</Link></nav></div></section>{initialView === "search" && <SearchPanel data={data} query={query} setQuery={setQuery} filter={filter} setFilter={setFilter}/>} {initialView === "notifications" && <Notifications data={data} query={query} setQuery={setQuery}/>} {initialView === "timeline" && <Timeline data={data} query={query} setQuery={setQuery} filter={filter} setFilter={setFilter}/>} {initialView === "files" && <Files data={data} query={query} setQuery={setQuery} filter={filter} setFilter={setFilter}/>}</div></main>;
}
function Tools({ query, setQuery, filter, setFilter, options = ["ALL"] }: { query: string; setQuery: (v: string) => void; filter: string; setFilter: (v: string) => void; options?: string[] }) { return <div className="flex flex-col gap-3 sm:flex-row"><label className="flex min-w-0 flex-1 items-center gap-2 rounded-xl border bg-white px-3"><Search className="h-4 w-4 text-indigo-600"/><input aria-label="Search" className="h-11 w-full bg-transparent text-sm outline-none" onChange={(event) => setQuery(event.target.value)} placeholder="Search your learning space" value={query}/></label>{options.length > 1 && <select aria-label="Filter" className="h-11 rounded-xl border bg-white px-3 text-sm" onChange={(event) => setFilter(event.target.value)} value={filter}>{options.map((option) => <option key={option}>{option}</option>)}</select>}</div>; }
function Empty({ children }: { children: string }) { return <Card className="border-dashed p-8 text-center text-sm text-muted-foreground">{children}</Card>; }
function SearchPanel({ data, query, setQuery, filter, setFilter }: { data: Data; query: string; setQuery: (v: string) => void; filter: string; setFilter: (v: string) => void }) { const kinds = ["ALL", ...Array.from(new Set(data.searchItems.map((item) => item.kind)))]; const rows = useMemo(() => data.searchItems.filter((item) => (filter === "ALL" || item.kind === filter) && `${item.title} ${item.detail}`.toLowerCase().includes(query.toLowerCase())), [data.searchItems, filter, query]); return <section className="space-y-4"><Tools filter={filter} options={kinds} query={query} setFilter={setFilter} setQuery={setQuery}/>{!query ? <Empty>Start with a title, topic, or saved learning item.</Empty> : rows.length ? <div className="grid gap-3">{rows.map((item) => <Link className="rounded-2xl border bg-white p-5 hover:border-indigo-300 hover:shadow-sm" href={item.href} key={item.id}><p className="text-xs font-semibold uppercase tracking-wide text-indigo-600">{item.kind}</p><h2 className="mt-1 font-semibold">{item.title}</h2><p className="mt-1 text-sm text-muted-foreground">{item.detail}</p></Link>)}</div> : <Empty>No learning evidence matches that search.</Empty>}</section>; }
function Notifications({ data, query, setQuery }: { data: Data; query: string; setQuery: (v: string) => void }) { const rows = data.notifications.filter((item) => `${item.title} ${item.body ?? ""}`.toLowerCase().includes(query.toLowerCase())); return <section className="space-y-4"><Tools filter="ALL" query={query} setFilter={() => undefined} setQuery={setQuery}/>{rows.length ? rows.map((item) => <Card className="p-5" key={item.id}><div className="flex gap-3"><Bell className={`mt-1 h-5 w-5 shrink-0 ${item.status === "UNREAD" ? "text-indigo-600" : "text-muted-foreground"}`}/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-semibold">{item.title}</h2><time className="text-xs text-muted-foreground">{item.createdAt.toLocaleString()}</time></div><p className="mt-1 text-sm text-muted-foreground">{item.body}</p><div className="mt-4 flex gap-2">{item.link && <Link className="text-sm font-medium text-indigo-700 hover:underline" href={item.link}>Open</Link>}{item.status === "UNREAD" && <form action={setStudentNotificationStateAction}><input name="id" type="hidden" value={item.id}/><input name="state" type="hidden" value="READ"/><Button className="h-8 px-2 text-xs" type="submit" variant="ghost">Mark read</Button></form>}<form action={setStudentNotificationStateAction}><input name="id" type="hidden" value={item.id}/><input name="state" type="hidden" value="ARCHIVED"/><Button className="h-8 px-2 text-xs" type="submit" variant="ghost">Archive</Button></form></div></div></div></Card>) : <Empty>Your notification inbox is clear.</Empty>}</section>; }
function Timeline({ data, query, setQuery, filter, setFilter }: { data: Data; query: string; setQuery: (v: string) => void; filter: string; setFilter: (v: string) => void }) { const types = ["ALL", ...Array.from(new Set(data.activities.map((item) => item.type)))]; const rows = data.activities.filter((item) => (filter === "ALL" || item.type === filter) && `${item.title} ${item.actor?.name ?? ""}`.toLowerCase().includes(query.toLowerCase())); return <section className="space-y-4"><Tools filter={filter} options={types} query={query} setFilter={setFilter} setQuery={setQuery}/>{rows.length ? <div className="space-y-3 border-l-2 border-cyan-200 pl-5">{rows.map((item) => <article className="relative" key={item.id}><span className="absolute -left-[1.78rem] top-5 h-3 w-3 rounded-full bg-indigo-500 ring-4 ring-indigo-50"/><Card className="p-4"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wide text-indigo-600">{item.type}</p><h2 className="mt-1 font-medium">{item.title}</h2>{item.actor?.name && <p className="mt-1 text-sm text-muted-foreground">{item.actor.name}</p>}</div><time className="shrink-0 text-xs text-muted-foreground">{item.createdAt.toLocaleDateString()}</time></div>{item.link && <Link className="mt-3 inline-block text-sm font-medium text-indigo-700 hover:underline" href={item.link}>Open related work</Link>}</Card></article>)}</div> : <Empty>No activity matches this filter.</Empty>}</section>; }
function Files({ data, query, setQuery, filter, setFilter }: { data: Data; query: string; setQuery: (v: string) => void; filter: string; setFilter: (v: string) => void }) { const groups = ["ALL", "Materials", "Notes", "Downloads"]; const rows = [{ group: "Materials", items: data.materials.map((item) => ({ id: item.id, title: item.title, detail: `${item.type} · ${item.subject?.name ?? item.classroom.title}`, href: item.fileUrl || "/student/resources" })) }, { group: "Notes", items: data.notes.map((item) => ({ id: item.id, title: item.title || "Untitled note", detail: item.targetType, href: "/student/bookmarks" })) }, { group: "Downloads", items: data.downloads.map((item) => ({ id: item.id, title: item.item.title, detail: `Downloaded ${item.downloadedAt.toLocaleDateString()}`, href: item.item.fileUrl || "/student/downloads" })) }].filter((group) => filter === "ALL" || group.group === filter).flatMap((group) => group.items.map((item) => ({ ...item, group: group.group }))).filter((item) => `${item.title} ${item.detail}`.toLowerCase().includes(query.toLowerCase())); return <section className="space-y-4"><Tools filter={filter} options={groups} query={query} setFilter={setFilter} setQuery={setQuery}/>{rows.length ? <div className="grid gap-3 sm:grid-cols-2">{rows.map((item) => <Link className="rounded-2xl border bg-white p-5 hover:border-cyan-300" href={item.href} key={`${item.group}-${item.id}`}><FileText className="h-5 w-5 text-cyan-600"/><p className="mt-4 text-xs font-semibold uppercase tracking-wide text-indigo-600">{item.group}</p><h2 className="mt-1 font-semibold">{item.title}</h2><p className="mt-1 text-sm text-muted-foreground">{item.detail}</p></Link>)}</div> : <Empty>No saved files match this filter.</Empty>}</section>; }