import Link from "next/link";
import { Bell, Bot, Languages, Lock, Palette, Shield, Store, UserRound, WifiOff } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Select } from "@/components/ui/select";
import { saveUnifiedTeacherSettingsAction } from "@/features/platform-integration/actions";
import type { getTeacherSettings } from "@/services/teacher-settings-service";

type Data=NonNullable<Awaited<ReturnType<typeof getTeacherSettings>>>;
const text=(x:unknown,fallback:string)=>typeof x==="string"?x:fallback;
export function TeacherUnifiedSettings({data}:{data:Data}){
  const enabled=new Set(data.notifications.filter(x=>x.enabled).map(x=>x.type));
  return <div className="space-y-8"><section className="rounded-[2rem] border bg-gradient-to-br from-sky-50 via-white to-blue-50 p-6 shadow-soft sm:p-8"><Badge>Unified Teacher Settings</Badge><h1 className="mt-5 text-4xl font-semibold tracking-tight">Settings</h1><p className="mt-3 max-w-3xl text-lg text-muted-foreground">Account, appearance, notifications, privacy, security, language, subscription, AI, marketplace, and offline preferences in one place.</p></section>
  <form action={saveUnifiedTeacherSettingsAction} className="grid gap-5 lg:grid-cols-2"><Card className="p-5"><Heading icon={UserRound} title="Account"/><p className="mt-4 font-medium">{data.user.name}</p><p className="text-sm text-muted-foreground">{data.user.email}</p><Link className="mt-4 inline-flex text-sm font-semibold text-sky-700" href="/profile">Open unified profile</Link></Card>
  <Card className="p-5"><Heading icon={Palette} title="Appearance"/><Label>Theme</Label><Select defaultValue={text(data.settings.appearance,"system")} name="appearance"><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option><option value="high-contrast">High contrast</option></Select></Card>
  <Card className="p-5"><Heading icon={Bell} title="Notifications"/><div className="mt-4 grid gap-3">{[["SYSTEM","System and subscription"],["CONTENT","AI, resources, and marketplace"],["ANNOUNCEMENT","Institution and community"],["ASSIGNMENT","Assignments and orders"],["PLANNER","Calendar and planner"]].map(([type,label])=><label className="flex items-center gap-3 text-sm" key={type}><input defaultChecked={enabled.has(type as never)} name="notificationTypes" type="checkbox" value={type}/>{label}</label>)}</div></Card>
  <Card className="p-5"><Heading icon={Shield} title="Privacy & Security"/><Label>Profile visibility</Label><Select defaultValue={text(data.settings.privacy,"professional")} name="privacy"><option value="professional">Professional community</option><option value="marketplace">Marketplace public</option><option value="private">Private</option></Select><label className="mt-4 flex items-center gap-3 text-sm"><input defaultChecked={data.settings.securityAlerts!==false} name="securityAlerts" type="checkbox"/>Security and login alerts</label></Card>
  <Card className="p-5"><Heading icon={Languages} title="Language"/><Select defaultValue={text(data.settings.language,"English")} name="language"><option>English</option><option>Hindi</option><option>Marathi</option><option>Tamil</option><option>Telugu</option><option>Bengali</option></Select></Card>
  <Card className="p-5"><Heading icon={Bot} title="AI Preferences"/><Select defaultValue={text(data.settings.aiStyle,"balanced")} name="aiStyle"><option value="balanced">Balanced</option><option value="concise">Concise</option><option value="detailed">Detailed</option><option value="activity-first">Activity first</option></Select></Card>
  <Card className="p-5"><Heading icon={Store} title="Marketplace & Community"/><label className="mt-4 flex items-center gap-3 text-sm"><input defaultChecked={data.settings.marketplaceEmails!==false} name="marketplaceEmails" type="checkbox"/>Marketplace, order, and resource updates</label><label className="mt-3 flex items-center gap-3 text-sm"><input defaultChecked={data.settings.communityDiscovery!==false} name="communityDiscovery" type="checkbox"/>Professional discovery and collaboration</label></Card>
  <Card className="p-5"><Heading icon={Lock} title="Subscription"/><p className="mt-4 font-semibold">{data.subscription?.plan.name??"No active plan"}</p><p className="text-sm text-muted-foreground">{data.subscription?`${data.subscription.status} · renews ${data.subscription.currentPeriodEnd?.toLocaleDateString()??"on plan schedule"}`:"Choose a plan to unlock subscription features."}</p><Link className="mt-4 inline-flex text-sm font-semibold text-sky-700" href="/teacher/business/subscription">Manage subscription</Link></Card>
  <Card className="p-5 lg:col-span-2"><Heading icon={WifiOff} title="Offline experience"/><label className="mt-4 flex items-center gap-3 text-sm"><input defaultChecked={data.settings.offlineHints!==false} name="offlineHints" type="checkbox"/>Show offline-friendly guidance when files or live data are unavailable</label></Card><Button className="lg:col-span-2 lg:w-fit" type="submit">Save unified settings</Button></form></div>;
}
function Heading({icon:Icon,title}:{icon:typeof UserRound;title:string}){return <div className="mb-4 flex items-center gap-3"><span className="rounded-xl bg-sky-50 p-2 text-sky-700"><Icon className="h-5 w-5"/></span><h2 className="text-xl font-semibold">{title}</h2></div>;}
