"use server";
import { Prisma } from "@prisma/client";
import { revalidatePath } from "next/cache";
import { auth } from "@/auth";
import { prisma } from "@/lib/db";

function value(data: FormData, key: string) { return String(data.get(key) ?? "").trim(); }
function list(data: FormData, key: string) { return value(data, key).split(",").map((x) => x.trim()).filter(Boolean); }
async function current() { const s = await auth(); if (!s?.user.id || !s.user.institutionId) throw new Error("Teacher community access is required."); return s; }
function refresh() { revalidatePath("/teacher/community", "layout"); }
function object(v: unknown) { return v && typeof v === "object" && !Array.isArray(v) ? v as Record<string, unknown> : {}; }
function array(v: unknown) { return Array.isArray(v) ? v.map(String) : []; }

export async function saveDiscussionAction(data: FormData) {
  const s = await current(); const id = value(data, "id"); const title = value(data, "title"); if (!title) return;
  const metadata = { category: value(data, "category") || "Teaching Practice", tags: list(data, "tags"), postType: value(data, "postType") || "QUESTION" };
  if (id) await prisma.genericDiscussion.updateMany({ where: { id, authorId: s.user.id }, data: { title, body: value(data, "body"), metadata } });
  else await prisma.genericDiscussion.create({ data: { institutionId: s.user.institutionId, authorId: s.user.id, title, body: value(data, "body"), scope: "INSTITUTION", communityId: value(data, "communityId") || undefined, metadata } });
  await prisma.activity.create({ data: { institutionId: s.user.institutionId, actorId: s.user.id, type: "SYSTEM", title: `${id ? "Updated" : "Published"} community discussion: ${title}`, link: "/teacher/community/discussions", metadata: { communityType: "COMMUNITY_POST" } } });
  refresh();
}
export async function deleteDiscussionAction(data: FormData) { const s = await current(); await prisma.genericDiscussion.deleteMany({ where: { id: value(data, "id"), authorId: s.user.id } }); refresh(); }
export async function replyDiscussionAction(data: FormData) { const s = await current(); const discussionId=value(data,"id"), body=value(data,"body"); if(!body)return; const mentions=list(data,"mentions").map(x=>x.replace(/^@/,"")); await prisma.genericDiscussionReply.create({data:{discussionId,authorId:s.user.id,body,metadata:{mentions}}}); const discussion=await prisma.genericDiscussion.update({where:{id:discussionId},data:{updatedAt:new Date()}}); const mentioned=mentions.length?await prisma.user.findMany({where:{institutionId:s.user.institutionId!,OR:mentions.flatMap(name=>[{name:{equals:name,mode:"insensitive" as const}},{email:{equals:name,mode:"insensitive" as const}}])},select:{id:true}}):[]; const recipients=Array.from(new Set([discussion.authorId,...mentioned.map(x=>x.id)].filter((id):id is string=>Boolean(id)&&id!==s.user.id)));if(recipients.length)await prisma.notification.createMany({data:recipients.map(userId=>({userId,institutionId:s.user.institutionId,title:mentioned.some(x=>x.id===userId)?"You were mentioned":"New discussion reply",body:discussion.title,link:"/teacher/community/discussions",metadata:{category:mentioned.some(x=>x.id===userId)?"MENTION":"REPLY",discussionId}}))}); refresh(); }
export async function deleteReplyAction(data: FormData) { const s=await current(); await prisma.genericDiscussionReply.deleteMany({where:{id:value(data,"id"),authorId:s.user.id}}); refresh(); }
async function mutateDiscussion(data:FormData, fn:(m:Record<string,unknown>,s:Awaited<ReturnType<typeof current>>)=>Record<string,unknown>) { const s=await current();const d=await prisma.genericDiscussion.findUnique({where:{id:value(data,"id")}});if(!d)return;await prisma.genericDiscussion.update({where:{id:d.id},data:{metadata:fn(object(d.metadata),s) as Prisma.InputJsonValue}});refresh(); }
export async function likeDiscussionAction(data:FormData){const s=await current();const d=await prisma.genericDiscussion.findUnique({where:{id:value(data,"id")}});if(!d)return;const m=object(d.metadata),x=array(m.likes),removing=x.includes(s.user.id);await prisma.genericDiscussion.update({where:{id:d.id},data:{metadata:{...m,likes:removing?x.filter(id=>id!==s.user.id):[...x,s.user.id]} as Prisma.InputJsonValue}});if(!removing&&d.authorId&&d.authorId!==s.user.id)await prisma.notification.create({data:{userId:d.authorId,institutionId:s.user.institutionId,title:"Your discussion was appreciated",body:d.title,link:"/teacher/community/discussions",metadata:{category:"LIKE",discussionId:d.id}}});refresh();}
export async function reportDiscussionAction(data:FormData){return mutateDiscussion(data,(m,s)=>({...m,reports:Array.from(new Set([...array(m.reports),s.user.id])),reportReason:value(data,"reason")}))}
export async function bestAnswerAction(data:FormData){return mutateDiscussion(data,(m)=>({...m,bestAnswerId:value(data,"replyId")}))}
export async function toggleCommunityBookmarkAction(data:FormData){const s=await current();const type=value(data,"type"),entityId=value(data,"entityId");const key={userId_type_entityId:{userId:s.user.id,type,entityId}};const found=await prisma.favoriteItem.findUnique({where:key});if(found)await prisma.favoriteItem.delete({where:{id:found.id}});else await prisma.favoriteItem.create({data:{userId:s.user.id,type,entityId,title:value(data,"title"),link:value(data,"link")||undefined}});refresh();}

export async function saveGroupAction(data:FormData){const s=await current();const id=value(data,"id"),name=value(data,"name");if(!name)return;const payload={name,description:value(data,"description"),visibility:(value(data,"visibility")||"PUBLIC") as "PUBLIC"|"PRIVATE"|"INVITE_ONLY",metadata:{settings:value(data,"settings"),sharedResources:list(data,"resources")}};if(id)await prisma.community.updateMany({where:{id,createdById:s.user.id},data:payload});else await prisma.community.create({data:{institutionId:s.user.institutionId,createdById:s.user.id,type:"TEACHER_GROUP",...payload,members:{create:{userId:s.user.id,role:"OWNER"}}}});refresh();}
export async function deleteGroupAction(data:FormData){const s=await current();await prisma.community.deleteMany({where:{id:value(data,"id"),createdById:s.user.id}});refresh();}
export async function joinGroupAction(data:FormData){const s=await current();const group=await prisma.community.findUnique({where:{id:value(data,"id")}});if(!group)return;if(group.visibility==="PRIVATE"||group.visibility==="INVITE_ONLY"){await prisma.notification.create({data:{userId:group.createdById,institutionId:s.user.institutionId,title:"Group join request",body:`${s.user.name} requested to join ${group.name}.`,link:"/teacher/community/groups",metadata:{category:"GROUP_REQUEST",groupId:group.id,requesterId:s.user.id}}})}else await prisma.communityMember.upsert({where:{communityId_userId:{communityId:group.id,userId:s.user.id}},update:{},create:{communityId:group.id,userId:s.user.id}});refresh();}
export async function leaveGroupAction(data:FormData){const s=await current();await prisma.communityMember.deleteMany({where:{communityId:value(data,"id"),userId:s.user.id,role:{not:"OWNER"}}});refresh();}
export async function inviteGroupMemberAction(data:FormData){const s=await current();const userId=value(data,"userId"),groupId=value(data,"id");const group=await prisma.community.findFirst({where:{id:groupId,members:{some:{userId:s.user.id}}}});if(!group||!userId)return;await prisma.notification.create({data:{userId,institutionId:s.user.institutionId,title:"Teacher group invitation",body:`${s.user.name} invited you to ${group.name}.`,link:"/teacher/community/groups",metadata:{category:"GROUP_INVITATION",groupId}}});refresh();}

export async function toggleTeacherRelationAction(data:FormData){const s=await current();const target=value(data,"userId"),type=value(data,"type");const key={userId_type_entityId:{userId:s.user.id,type,entityId:target}};const found=await prisma.favoriteItem.findUnique({where:key});if(found)await prisma.favoriteItem.delete({where:{id:found.id}});else {await prisma.favoriteItem.create({data:{userId:s.user.id,type,entityId:target,title:value(data,"title"),link:value(data,"link")}});if(type==="teacher-connection-request")await prisma.notification.create({data:{userId:target,institutionId:s.user.institutionId,title:"Professional connection request",body:`${s.user.name} would like to connect.`,link:"/teacher/community/network",metadata:{category:"CONNECTION_REQUEST",requesterId:s.user.id}}})}refresh();}

export async function createConversationAction(data:FormData){const s=await current();const target=value(data,"userId");if(!target)return;await prisma.directConversation.create({data:{institutionId:s.user.institutionId,createdById:s.user.id,type:"TEACHER_TEACHER",status:"ACTIVE",title:value(data,"title")||"Professional conversation",participants:{create:[{userId:s.user.id,role:"OWNER"},{userId:target,role:"MEMBER"}]},messages:value(data,"body")?{create:{senderId:s.user.id,body:value(data,"body"),attachments:{urls:list(data,"attachments"),resources:list(data,"resources")}}}:undefined}});refresh();}
export async function sendMessageAction(data:FormData){const s=await current();const conversationId=value(data,"id");const access=await prisma.directConversation.findFirst({where:{id:conversationId,participants:{some:{userId:s.user.id,archivedAt:null}}}});if(!access||!value(data,"body"))return;await prisma.directMessage.create({data:{conversationId,senderId:s.user.id,body:value(data,"body"),attachments:{urls:list(data,"attachments"),resources:list(data,"resources")}}});await prisma.directConversation.update({where:{id:conversationId},data:{updatedAt:new Date()}});refresh();}
export async function archiveConversationAction(data:FormData){const s=await current();await prisma.directConversationParticipant.updateMany({where:{conversationId:value(data,"id"),userId:s.user.id},data:{archivedAt:value(data,"restore")==="true"?null:new Date()}});refresh();}
export async function markConversationReadAction(data:FormData){const s=await current();const id=value(data,"id");await prisma.directConversationParticipant.updateMany({where:{conversationId:id,userId:s.user.id},data:{lastReadAt:new Date()}});await prisma.directMessage.updateMany({where:{conversationId:id,senderId:{not:s.user.id},readAt:null},data:{readAt:new Date(),status:"READ"}});refresh();}

export async function saveCollaborationAction(data:FormData){const s=await current();const id=value(data,"id");const key=id?value(data,"key"):`teacher-collaboration:${crypto.randomUUID()}`;const payload={title:value(data,"title"),type:value(data,"type"),collaboratorId:value(data,"collaboratorId"),status:value(data,"status")||"REQUESTED",resourceIds:list(data,"resources"),collection:value(data,"collection"),activity:[{at:new Date().toISOString(),actor:s.user.name,action:id?"Updated collaboration":"Created collaboration"}]};if(id)await prisma.userPreference.updateMany({where:{id,userId:s.user.id,key:{startsWith:"teacher-collaboration:"}},data:{value:payload}});else {await prisma.userPreference.create({data:{userId:s.user.id,key,value:payload}});if(payload.collaboratorId)await prisma.notification.create({data:{userId:payload.collaboratorId,institutionId:s.user.institutionId,title:"Collaboration invitation",body:payload.title,link:"/teacher/community/collaboration",metadata:{category:"COLLABORATION"}}})}refresh();}
export async function deleteCollaborationAction(data:FormData){const s=await current();await prisma.userPreference.deleteMany({where:{id:value(data,"id"),userId:s.user.id,key:{startsWith:"teacher-collaboration:"}}});refresh();}
export async function shareResourceAction(data:FormData){const s=await current();const resource=await prisma.contentItem.findFirst({where:{id:value(data,"id"),institutionId:s.user.institutionId!}});if(!resource)return;await prisma.genericDiscussion.create({data:{institutionId:s.user.institutionId,authorId:s.user.id,title:`Resource: ${resource.title}`,body:value(data,"message")||resource.description||undefined,scope:"INSTITUTION",metadata:{category:"Resource Sharing",postType:"RESOURCE",resourceId:resource.id,tags:list(data,"tags")}}});refresh();}
export async function markCommunityNotificationAction(data:FormData){const s=await current();await prisma.notification.updateMany({where:{id:value(data,"id"),userId:s.user.id},data:{status:"READ",readAt:new Date()}});refresh();}
export async function deleteCommunityNotificationAction(data:FormData){const s=await current();await prisma.notification.deleteMany({where:{id:value(data,"id"),userId:s.user.id}});refresh();}
