"use server";
import { revalidatePath } from "next/cache";
import { auth } from "@/auth";
import { prisma } from "@/lib/db";
import { saveStudentAssignmentDraft,submitStudentAssignment } from "@/services/assignment-workflow-service";
function attachment(form:FormData){const urls=form.getAll("attachmentUrl").map(String),names=form.getAll("attachmentName").map(String),types=form.getAll("attachmentType").map(String),sizes=form.getAll("attachmentSize").map(String);return urls.flatMap((url,i)=>url.trim()?[{url:url.trim(),name:(names[i]??"External attachment").trim()||"External attachment",mediaType:(types[i]??"application/octet-stream").trim(),...(sizes[i]?.trim()?{sizeBytes:Number(sizes[i])}:{})}]:[])}
async function student(){const s=await auth();if(!s?.user.id||!s.user.institutionId||!s.user.roles.includes("STUDENT"))throw new Error("Student access required.");return{id:s.user.id,institutionId:s.user.institutionId}}
export async function saveDraftAction(_:string|undefined,form:FormData){try{const s=await student();await saveStudentAssignmentDraft({userId:s.id,institutionId:s.institutionId,assignmentId:String(form.get("assignmentId")??""),text:String(form.get("text")??""),attachments:attachment(form)});revalidatePath("/student/assignments");return"Draft saved."}catch(e){return e instanceof Error?e.message:"Draft could not be saved."}}
export async function submitAssignmentAction(_:string|undefined,form:FormData){try{const s=await student();const result=await submitStudentAssignment({userId:s.id,institutionId:s.institutionId,assignmentId:String(form.get("assignmentId")??""),text:String(form.get("text")??""),attachments:attachment(form)});revalidatePath("/student/assignments");return`Version ${result.version} submitted${result.status==="LATE"?" late":""}.`}catch(e){return e instanceof Error?e.message:"Submission failed."}}
export async function raiseAssignmentDoubtAction(_:string|undefined,form:FormData){try{const s=await student(),assignmentId=String(form.get("assignmentId")??""),message=String(form.get("message")??"").trim().slice(0,1000);if(message.length<3)return"Enter a clear academic question.";const assignment=await prisma.assignment.findFirst({where:{id:assignmentId,status:"PUBLISHED",classroom:{institutionId:s.institutionId,batch:{students:{some:{studentId:s.id}}}}},select:{title:true,classroomId:true,classroom:{select:{batch:{select:{faculty:{select:{facultyId:true}}}}}}}});if(!assignment)return"Assignment is unavailable.";const recipients=[...new Set(assignment.classroom.batch.faculty.map(x=>x.facultyId))];if(!recipients.length)return"No assigned teacher is available for a private doubt.";await prisma.$transaction(async tx=>{const doubt=await tx.assignmentDoubt.upsert({where:{assignmentId_studentId:{assignmentId,studentId:s.id}},create:{assignmentId,studentId:s.id},update:{status:"OPEN"}});await tx.assignmentDoubtMessage.create({data:{doubtId:doubt.id,authorId:s.id,body:message}});await tx.notification.createMany({data:recipients.map(userId=>({institutionId:s.institutionId,userId,title:`Student doubt: ${assignment.title}`,body:"A student sent a private assignment question.",link:`/classrooms/${assignment.classroomId}`,metadata:{assignmentId,studentId:s.id,doubtId:doubt.id,kind:"ASSIGNMENT_DOUBT"}}))})});return"Question added to the private teacher thread."}catch(e){return e instanceof Error?e.message:"Question could not be sent."}}