"use client";

import { useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, Clock3, Database, Save, ShieldCheck } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";

type RequestItem={id:string;type:string;status:string;details:string|null;assignedToId:string|null;resolution:string|null;legalHold:boolean;dueAt:string;user:{name:string;email:string};events:{id:string;status:string;note:string;createdAt:string}[]};
type Retention={id:string;dataset:string;retentionDays:number;legalBasis:string;disposition:string;enabled:boolean};
type Props={data:{config:{live:boolean;policyVersion:string};metrics:{open:number;overdue:number;legalHolds:number};requests:RequestItem[];retention:Retention[]}};
const transitions:Record<string,string[]>={SUBMITTED:["IDENTITY_VERIFICATION","IN_REVIEW","CANCELLED"],IDENTITY_VERIFICATION:["IN_REVIEW","REJECTED","CANCELLED"],IN_REVIEW:["APPROVED","REJECTED","CANCELLED"],APPROVED:["FULFILLED","REJECTED"],FULFILLED:[],REJECTED:[],CANCELLED:[]};
async function send(url:string,method:string,body:unknown){const response=await fetch(url,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error??"Operation failed");}

export function PrivacyAdministration({data}:Props){
 const [query,setQuery]=useState(""),[status,setStatus]=useState("OPEN"),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const rows=useMemo(()=>data.requests.filter(item=>`${item.user.name} ${item.user.email} ${item.type} ${item.status}`.toLowerCase().includes(query.toLowerCase())).filter(item=>status==="ALL"||(status==="OPEN"?!["FULFILLED","REJECTED","CANCELLED"].includes(item.status):item.status===status)),[data.requests,query,status]);
 const run=async(work:()=>Promise<void>)=>{setBusy(true);setError("");try{await work();window.location.reload();}catch(cause){setError(cause instanceof Error?cause.message:"Operation failed");setBusy(false);}};
 return <main className="space-y-7 pb-12">
  <header className="border-b border-border pb-7"><div className="flex flex-wrap items-center gap-3"><Badge>Phase 21</Badge><span className="text-sm text-muted-foreground">Policy {data.config.policyVersion}</span></div><div className="mt-4 flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-semibold">Privacy governance</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Rights requests, deadlines, legal holds, consent evidence, and retention decisions in one governed operating view.</p></div><span className={data.config.live?"flex items-center gap-2 text-sm font-semibold text-emerald-700":"flex items-center gap-2 text-sm font-semibold text-amber-700"}>{data.config.live?<CheckCircle2 className="h-5 w-5"/>:<AlertTriangle className="h-5 w-5"/>}{data.config.live?"Privacy evidence current":"Railway evidence required"}</span></div></header>
  {error?<p className="border-y border-red-300 bg-red-50 px-4 py-3 text-sm text-red-900" role="alert">{error}</p>:null}
  <section className="grid gap-px overflow-hidden rounded-lg border bg-border sm:grid-cols-3"><Metric icon={<Clock3/>} label="Open requests" value={data.metrics.open}/><Metric icon={<AlertTriangle/>} label="Overdue" value={data.metrics.overdue}/><Metric icon={<ShieldCheck/>} label="Legal holds" value={data.metrics.legalHolds}/></section>
  <section><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-lg font-semibold">Rights request queue</h2><p className="mt-1 text-sm text-muted-foreground">Verify identity outside free-text notes. Never upload identity documents here.</p></div><div className="flex gap-2"><Input className="w-64" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search person or request"/><Select className="w-40" value={status} onChange={e=>setStatus(e.target.value)}><option value="OPEN">Open</option><option value="ALL">All</option><option value="FULFILLED">Fulfilled</option><option value="REJECTED">Rejected</option><option value="CANCELLED">Cancelled</option></Select></div></div>
   <div className="mt-4 divide-y divide-border border-y border-border">{rows.length?rows.map(item=><article className="py-5" key={item.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><Badge>{item.type}</Badge><strong>{item.user.name}</strong></div><p className="mt-1 text-sm text-muted-foreground">{item.user.email} · due {new Date(item.dueAt).toLocaleDateString()}</p></div><Badge>{item.status.toLowerCase().replaceAll("_"," ")}</Badge></div>{item.details?<p className="mt-3 text-sm leading-6 text-muted-foreground">{item.details}</p>:null}
    {transitions[item.status]?.length?<form className="mt-4 grid gap-3 lg:grid-cols-[180px_1fr_220px_auto]" onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);void run(()=>send("/api/privacy/admin/requests","PATCH",{id:item.id,status:form.get("status"),note:form.get("note"),assignedToId:form.get("assignedToId")||undefined,resolution:form.get("resolution")||undefined,legalHold:form.get("legalHold")==="on"}));}}><Select name="status" defaultValue={transitions[item.status][0]}>{transitions[item.status].map(next=><option key={next} value={next}>{next.toLowerCase().replaceAll("_"," ")}</option>)}</Select><Textarea className="min-h-12" name="note" required minLength={5} placeholder="Auditable internal update"/><div className="space-y-2"><Input name="assignedToId" defaultValue={item.assignedToId??""} placeholder="Owner name or ID"/><label className="flex items-center gap-2 text-xs"><input defaultChecked={item.legalHold} name="legalHold" type="checkbox"/>Legal hold</label><Input name="resolution" defaultValue={item.resolution??""} placeholder="Resolution basis"/></div><Button disabled={busy} type="submit"><Save className="mr-2 h-4 w-4"/>Update</Button></form>:null}
    <details className="mt-3"><summary className="cursor-pointer text-sm font-medium">Audit timeline</summary><ol className="mt-3 space-y-2">{item.events.map(event=><li className="border-l-2 border-border pl-3 text-sm" key={event.id}><strong>{event.status.toLowerCase().replaceAll("_"," ")}</strong><span className="ml-2 text-muted-foreground">{new Date(event.createdAt).toLocaleString()}</span><p className="mt-1 text-muted-foreground">{event.note}</p></li>)}</ol></details></article>):<p className="py-7 text-sm text-muted-foreground">No privacy requests match this view.</p>}</div></section>
  <section className="border-t border-border pt-6"><div className="flex items-center gap-3"><Database className="h-5 w-5 text-primary"/><h2 className="text-lg font-semibold">Retention register</h2></div><div className="mt-4 divide-y divide-border border-y border-border">{data.retention.map(policy=><form className="grid gap-3 py-5 lg:grid-cols-[220px_130px_1fr_1fr_auto] lg:items-end" key={policy.id} onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);void run(()=>send("/api/privacy/admin/retention","PUT",{id:policy.id,retentionDays:Number(form.get("retentionDays")),legalBasis:form.get("legalBasis"),disposition:form.get("disposition"),enabled:form.get("enabled")==="on"}));}}><div><strong>{policy.dataset}</strong><label className="mt-2 flex items-center gap-2 text-xs"><input defaultChecked={policy.enabled} name="enabled" type="checkbox"/>Policy active</label></div><label className="text-xs text-muted-foreground">Days<Input className="mt-1" defaultValue={policy.retentionDays} name="retentionDays" type="number" min={1} max={3650}/></label><label className="text-xs text-muted-foreground">Legal basis<Input className="mt-1" defaultValue={policy.legalBasis} name="legalBasis" required/></label><label className="text-xs text-muted-foreground">Disposition<Input className="mt-1" defaultValue={policy.disposition} name="disposition" required/></label><Button disabled={busy} type="submit"><Save className="mr-2 h-4 w-4"/>Review</Button></form>)}</div></section>
 </main>;
}

function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:number}){return <div className="bg-background p-5"><span className="block h-5 w-5 text-primary">{icon}</span><p className="mt-2 text-sm text-muted-foreground">{label}</p><strong className="mt-1 block text-2xl">{value}</strong></div>}
