"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { BellRing, Download, HeartPulse, LifeBuoy, Settings2, Sparkles, Users } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import type { getAdminCustomerSuccessData } from "@/services/admin-customer-success-service";

type Data = Awaited<ReturnType<typeof getAdminCustomerSuccessData>>;
type View = "overview" | "support" | "health" | "onboarding" | "adoption" | "communications" | "knowledge" | "ai" | "reports" | "settings";
const tabs: { id: View; label: string }[] = [{ id: "overview", label: "Success pulse" }, { id: "support", label: "Support" }, { id: "health", label: "Customer health" }, { id: "onboarding", label: "Onboarding" }, { id: "adoption", label: "Adoption" }, { id: "communications", label: "Communications" }, { id: "knowledge", label: "Knowledge" }, { id: "ai", label: "AI assist" }, { id: "reports", label: "Reports" }, { id: "settings", label: "Settings" }];
const exportRows = (name: string, rows: unknown, format: "csv" | "json") => { const list = Array.isArray(rows) ? rows as Record<string, unknown>[] : [rows as Record<string, unknown>]; const keys = [...new Set(list.flatMap(Object.keys))]; const quote = (v: unknown) => { const raw = String(typeof v === "object" ? JSON.stringify(v) : v ?? ""); const safe = /^[=+\-@]/.test(raw) ? `'${raw}` : raw; return `"${safe.replace(/"/g, '""')}"`; }; const text = format === "json" ? JSON.stringify(rows, null, 2) : [keys.map(quote).join(","), ...list.map((row) => keys.map((key) => quote(row[key])).join(","))].join("\r\n"); const url = URL.createObjectURL(new Blob([text], { type: format === "csv" ? "text/csv" : "application/json" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `adminx-${name}.${format}`; anchor.click(); URL.revokeObjectURL(url); };
function Metric({ label, value, note }: { label: string; value: string | number; note?: string }) { return <Card className="p-4"><p className="text-xs font-semibold uppercase tracking-[.12em] text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold tracking-tight">{value}</p>{note && <p className="mt-1 text-xs text-muted-foreground">{note}</p>}</Card>; }
function Readiness({ title, body }: { title: string; body: string }) { return <Card className="border-dashed p-5"><Badge>Source readiness</Badge><h3 className="mt-3 font-semibold">{title}</h3><p className="mt-1 text-sm text-muted-foreground">{body}</p></Card>; }

export function CustomerSuccessOS({ data }: { data: Data }) {
  const saved = (data.preferences && typeof data.preferences === "object" && !Array.isArray(data.preferences) ? data.preferences : {}) as { compact?: boolean; exportFormat?: "csv" | "json" };
  const [view, setView] = useState<View>("overview"); const [query, setQuery] = useState(""); const [filter, setFilter] = useState("ALL"); const [sort, setSort] = useState("health"); const [compact, setCompact] = useState(Boolean(saved.compact)); const [format, setFormat] = useState<"csv" | "json">(saved.exportFormat === "json" ? "json" : "csv"); const [saving, setSaving] = useState(false); const [saveMessage, setSaveMessage] = useState("");
  const tenants = useMemo(() => data.tenants.filter((item) => `${item.name} ${item.email ?? ""}`.toLowerCase().includes(query.toLowerCase())).filter((item) => filter === "ALL" || (filter === "RISK" && item.health < 70) || (filter === "OPEN" && item.open > 0) || (filter === "ONBOARDING" && item.onboarding < 75)).sort((a, b) => sort === "name" ? a.name.localeCompare(b.name) : sort === "tickets" ? b.open - a.open : a.health - b.health), [data.tenants, query, filter, sort]);
  const filteredTickets = useMemo(() => data.tickets.filter((ticket) => `${ticket.subject} ${ticket.institution?.name ?? ""}`.toLowerCase().includes(query.toLowerCase())).filter((ticket) => filter === "ALL" || (filter === "OPEN" && ["OPEN", "IN_REVIEW"].includes(ticket.status)) || (filter === "RISK" && ["HIGH", "URGENT"].includes(ticket.priority)) || (filter === "ONBOARDING" && Boolean(ticket.institutionId && data.tenants.find((tenant) => tenant.id === ticket.institutionId && tenant.onboarding < 75)))).sort((a, b) => sort === "name" ? a.subject.localeCompare(b.subject) : sort === "tickets" ? Number(b.priority === "URGENT") - Number(a.priority === "URGENT") : new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime()), [data.tickets, data.tenants, query, filter, sort]);
  const filteredCommunications = useMemo(() => data.communications.filter((item) => item.title.toLowerCase().includes(query.toLowerCase())).filter((item) => filter === "ALL" || (filter === "OPEN" && item.logs.length === 0) || (filter === "RISK" && item.logs.length < item.recipients.length) || (filter === "ONBOARDING" && !item.institutionId)).sort((a, b) => sort === "name" ? a.title.localeCompare(b.title) : new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime()), [data.communications, query, filter, sort]);
  const controls = <div className="grid gap-3 md:grid-cols-[1fr_150px_150px_auto]"><Input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search institution or contact"/><Select value={filter} onChange={(e) => setFilter(e.target.value)}><option value="ALL">All customers</option><option value="RISK">At risk</option><option value="OPEN">Open support</option><option value="ONBOARDING">Onboarding</option></Select><Select value={sort} onChange={(e) => setSort(e.target.value)}><option value="health">Health: low first</option><option value="tickets">Open tickets</option><option value="name">Name A-Z</option></Select><Button variant="secondary" onClick={() => exportRows(view === "support" ? "support-queue" : view === "communications" ? "communications" : "customer-list", view === "support" ? filteredTickets : view === "communications" ? filteredCommunications : tenants, format)}><Download className="mr-2 h-4 w-4"/>Export</Button></div>;
  const hero = <><section className="relative overflow-hidden rounded-[2rem] border bg-slate-950 p-6 text-slate-50 shadow-soft sm:p-8"><div className="absolute -right-20 -top-24 h-80 w-80 rounded-full bg-cyan-400/20 blur-3xl"/><div className="relative flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-cyan-200">AdminX Guru / customer success OS</p><h1 className="mt-3 max-w-3xl text-3xl font-semibold tracking-tight sm:text-4xl">A calm view of customers who need a hand.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-300">Institution health and support activity from existing tenant, ticket, communication, subscription, and AI usage data. Anything not measured remains visible as a readiness need.</p></div><Button variant="secondary" onClick={() => exportRows("success-snapshot", data, format)}><Download className="mr-2 h-4 w-4"/>Export snapshot</Button></div></section><nav className="flex gap-2 overflow-x-auto py-1">{tabs.map((tab) => <button key={tab.id} onClick={() => setView(tab.id)} className={view === tab.id ? "shrink-0 rounded-full bg-primary px-4 py-2 text-sm font-medium text-primary-foreground" : "shrink-0 rounded-full border bg-surface px-4 py-2 text-sm font-medium hover:bg-muted"}>{tab.label}</button>)}</nav></>;
  let content: React.ReactNode;
  if (view === "overview") content = <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Customer health" value={`${data.metrics.averageHealth}%`} note="Derived support/subscription signal"/><Metric label="Open tickets" value={data.metrics.openTickets}/><Metric label="Urgent escalations" value={data.metrics.escalations}/><Metric label="Onboarding attention" value={data.metrics.onboardingAttention}/><Metric label="Customers at risk" value={data.metrics.atRisk}/></div><div className="grid gap-5 xl:grid-cols-[1.3fr_1fr]"><Card className="p-5"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">Intervention queue</h2><HeartPulse className="h-5 w-5 text-cyan-600"/></div><div className="mt-4 space-y-3">{tenants.filter((x) => x.health < 70 || x.urgent || x.onboarding < 75).length ? tenants.filter((x) => x.health < 70 || x.urgent || x.onboarding < 75).slice(0, 7).map((x) => <div className="rounded-xl border-l-2 border-amber-500 bg-amber-50/60 p-3" key={x.id}><div className="flex justify-between gap-3"><strong>{x.name}</strong><Badge>{x.health}% health</Badge></div><p className="mt-1 text-sm text-muted-foreground">{x.urgent ? `${x.urgent} urgent support item(s). ` : ""}{x.open ? `${x.open} open ticket(s). ` : ""}{x.onboarding < 75 ? `Onboarding evidence is ${x.onboarding}%.` : "Review recent usage and renewal signals."}</p><Link href="/admin/support" className="mt-2 inline-block text-xs font-semibold text-primary hover:underline">Open existing support workflow</Link></div>) : <EmptyState icon={<HeartPulse/>} title="No interventions need attention" description="No current tenant has a low health, urgent support, or incomplete onboarding signal."/>}</div></Card><div className="space-y-3"><Readiness title="Satisfaction and renewal pipeline" body={data.readiness.satisfaction}/><Readiness title="SLA & escalation rules" body={data.readiness.sla}/><Card className="p-5"><h3 className="font-semibold">Today's operational focus</h3><p className="mt-2 text-sm text-muted-foreground">Prioritize urgent tickets, low-health institutions, and incomplete go-live evidence before outbound communication.</p></Card></div></div></div>;
  else if (view === "support") content = <div className="space-y-4">{controls}<div className="flex justify-end"><Link href="/admin/support" className="text-sm font-medium text-primary hover:underline">Open existing support center</Link></div>{filteredTickets.length ? <div className="overflow-x-auto rounded-2xl border"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-muted"><tr><th className="p-3">Ticket</th><th className="p-3">Institution</th><th className="p-3">Priority</th><th className="p-3">Status</th><th className="p-3">Owner</th><th className="p-3">Updated</th></tr></thead><tbody>{filteredTickets.map((t) => <tr className="border-t" key={t.id}><td className="p-3"><strong>{t.subject}</strong><span className="block text-xs text-muted-foreground">{t.type}</span></td><td className="p-3">{t.institution?.name ?? "Platform"}</td><td className="p-3"><Badge>{t.priority}</Badge></td><td className="p-3">{t.status}</td><td className="p-3">{t.assignedTo?.name ?? "Unassigned"}</td><td className="p-3"><span className="block">{new Date(t.updatedAt).toLocaleDateString()}</span><Link href={`/admin/support?ticket=${t.id}`} className="mt-1 inline-block text-xs font-semibold text-primary hover:underline">Open ticket</Link></td></tr>)}</tbody></table></div> : <EmptyState icon={<LifeBuoy/>} title="No matching support tickets" description="Change the search, filter, or sort controls to widen the queue."/>}<Readiness title="Resolution time and SLA tracking" body={data.readiness.sla}/></div>;
  else if (view === "health") content = <div className="space-y-4">{controls}<div className="grid gap-4 md:grid-cols-2">{tenants.length ? tenants.map((x) => <Card className="p-5" key={x.id}><div className="flex justify-between gap-3"><div><h2 className="font-semibold">{x.name}</h2><p className="mt-1 text-sm text-muted-foreground">{x.open} open support / {x.usage.requests} AI requests</p></div><strong className="text-3xl text-cyan-700">{x.health}</strong></div><p className="mt-4 text-sm text-muted-foreground">Score: 100 baseline; -10 per open ticket; -10 per high/urgent ticket; -12 with no linked subscription. Adoption, NPS, growth, and renewal likelihood are not inferred.</p></Card>) : <EmptyState icon={<Users/>} title="No customer health records" description="Institution records will appear when tenant data is available."/>}</div></div>;
  else if (view === "onboarding") content = <div className="space-y-4">{controls}<div className="grid gap-4 md:grid-cols-2">{tenants.length ? tenants.map((x) => <Card className="p-5" key={x.id}><div className="flex justify-between"><h2 className="font-semibold">{x.name}</h2><Badge>{x.onboarding}% evidence</Badge></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full bg-cyan-600" style={{ width: `${x.onboarding}%` }}/></div><p className="mt-3 text-sm text-muted-foreground">Contact, users, courses, and subscription linkage. Admin, teacher/student adoption, branding, domain, and go-live checks need dedicated source events.</p></Card>) : <EmptyState icon={<Users/>} title="No onboarding evidence" description="Institution records will appear when tenant data is available."/>}</div></div>;
  else if (view === "adoption") content = <div className="space-y-4">{controls}<div className="grid gap-4 md:grid-cols-2">{tenants.length ? tenants.map((x) => <Card className="p-5" key={x.id}><div className="flex justify-between"><h2 className="font-semibold">{x.name}</h2><Badge>{x._count.users} users</Badge></div><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><span className="text-muted-foreground">Courses</span><strong className="block">{x._count.courses}</strong></div><div><span className="text-muted-foreground">AI requests</span><strong className="block">{x.usage.requests}</strong></div><div><span className="text-muted-foreground">Token usage</span><strong className="block">{Number(x.usage.tokens).toLocaleString()}</strong></div><div><span className="text-muted-foreground">DAU / module use</span><strong className="block">Not instrumented</strong></div></div></Card>) : <EmptyState icon={<Users/>} title="No adoption records" description="Institution records will appear when tenant data is available."/>}</div><Readiness title="Feature adoption" body="Daily/monthly active users, marketplace adoption, communications reach, and analytics use need platform event telemetry."/></div>;
  else if (view === "communications") content = <div className="space-y-4">{controls}<div className="flex justify-end"><Link href="/admin/announcements" className="text-sm font-medium text-primary hover:underline">Open existing communication workflow</Link></div>{filteredCommunications.length ? <div className="grid gap-4 md:grid-cols-2">{filteredCommunications.map((x) => <Card className="p-5" key={x.id}><div className="flex justify-between"><Badge>{x.kind}</Badge><span className="text-xs text-muted-foreground">{new Date(x.updatedAt).toLocaleDateString()}</span></div><h2 className="mt-3 font-semibold">{x.title}</h2><p className="mt-2 text-sm text-muted-foreground">{x.recipients.length} recipients / {x.logs.length} delivery log(s)</p><Link href={`/admin/announcements?communication=${x.id}`} className="mt-3 inline-block text-sm font-medium text-primary hover:underline">Open communication workflow</Link></Card>)}</div> : <EmptyState icon={<BellRing/>} title="No matching communication records" description="Change the search, filter, or sort controls, or use the existing announcement workflow to publish updates."/>}</div>;
  else if (view === "knowledge") content = <div className="grid gap-4 lg:grid-cols-2"><Readiness title="Knowledge base" body={data.readiness.knowledge}/><Card className="p-5"><h2 className="font-semibold">Existing content handoff</h2><p className="mt-2 text-sm text-muted-foreground">Use the existing content and announcement workflows for published documentation while a dedicated knowledge taxonomy is introduced.</p><Link href="/admin/content-management" className="mt-4 inline-block text-sm font-medium text-primary hover:underline">Open content management</Link></Card></div>;
  else if (view === "ai") content = <div className="grid gap-4 lg:grid-cols-2"><Card className="p-5"><div className="flex items-center gap-2"><Sparkles className="h-5 w-5 text-cyan-600"/><h2 className="font-semibold">AI customer-success assist</h2></div><p className="mt-3 text-sm text-muted-foreground">AI usage is shown per institution; ticket summaries, reply suggestions, categorization, priority prediction, and churn inference are only enabled when supported by the existing AI conversation service.</p><Link href="/admin/ai-analytics" className="mt-4 inline-block text-sm font-medium text-primary hover:underline">Open existing AI analytics</Link></Card><Readiness title="AI suggestions and predictions" body={data.readiness.predictions}/></div>;
  else if (view === "reports") content = <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Open support" value={data.metrics.openTickets}/><Metric label="At-risk institutions" value={data.metrics.atRisk}/><Metric label="Onboarding attention" value={data.metrics.onboardingAttention}/><Metric label="Average health" value={`${data.metrics.averageHealth}%`}/></div><Card className="p-5"><h2 className="font-semibold">Customer success export</h2><p className="mt-2 text-sm text-muted-foreground">Export support, health, onboarding, and adoption evidence through the shared browser export control. Scheduled, PDF, and AI-authored reports require the existing reporting engine to expose those functions.</p><Button className="mt-4" onClick={() => exportRows("customer-success-report", { tenants: data.tenants, metrics: data.metrics }, format)}><Download className="mr-2 h-4 w-4"/>Export report</Button></Card></div>;
  else content = <div className="space-y-4"><Card className="p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="flex items-center gap-2"><Settings2 className="h-5 w-5 text-cyan-600"/><h2 className="font-semibold">Customer success preferences</h2></div><p className="mt-2 text-sm text-muted-foreground">Presentation preferences are stored in your existing shared admin preference record.</p></div><div className="flex gap-3"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={compact} onChange={(e) => setCompact(e.target.checked)}/> Compact</label><Select className="h-9 w-24" value={format} onChange={(e) => setFormat(e.target.value as "csv" | "json")}><option value="csv">CSV</option><option value="json">JSON</option></Select></div><Button disabled={saving} onClick={async () => { setSaving(true); try { const response = await fetch("/api/admin/customer-success-preferences", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ compact, exportFormat: format }) }); setSaveMessage(response.ok ? "Preferences saved." : "Could not save preferences."); } catch { setSaveMessage("Could not save preferences."); } finally { setSaving(false); } }}>{saving ? "Saving..." : "Save preferences"}</Button></div>{saveMessage ? <p role="status" className="mt-3 text-sm text-muted-foreground">{saveMessage}</p> : null}</Card><div className="grid gap-4 lg:grid-cols-2"><Readiness title="SLA, categories, and priorities" body="These are governed in the existing support workflow; no duplicate policy store was added."/><Readiness title="Escalation and communication preferences" body="Use existing support/notification services for operational rules. This screen stores dashboard presentation only."/></div></div>;
  return <main className={`${compact ? "space-y-4" : "space-y-6"} pb-10`}>{hero}{content}</main>;
}
