"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { Activity, AlertTriangle, Archive, Download, Flag, Search, ShieldCheck, Server, TriangleAlert } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import type { getAdminGovernanceData } from "@/services/admin-governance-service";

type Data = Awaited<ReturnType<typeof getAdminGovernanceData>>;
type View = "health"|"security"|"audit"|"flags"|"monitoring"|"errors"|"releases"|"backups"|"analytics"|"settings";
const views: [View,string][] = [["health","Health"],["security","Security"],["audit","Audit"],["flags","Feature flags"],["monitoring","Monitoring"],["errors","Errors"],["releases","Releases"],["backups","Backups"],["analytics","Analytics"],["settings","Governance settings"]];
const stamp=(date:Date|string)=>new Date(date).toLocaleString();
const redact=(value:unknown):unknown=>{if(Array.isArray(value))return value.map(redact);if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value as Record<string,unknown>).filter(([key])=>!["ipAddress","userAgent","metadata","error","email","body"].includes(key)).map(([key,item])=>[key,redact(item)]));return typeof value==="string"&&/^[=+\-@]/.test(value)?`'${value}`:value;};
const download=(name:string,data:unknown)=>{const link=document.createElement("a");link.href=URL.createObjectURL(new Blob([JSON.stringify(redact(data),null,2)],{type:"application/json"}));link.download=`adminx-governance-${name}.json`;link.click();URL.revokeObjectURL(link.href);};
function Metric({label,value,note}:{label:string;value:string|number;note?:string}){return <Card className="p-4"><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p>{note&&<p className="mt-1 text-xs text-muted-foreground">{note}</p>}</Card>}
function Readiness({title,body}:{title:string;body:string}){return <Card className="border-dashed p-5"><Badge>Read-only readiness</Badge><h2 className="mt-3 font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{body}</p><p className="mt-3 text-xs text-muted-foreground">There is no governed source to search, filter, edit, or export for this module.</p></Card>}
export function GovernanceCommandCenter({data}:{data:Data}) {
 const [view,setView]=useState<View>("health"),[q,setQ]=useState(""),[filter,setFilter]=useState("ALL"),[sort,setSort]=useState("newest"),[securityOnly,setSecurityOnly]=useState(false);
 const audit=useMemo(()=>data.audits.filter(x=>`${x.action} ${x.entity} ${x.message??""} ${x.actor?.name??""} ${x.institution?.name??""}`.toLowerCase().includes(q.toLowerCase())) .filter(x=>!securityOnly||/login|sign.?in|auth|permission|role|security|access/i.test(`${x.entity} ${x.message??""}`)).filter(x=>filter==="ALL"||x.action===filter).sort((a,b)=>sort==="oldest"?+new Date(a.createdAt)-+new Date(b.createdAt):+new Date(b.createdAt)-+new Date(a.createdAt)),[data.audits,q,filter,sort,securityOnly]);
 const flags=useMemo(()=>data.flags.filter(x=>`${x.name} ${x.key} ${x.scope} ${x.institution?.name??""}`.toLowerCase().includes(q.toLowerCase())).filter(x=>filter==="ALL"||(filter==="ENABLED"?x.enabled:!x.enabled)),[data.flags,q,filter]);
 const Header=()=> <><section className="relative overflow-hidden rounded-3xl border bg-slate-950 p-7 text-slate-50"><div className="absolute -right-20 -top-20 h-64 w-64 rounded-full bg-emerald-400/20 blur-3xl"/><div className="relative flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-emerald-300">AdminX / governance center</p><h1 className="mt-3 text-3xl font-semibold tracking-tight">Platform trust, in one operating view.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-300">Security, audit, automation and platform evidence from existing services. Operational telemetry is explicitly marked when no source is connected.</p></div><Button variant="secondary" onClick={()=>download("snapshot",data)}><Download className="mr-2 h-4 w-4"/>Export snapshot</Button></div></section><nav className="flex gap-2 overflow-x-auto py-1">{views.map(([id,label])=><button key={id} onClick={()=>{setView(id);setQ("");setFilter("ALL");setSecurityOnly(false)}} className={view===id?"shrink-0 rounded-full bg-primary px-4 py-2 text-sm font-medium text-primary-foreground":"shrink-0 rounded-full border px-4 py-2 text-sm font-medium hover:bg-muted"}>{label}</button>)}</nav></>;
 let body:React.ReactNode;
 if(view==="health") body=<div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Overall health (signal-based)" value={`${data.health.score}%`} note="100 - (8 x failed automation runs) - (6 x urgent unresolved tickets), minimum 0; not runtime availability"/><Metric label="Critical support signals" value={data.health.critical}/><Metric label="Failed automation runs" value={data.health.failedJobs}/><Metric label="Audit events, 7 days" value={data.health.auditEvents7d}/></div><div className="grid gap-4 lg:grid-cols-3"><Readiness title="API, database & storage" body={data.readiness.infrastructure}/><Card className="p-5"><h2 className="font-semibold">Automation status</h2><p className="mt-2 text-sm text-muted-foreground">{data.automations.length} configured rule(s), {data.executions.length} recorded run(s).</p><p className="mt-4 text-sm">Failed runs are counted in the health signal and listed in Error Center.</p></Card><Readiness title="Health timeline" body="A time-series uptime source has not been registered. Platform metrics below retain only events the platform already records."/></div></div>;
 else if(view==="security") body=<div className="space-y-4"><div className="grid gap-3 md:grid-cols-3"><Metric label="Failed-login audit signals" value={data.security.failedLogins}/><Metric label="Permission/security signals" value={data.security.permissionSignals}/><Metric label="Blocked accounts" value="Not modeled"/></div><Card className="p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Security evidence</h2><p className="mt-1 text-sm text-muted-foreground">Audit-derived login, role, permission, and access signals; not a threat-detection engine.</p></div><div className="flex gap-2"><Button variant="secondary" onClick={()=>download("security-evidence",data.audits.filter(x=>/login|sign.?in|auth|permission|role|security|access/i.test(`${x.entity} ${x.message??""}`)))}>Export</Button><Button variant="secondary" onClick={()=>{setView("audit");setQ("");setFilter("ALL");setSecurityOnly(true)}}>Audit drill-down</Button></div></div><div className="mt-4 space-y-2">{data.audits.filter(x=>/login|sign.?in|auth|permission|role|security|access/i.test(`${x.entity} ${x.message??""}`)).slice(0,6).map(x=><div className="rounded-lg border p-3 text-sm" key={x.id}><Badge>{x.action}</Badge><span className="ml-2">{x.entity} - {x.actor?.name??"System"}</span><span className="ml-2 text-muted-foreground">{stamp(x.createdAt)}</span></div>)}</div></Card></div>;
 else if(view==="audit") body=<div className="space-y-4"><div className="grid gap-3 md:grid-cols-[1fr_180px_160px_auto]"><Input value={q} onChange={e=>{setQ(e.target.value);setSecurityOnly(false)}} placeholder="Search actor, institution, entity, or message"/><Select value={filter} onChange={e=>setFilter(e.target.value)}><option value="ALL">All actions</option>{[...new Set(data.audits.map(x=>x.action))].map(x=><option key={x} value={x}>{x}</option>)}</Select><Select value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">Newest first</option><option value="oldest">Oldest first</option></Select><Button variant="secondary" onClick={()=>download("audit",audit)}>Export</Button></div>{securityOnly?<p className="text-xs text-muted-foreground">Showing the security-evidence drill-down. <button className="font-medium text-primary underline" onClick={()=>setSecurityOnly(false)}>Clear scope</button></p>:null}{audit.length?<div className="overflow-x-auto rounded-2xl border"><table className="w-full min-w-[800px] text-left text-sm"><thead className="bg-muted"><tr><th className="p-3">When</th><th className="p-3">Action</th><th className="p-3">Actor</th><th className="p-3">Institution</th><th className="p-3">Evidence</th></tr></thead><tbody>{audit.map(x=><tr key={x.id} className="border-t"><td className="p-3">{stamp(x.createdAt)}</td><td className="p-3"><Badge>{x.action}</Badge></td><td className="p-3">{x.actor?.name??"System"}</td><td className="p-3">{x.institution?.name??"Platform"}</td><td className="p-3 text-muted-foreground">{x.entity}{x.message?`: ${x.message}`:""}</td></tr>)}</tbody></table></div>:<EmptyState icon={<Search/>} title="No audit activity matches" description="Adjust the search or action filter."/>}</div>;
 else if(view==="flags") body=<div className="space-y-4"><div className="grid gap-3 md:grid-cols-[1fr_180px_auto]"><Input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search feature flags"/><Select value={filter} onChange={e=>setFilter(e.target.value)}><option value="ALL">All states</option><option value="ENABLED">Enabled</option><option value="DISABLED">Disabled</option></Select><Button variant="secondary" onClick={()=>download("feature-flags",flags)}>Export</Button></div>{flags.length?<div className="grid gap-3 md:grid-cols-2">{flags.map(x=><Card key={x.id} className="p-5"><div className="flex justify-between gap-4"><div><h2 className="font-semibold">{x.name}</h2><p className="mt-1 text-xs text-muted-foreground">{x.key} / {x.scope}</p></div><Badge>{x.enabled?"ENABLED":"DISABLED"}</Badge></div><p className="mt-3 text-sm text-muted-foreground">{x.description??"No description recorded."}</p><p className="mt-3 text-xs text-muted-foreground">Target: {x.institution?.name??"Platform"} - Updated {stamp(x.updatedAt)}</p><p className="mt-3 text-xs text-muted-foreground">Record-level editing is unavailable in this read-only evidence view.</p></Card>)}</div>:<EmptyState icon={<Flag/>} title="No feature flags found" description="Adjust search or state filters."/>}<Card className="border-dashed p-5"><Badge>Existing control</Badge><h2 className="mt-3 font-semibold">Feature flag handoff</h2><p className="mt-2 text-sm text-muted-foreground">Flags above are read-only evidence. No per-record feature-flag editor is registered on this platform surface. Existing system settings may expose supported controls; percentage rollouts and rollback history require deployment metadata.</p><Link className="mt-3 inline-block text-sm font-medium text-primary hover:underline" href="/admin/system-settings">Open feature settings</Link></Card></div>;
 else if(view==="errors") body=<div className="space-y-4"><div className="flex flex-wrap justify-end gap-3"><Input className="max-w-sm" value={q} onChange={e=>setQ(e.target.value)} placeholder="Filter rule or entity"/><Button variant="secondary" onClick={()=>download("failed-automation",data.executions.filter(x=>String(x.status).includes("FAIL")&&`${x.ruleId} ${x.entity??""}`.toLowerCase().includes(q.toLowerCase())))}>Export failures</Button></div>{data.executions.filter(x=>String(x.status).includes("FAIL")&&`${x.ruleId} ${x.entity??""}`.toLowerCase().includes(q.toLowerCase())).length?<div className="space-y-2">{data.executions.filter(x=>String(x.status).includes("FAIL")&&`${x.ruleId} ${x.entity??""}`.toLowerCase().includes(q.toLowerCase())).map(x=><Card key={x.id} className="border-l-4 border-destructive p-4"><strong>{x.ruleId}</strong><span className="ml-2 text-sm text-muted-foreground">{String(x.status)} - {stamp(x.createdAt)}</span><details className="mt-2 text-xs text-muted-foreground"><summary className="cursor-pointer font-medium">Safe record details</summary><p className="mt-1">Execution {x.id} - entity {x.entity??"Not recorded"} - completed {x.completedAt?stamp(x.completedAt):"Not recorded"}</p></details><Link className="mt-2 inline-block text-sm font-medium text-primary hover:underline" href="/admin/automation">Review resolution workflow</Link></Card>)}</div>:<EmptyState icon={<AlertTriangle/>} title="No failed automation runs recorded" description="This is limited to existing automation execution data; application and frontend crash telemetry needs an error-tracking source."/>}<Card className="border-dashed p-5"><Badge>Read-only handoff</Badge><h2 className="mt-3 font-semibold">Exception resolution</h2><p className="mt-2 text-sm text-muted-foreground">Failure details are limited to existing automation records. Review the automation workflow before retrying or changing a rule.</p><Link className="mt-3 inline-block text-sm font-medium text-primary hover:underline" href="/admin/automation">Open automation workflow</Link></Card></div>;
 else if(view==="monitoring") body=<div className="grid gap-4 lg:grid-cols-2"><Card className="p-5"><h2 className="font-semibold">Recorded automation</h2><p className="mt-2 text-sm text-muted-foreground">{data.automations.length} scheduled/workflow rules and {data.executions.length} execution events are available.</p></Card><Readiness title="System monitoring" body={data.readiness.infrastructure}/><Readiness title="Webhook and cron monitoring" body="No webhook delivery or cron-job event source is registered."/><Readiness title="Performance monitoring" body="No latency, throughput, or browser performance source is registered."/></div>;
 else if(view==="analytics") body=<div className="space-y-4"><div className="flex flex-wrap justify-end gap-3"><Input className="max-w-sm" value={q} onChange={e=>setQ(e.target.value)} placeholder="Filter recorded metrics"/><Button variant="secondary" onClick={()=>download("platform-metrics",data.metrics.filter(x=>`${x.key} ${x.label}`.toLowerCase().includes(q.toLowerCase())))}>Export metrics</Button></div>{data.metrics.filter(x=>`${x.key} ${x.label}`.toLowerCase().includes(q.toLowerCase())).length?<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.metrics.filter(x=>`${x.key} ${x.label}`.toLowerCase().includes(q.toLowerCase())).map(x=><Card key={x.id} className="p-4"><p className="text-xs uppercase tracking-wider text-muted-foreground">{x.key}</p><h2 className="mt-2 font-semibold">{x.label}</h2><p className="mt-2 text-2xl font-semibold">{String(x.value)}</p><p className="mt-1 text-xs text-muted-foreground">{stamp(x.recordedAt)}</p></Card>)}</div>:<EmptyState icon={<Activity/>} title="No platform metrics recorded" description="Connect existing instrumentation to record performance, traffic, storage, and AI-consumption measurements."/>}</div>;
 else if(view==="releases") body=<Readiness title="Release management" body={data.readiness.releases}/>;
 else if(view==="backups") body=<Readiness title="Backup & recovery" body={data.readiness.backups}/>;
 else body=<div className="grid gap-4 lg:grid-cols-2"><Readiness title="Security policies & audit retention" body="Policy and retention configuration need an approved platform-level configuration source; existing tenant settings are not repurposed."/><Readiness title="Feature-flag, threshold & alert rules" body="Use existing flag records for state visibility. Governance configuration must be backed by controlled platform settings before edits are enabled."/><Readiness title="Maintenance preferences" body="Maintenance scheduling depends on release-management metadata."/></div>;
 return <main className="space-y-6 pb-10"><Header/>{body}</main>;
}
