"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { Bell, Bot, Download, HeartPulse, Search, Settings2, ShieldCheck, Sparkles, TimerReset } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import type { getAdminPlatformBrainData } from "@/services/admin-platform-brain-service";

type Data = Awaited<ReturnType<typeof getAdminPlatformBrainData>>;
type View = "brief" | "command" | "timeline" | "notifications" | "governance" | "intelligence" | "health" | "quality" | "certification" | "settings";
const tabs: [View, string][] = [["brief", "AI director"], ["command", "Command"], ["timeline", "Timeline"], ["notifications", "Notifications"], ["governance", "Governance"], ["intelligence", "Business intelligence"], ["health", "Health"], ["quality", "Quality audit"], ["certification", "1.0 certification"], ["settings", "Preferences"]];
const safe = (value: unknown): unknown => Array.isArray(value) ? value.map(safe) : value && typeof value === "object" ? Object.fromEntries(Object.entries(value as Record<string, unknown>).filter(([key]) => !["body", "message", "metadata", "error"].includes(key)).map(([key, item]) => [key, safe(item)])) : typeof value === "string" && /^[=+\-@]/.test(value) ? `'${value}` : value;
function download(name: string, value: unknown, format: "csv" | "json") { const data = safe(value); const body = format === "csv" && Array.isArray(data) ? (() => { const rows = data as Record<string, unknown>[]; const keys = [...new Set(rows.flatMap((row) => Object.keys(row)))]; return [keys.join(","), ...rows.map((row) => keys.map((key) => JSON.stringify(String(row[key] ?? ""))).join(","))].join("\n"); })() : JSON.stringify(data, null, 2); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([body], { type: format === "csv" ? "text/csv" : "application/json" })); link.download = `adminx-platform-brain-${name}.${format}`; link.click(); URL.revokeObjectURL(link.href); }
function Metric({ label, value, note }: { label: string; value: string | number; note?: string }) { return <Card className="p-4"><p className="text-xs font-semibold uppercase tracking-[.13em] text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold tracking-tight">{value}</p>{note && <p className="mt-1 text-xs text-muted-foreground">{note}</p>}</Card>; }
function Ready({ title, body, href }: { title: string; body: string; href?: string }) { return <Card className="border-dashed p-5"><Badge>Read-only readiness</Badge><h2 className="mt-3 font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{body}</p>{href && <Link href={href} className="mt-3 inline-block text-sm font-medium text-primary hover:underline">Open existing workflow</Link>}</Card>; }
export function PlatformBrain({ data }: { data: Data }) {
  const [view, setView] = useState<View>("brief"), [q, setQ] = useState(""), [filter, setFilter] = useState("ALL"), [format, setFormat] = useState<"csv" | "json">((data.preference as { format?: "csv" | "json" }).format ?? "csv"), [compact, setCompact] = useState(Boolean((data.preference as { compact?: boolean }).compact)), [notice, setNotice] = useState("");
  const timeline = useMemo(() => data.timeline.filter((row) => `${row.source} ${row.title} ${row.detail}`.toLowerCase().includes(q.toLowerCase())).filter((row) => filter === "ALL" || row.source === filter), [data.timeline, q, filter]);
  const priorities = [
    ...data.tickets.filter((row) => row.priority === "URGENT" || row.priority === "HIGH").map((row) => ({ label: row.subject, detail: `${row.priority} support ticket`, href: "/admin/customer-success" })),
    ...data.executions.filter((row) => String(row.status).includes("FAIL")).map((row) => ({ label: row.rule.name, detail: "Failed automation", href: "/admin/automation" })),
  ].slice(0, 8);
  const header = <><section className="relative overflow-hidden rounded-[2rem] border bg-slate-950 p-7 text-slate-50"><div className="absolute -right-20 -top-24 h-72 w-72 rounded-full bg-emerald-400/20 blur-3xl" /><div className="relative flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-emerald-300">AdminX / platform brain</p><h1 className="mt-3 text-3xl font-semibold tracking-tight">The ecosystem, interpreted as evidence.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-300">A unified executive layer over existing support, AI, audit, notifications, automations, institutions, and governance services. No parallel intelligence engine is created here.</p></div><Button variant="secondary" onClick={() => download("brief", { summary: data.summary, priorities, timeline }, format)}><Download className="mr-2 h-4 w-4" />Export brief</Button></div></section><nav className="flex gap-2 overflow-x-auto py-1">{tabs.map(([id, label]) => <button key={id} onClick={() => { setView(id); setQ(""); setFilter("ALL"); }} className={view === id ? "shrink-0 rounded-full bg-primary px-4 py-2 text-sm font-medium text-primary-foreground" : "shrink-0 rounded-full border px-4 py-2 text-sm font-medium hover:bg-muted"}>{label}</button>)}</nav></>;
  let body: React.ReactNode;
  if (view === "brief") body = <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Platform health signal" value={`${data.summary.health}%`} note="Evidence score, not uptime" /><Metric label="Critical priorities" value={priorities.length} /><Metric label="Unread notifications" value={data.summary.unreadNotifications} /><Metric label="AI requests today" value={data.summary.aiRequests} /><Metric label="AI tokens today" value={data.summary.aiTokens.toLocaleString()} /><Metric label="Failed automations" value={data.summary.failedAutomations} /><Metric label="Enabled flags" value={data.summary.enabledFlags} /></div><div className="grid gap-4 lg:grid-cols-[1.3fr_1fr]"><Card className="p-5"><div className="flex items-center gap-2"><Sparkles className="h-5 w-5 text-emerald-600" /><h2 className="font-semibold">Executive morning brief</h2></div><p className="mt-2 text-sm text-muted-foreground">Today&apos;s attention is derived from open high-priority support and failed automation evidence.</p><div className="mt-4 space-y-2">{priorities.length ? priorities.map((item, i) => <Link className="block rounded-xl border-l-4 border-amber-500 bg-amber-50/60 p-3 text-sm" href={item.href} key={`${item.label}-${i}`}><strong>{item.label}</strong><span className="block text-muted-foreground">{item.detail}. Open the source workflow.</span></Link>) : <EmptyState icon={<HeartPulse />} title="No critical evidence recorded" description="No urgent/high support tickets or failed automation runs are in the loaded source set." />}</div></Card><Ready title="AI recommendation boundary" body={data.readiness.command} href="/admin/ai-platform" /></div></div>;
  else if (view === "command") body = <div className="space-y-4"><div className="grid gap-3 md:grid-cols-[1fr_auto]"><Input value={q} onChange={(event) => setQ(event.target.value)} placeholder="Search institutions, support, AI, audit, or automation evidence" /><Button variant="secondary" onClick={() => download("search-evidence", timeline, format)}>Export results</Button></div><div className="grid gap-4 lg:grid-cols-2"><Card className="p-5"><h2 className="font-semibold">Global command handoffs</h2><p className="mt-2 text-sm text-muted-foreground">Search is evidence-only. Commands do not mutate platform data.</p><div className="mt-4 grid gap-2 sm:grid-cols-2">{[["Institutions", "/admin/tenants"], ["Support", "/admin/customer-success"], ["AI operations", "/admin/ai-platform"], ["Governance", "/admin/governance"], ["Business", "/admin/business"], ["Ecosystem", "/admin/ecosystem"]].map(([label, href]) => <Link key={label} href={href} className="rounded-lg border p-3 text-sm font-medium hover:bg-muted">{label}</Link>)}</div></Card><Ready title="Institution switcher, pins, and favorites" body="Tenant context and workspace navigation remain in existing AdminX navigation. Pinned/favorite workspace persistence needs a governed preference model beyond this dashboard's display settings." /></div><Card className="p-5"><h2 className="font-semibold">Search results</h2><p className="mt-1 text-xs text-muted-foreground">Results are cross-source evidence; open a source workspace to act.</p>{timeline.length ? <div className="mt-3 space-y-2">{timeline.slice(0, 12).map((row) => <div className="rounded-lg border p-3 text-sm" key={row.id}><Badge>{row.source}</Badge><strong className="ml-2">{row.title}</strong><span className="ml-2 text-muted-foreground">{row.detail}</span></div>)}</div> : <EmptyState icon={<Search />} title="No command evidence matches" description="Search by institution, feature, support subject, audit action, or automation rule." />}</Card></div>;
  else if (view === "timeline") body = <div className="space-y-4"><div className="grid gap-3 md:grid-cols-[1fr_180px_auto]"><Input value={q} onChange={(event) => setQ(event.target.value)} placeholder="Search timeline" /><Select value={filter} onChange={(event) => setFilter(event.target.value)}><option value="ALL">All sources</option>{[...new Set(data.timeline.map((row) => row.source))].map((source) => <option key={source} value={source}>{source}</option>)}</Select><Button variant="secondary" onClick={() => download("timeline", timeline, format)}>Export timeline</Button></div>{timeline.length ? <div className="space-y-2">{timeline.map((row) => <Card className="p-4" key={row.id}><div className="flex flex-wrap items-center justify-between gap-2"><div><Badge>{row.source}</Badge><strong className="ml-2">{row.title}</strong><p className="mt-1 text-sm text-muted-foreground">{row.detail}</p></div><span className="text-xs text-muted-foreground">{new Date(row.at).toLocaleString()}</span></div></Card>)}</div> : <EmptyState icon={<TimerReset />} title="No timeline evidence matches" description="Adjust the source filter or search." />}</div>;
  else if (view === "notifications") body = <div className="space-y-4"><div className="flex flex-wrap justify-between gap-3"><Input className="max-w-md" value={q} onChange={(event) => setQ(event.target.value)} placeholder="Search notification title or status" /><Button variant="secondary" onClick={() => download("notifications", data.notifications.filter((row) => `${row.title} ${row.status}`.toLowerCase().includes(q.toLowerCase())).map((row) => ({ title: row.title, type: row.status, read: Boolean(row.readAt), createdAt: row.createdAt })), format)}>Export notifications</Button></div>{data.notifications.filter((row) => `${row.title} ${row.status}`.toLowerCase().includes(q.toLowerCase())).length ? <div className="space-y-2">{data.notifications.filter((row) => `${row.title} ${row.status}`.toLowerCase().includes(q.toLowerCase())).map((row) => <Card key={row.id} className="p-4"><Badge>{row.status}</Badge><strong className="ml-2">{row.title}</strong><span className="ml-2 text-xs text-muted-foreground">{row.readAt ? "Read" : "Unread"} / {new Date(row.createdAt).toLocaleString()}</span></Card>)}</div> : <EmptyState icon={<Bell />} title="No platform notifications match" description="Connected notification evidence will appear here." />}</div>;
  else if (view === "governance") body = <div className="grid gap-4 lg:grid-cols-2"><Ready title="Roles, permissions, tenant and platform policy" body={data.readiness.governance} href="/admin/governance" /><Card className="p-5"><h2 className="font-semibold">Feature visibility evidence</h2><p className="mt-2 text-sm text-muted-foreground">{data.summary.enabledFlags} enabled feature flags are recorded. Use the existing governance center for the safe, scoped source view.</p><Link href="/admin/governance" className="mt-4 inline-block text-sm font-medium text-primary hover:underline">Open governance center</Link></Card></div>;
  else if (view === "intelligence") body = <div className="grid gap-4 lg:grid-cols-2"><Card className="p-5"><h2 className="font-semibold">Current executive evidence</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><Metric label="Open support" value={data.tickets.length} /><Metric label="AI usage today" value={data.summary.aiRequests} /><Metric label="Automation failures" value={data.summary.failedAutomations} /><Metric label="Institutions" value={data.institutions.length} /></div><Button className="mt-4" onClick={() => download("executive-evidence", { summary: data.summary, tickets: data.tickets, usage: data.usage }, format)}><Download className="mr-2 h-4 w-4" />Export executive report</Button></Card><Ready title="Forecasts, opportunities, and AI reports" body={data.readiness.reports} href="/admin/ecosystem" /></div>;
  else if (view === "health") body = <div className="grid gap-4 lg:grid-cols-2"><Card className="p-5"><div className="flex items-center gap-2"><HeartPulse className="h-5 w-5 text-emerald-600" /><h2 className="font-semibold">Platform health summary</h2></div><p className="mt-3 text-4xl font-semibold">{data.summary.health}%</p><p className="mt-2 text-sm text-muted-foreground">100 - (8 x failed automation runs) - (4 x urgent/high open tickets), minimum 0.</p><div className="mt-4 grid grid-cols-2 gap-3"><Metric label="Failed runs" value={data.summary.failedAutomations} /><Metric label="Critical tickets" value={data.summary.criticalTickets} /></div></Card><Ready title="Infrastructure status" body={data.readiness.health} href="/admin/governance" /></div>;
  else if (view === "quality") body = <div className="grid gap-4 lg:grid-cols-2"><Card className="p-5"><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-emerald-600" /><h2 className="font-semibold">Cross-platform quality inventory</h2></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{["TeachX", "LearnX", "DirectorX", "AdminX", "Marketplace", "Authentication", "AI", "Notifications", "Reports", "Analytics", "Settings", "Search"].map((item) => <div className="rounded-lg border p-3 text-sm" key={item}>{item}<span className="block text-xs text-muted-foreground">Review through existing source workflows</span></div>)}</div></Card><Ready title="Production cleanup audit" body={data.readiness.quality} /></div>;
  else if (view === "certification") body = <div className="space-y-4"><Card className="p-5"><h2 className="font-semibold">Version 1.0 certification evidence</h2><p className="mt-2 text-sm text-muted-foreground">This is a navigation and evidence checklist, not a claim that unmeasured operational guarantees have been certified.</p><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{[["Authentication", "/admin/governance"], ["Authorization", "/admin/governance"], ["AI", "/admin/ai-platform"], ["Commerce", "/admin/business"], ["Reports", "/admin/ecosystem"], ["Analytics", "/admin/ecosystem"], ["Notifications", "/admin/customer-success"], ["Institutions", "/admin/tenants"], ["Platform health", "/admin/governance"]].map(([label, href]) => <Link href={href} key={label} className="rounded-lg border p-3 text-sm font-medium hover:bg-muted">{label}<span className="block text-xs font-normal text-muted-foreground">Open evidence</span></Link>)}</div></Card><Ready title="Production certification boundary" body="Accessibility, performance, security, and mobile responsiveness require their own verified test evidence. Run the repository validation suite before making a release claim." /></div>;
  else body = <div className="space-y-4"><Card className="p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="flex items-center gap-2"><Settings2 className="h-5 w-5 text-emerald-600" /><h2 className="font-semibold">Platform brain presentation</h2></div><p className="mt-2 text-sm text-muted-foreground">Only display density and export format are saved to your shared preferences.</p></div><div className="flex items-center gap-3"><label className="text-sm"><input className="mr-2" type="checkbox" checked={compact} onChange={(event) => setCompact(event.target.checked)} />Compact</label><Select className="w-24" value={format} onChange={(event) => setFormat(event.target.value as "csv" | "json")}><option value="csv">CSV</option><option value="json">JSON</option></Select><Button onClick={async () => { try { const response = await fetch("/api/admin/platform-brain-preferences", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ compact, format }) }); setNotice(response.ok ? "Preferences saved." : "Could not save preferences."); } catch { setNotice("Could not save preferences."); } }}>Save</Button></div></div>{notice && <p role="status" className="mt-3 text-sm text-muted-foreground">{notice}</p>}</Card><Ready title="Platform policies and alert configuration" body="Policy, alert, and maintenance controls remain in existing governed settings and governance workflows." href="/admin/governance" /></div>;
  return <main className={compact ? "space-y-4 pb-10" : "space-y-6 pb-10"}>{header}{body}</main>;
}
