import { prisma } from "@/lib/db";
export async function getDirectorAcademicIntelligence({ institutionId }: { institutionId?: string | null }) {
 const nil={academicScore:null,passRate:null,attendance:null,completion:null,students:0,teachers:0,departments:0,classes:0,results:0};
 if(!institutionId)return {institution:"No authorized institution",summary:nil,departments:[],actions:[],subjects:[],courses:[],classes:[],teachers:[],students:[],assessments:{total:0,internal:0,mocks:0,passRate:null,assignmentCompletion:null},risks:[],evidence:{savedAttendanceRecords:0,learningProgressRecords:0,examResults:0,assignmentSubmissions:0,aiEvents:0}};
 const [institution,departments,courses,batches,teachers,students,results,progress,sessions,assignments,content,usage]=await Promise.all([
 prisma.institution.findUnique({where:{id:institutionId},select:{name:true}}), prisma.department.findMany({where:{institutionId},select:{id:true,name:true,courses:{select:{id:true}},subjects:{select:{id:true}}}}), prisma.course.findMany({where:{institutionId},select:{id:true,name:true,academicYear:{select:{name:true}}}}), prisma.batch.findMany({where:{course:{institutionId}},select:{id:true,name:true,courseId:true,faculty:{select:{facultyId:true}},students:{select:{studentId:true}}}}), prisma.user.findMany({where:{institutionId,roles:{some:{role:{key:{in:["ACADEMIC_FACULTY","PART_TIME_TUTOR"]}}}}},select:{id:true,name:true,email:true}}), prisma.user.findMany({where:{institutionId,roles:{some:{role:{key:"STUDENT"}}}},select:{id:true,name:true,email:true}}), prisma.examResult.findMany({where:{exam:{institutionId}},select:{studentId:true,percentage:true,passed:true,exam:{select:{name:true,type:true,courseId:true,batchId:true,createdById:true,subject:{select:{name:true}}}}}}), prisma.learningProgress.findMany({where:{course:{institutionId}},select:{studentId:true,completion:true}}), prisma.attendanceSession.findMany({where:{classroom:{institutionId},savedAt:{not:null}},select:{records:{select:{studentId:true,status:true}}}}), prisma.assignment.findMany({where:{classroom:{institutionId}},select:{createdById:true,submissions:{select:{status:true}}}}), prisma.contentItem.findMany({where:{institutionId},select:{createdById:true}}), prisma.aIUsage.findMany({where:{institutionId},select:{userId:true}})]);
 const avg=(v:number[])=>v.length?Math.round(v.reduce((a,b)=>a+b,0)/v.length*10)/10:null, records=sessions.flatMap(s=>s.records), vals=results.map(r=>Number(r.percentage)); const attendance=records.length?Math.round(records.filter(r=>r.status==="PRESENT"||r.status==="LATE").length/records.length*1000)/10:null, passRate=results.length?Math.round(results.filter(r=>r.passed).length/results.length*1000)/10:null;
 const departmentRows=departments.map(d=>{const ids=new Set(d.courses.map(c=>c.id)),rr=results.filter(r=>ids.has(r.exam.courseId)),bb=batches.filter(b=>ids.has(b.courseId));return{id:d.id,name:d.name,faculty:new Set(bb.flatMap(b=>b.faculty.map(f=>f.facultyId))).size,students:new Set(bb.flatMap(b=>b.students.map(s=>s.studentId))).size,score:avg(rr.map(r=>Number(r.percentage))),subjects:d.subjects.length,evidence:rr.length}}); const sm=new Map<string,number[]>();results.forEach(r=>{const k=r.exam.subject?.name??"Unassigned subject";sm.set(k,[...(sm.get(k)??[]),Number(r.percentage)])});
 const teacherRows=teachers.map(t=>{const rr=results.filter(r=>r.exam.createdById===t.id),resources=content.filter(c=>c.createdById===t.id).length,activities=assignments.filter(a=>a.createdById===t.id).length,ai=usage.filter(a=>a.userId===t.id).length,outcome=avg(rr.map(r=>Number(r.percentage)));return{id:t.id,name:t.name,email:t.email,score:outcome===null?null:Math.min(100,Math.round((outcome*.7+Math.min(resources,10)*2+Math.min(activities,10))*10)/10),outcome,activities,ai,resources,evidence:rr.length}});
 const studentRows=students.map(s=>{const rr=results.filter(r=>r.studentId===s.id),pp=progress.filter(p=>p.studentId===s.id),aa=records.filter(a=>a.studentId===s.id),score=avg(rr.map(r=>Number(r.percentage))),att=aa.length?Math.round(aa.filter(a=>a.status==="PRESENT"||a.status==="LATE").length/aa.length*1000)/10:null,completion=avg(pp.map(p=>p.completion)),risk=(score!==null&&score<50?45:0)+(att!==null&&att<75?35:0)+(completion!==null&&completion<50?20:0);return{id:s.id,name:s.name,email:s.email,score,attendance:att,completion,risk,resultEvidence:rr.length,attendanceEvidence:aa.length}}),subs=assignments.flatMap(a=>a.submissions);
 const classRows = batches.map(batch => ({
   id: batch.id,
   name: batch.name,
   students: batch.students.length,
   teachers: batch.faculty.length,
   score: avg(results.filter(result => result.exam.batchId === batch.id).map(result => Number(result.percentage))),
 }));
 const actions = [
   ...studentRows.flatMap(student => [
     ...(student.attendance !== null && student.attendance < 75 ? [{ id: `attendance-${student.id}`, domain: "ATTENDANCE", subject: student.name, severity: student.attendance < 60 ? "CRITICAL" : "HIGH", owner: "Student services lead", dueHorizon: "7 days", evidence: `Saved attendance ${student.attendance}% across ${student.attendanceEvidence} records`, action: "Contact the family, agree a daily attendance recovery plan, and review after seven days.", report: "actions" }] : []),
     ...(student.score !== null && student.score < 50 ? [{ id: `grade-${student.id}`, domain: "GRADE", subject: student.name, severity: student.score < 35 ? "CRITICAL" : "HIGH", owner: "Subject lead", dueHorizon: "Before next assessment", evidence: `Measured grade ${student.score}% across ${student.resultEvidence} results`, action: "Assign targeted remediation by weak subject and schedule a short reassessment.", report: "actions" }] : []),
     ...(student.completion !== null && student.completion < 50 ? [{ id: `completion-${student.id}`, domain: "COMPLETION", subject: student.name, severity: student.completion < 25 ? "HIGH" : "WATCH", owner: "Class mentor", dueHorizon: "14 days", evidence: `Learning completion ${student.completion}%`, action: "Reset the learning plan into weekly milestones and review completion with the learner.", report: "actions" }] : []),
   ]),
   ...classRows.filter(item => item.score !== null && item.score < 55).map(item => ({ id: `class-${item.id}`, domain: "CLASS_OUTCOME", subject: item.name, severity: item.score! < 40 ? "CRITICAL" : "HIGH", owner: "Academic head", dueHorizon: "10 days", evidence: `Class result average ${item.score}% for ${item.students} students`, action: "Run a class-level item analysis, assign subject remediation, and review the next common assessment.", report: "actions" })),
   ...teacherRows.filter(item => item.activities > 8 || item.resources === 0).map(item => ({ id: `faculty-${item.id}`, domain: "FACULTY_WORKLOAD", subject: item.name, severity: item.activities > 12 ? "HIGH" : "WATCH", owner: "Department head", dueHorizon: "Next workload review", evidence: `${item.activities} assignment activities and ${item.resources} resource contributions`, action: item.activities > 8 ? "Review teaching load and redistribute assessment activity where coverage permits." : "Schedule resource-development support and agree one publishable contribution.", report: "actions" })),
 ]; return {institution:institution?.name??"Authorized institution",summary:{academicScore:avg(vals),passRate,attendance,completion:avg(progress.map(p=>p.completion)),students:students.length,teachers:teachers.length,departments:departments.length,classes:batches.length,results:results.length},departments:departmentRows,subjects:[...sm].map(([name,v])=>({name,score:avg(v),evidence:v.length})),courses:courses.map(c=>({id:c.id,name:c.name,year:c.academicYear?.name??"Year not assigned",score:avg(results.filter(r=>r.exam.courseId===c.id).map(r=>Number(r.percentage))),evidence:results.filter(r=>r.exam.courseId===c.id).length})),classes:classRows,actions,teachers:teacherRows,students:studentRows,assessments:{total:new Set(results.map(r=>r.exam.name)).size,internal:new Set(results.filter(r=>String(r.exam.type)!=="MOCK").map(r=>r.exam.name)).size,mocks:new Set(results.filter(r=>String(r.exam.type)==="MOCK").map(r=>r.exam.name)).size,passRate,assignmentCompletion:subs.length?Math.round(subs.filter(s=>s.status!=="PENDING").length/subs.length*1000)/10:null},risks:studentRows.filter(s=>s.risk>0).sort((a,b)=>b.risk-a.risk),evidence:{savedAttendanceRecords:records.length,learningProgressRecords:progress.length,examResults:results.length,assignmentSubmissions:subs.length,aiEvents:usage.length}};
}
