import { prisma } from "@/lib/db";

export async function getDirectorHrIntelligence({ institutionId }: { institutionId?: string | null }) {
  const empty = { institution: "No authorized institution", people: [], leaves: [], balances: [], holidays: [], allocation: [], summary: { workforce: 0, faculty: 0, nonTeaching: 0, active: 0, onLeave: 0, pendingLeave: 0, scheduledEntries: 0, profileCoverage: 0 }, departments: [], actions: [], settings: { scheduledEntryAlert: 5, compact: false, format: "csv" } };
  if (!institutionId) return empty;
  const [institution, users, leaves, holidays, entries, setting] = await Promise.all([
    prisma.institution.findUnique({ where: { id: institutionId }, select: { name: true } }),
    prisma.user.findMany({ where: { institutionId }, select: { id: true, name: true, status: true, roles: { select: { role: { select: { key: true, name: true } } } }, profile: { select: { title: true } }, staffProfile: { select: { id: true, department: true, designation: true, employmentStatus: true, joiningDate: true, leaveBalances: { select: { leaveType: true, balance: true, used: true } } } }, teacherProfile: { select: { certificates: true } } }, orderBy: { name: "asc" }, take: 500 }),
    prisma.leaveApplication.findMany({ where: { applicant: { institutionId } }, select: { id: true, applicantId: true, fromDate: true, toDate: true, status: true, createdAt: true, applicant: { select: { name: true } }, approver: { select: { name: true } } }, orderBy: { createdAt: "desc" }, take: 300 }),
    prisma.plannerEvent.findMany({ where: { institutionId, type: { in: ["HOLIDAY", "SPECIAL_HOLIDAY"] } }, select: { id: true, title: true, type: true, startsAt: true, endsAt: true }, orderBy: { startsAt: "asc" }, take: 100 }),
    prisma.timetableEntry.findMany({ where: { course: { institutionId } }, select: { id: true, day: true, facultyId: true, faculty: { select: { name: true, staffProfile: { select: { department: true } } } }, course: { select: { name: true } }, batch: { select: { name: true } }, subject: { select: { name: true } } }, take: 1000 }),
    prisma.setting.findUnique({ where: { institutionId_key: { institutionId, key: "directorx.hr.thresholds" } }, select: { value: true } }),
  ]);
  const facultyKeys = new Set(["teacher", "faculty", "instructor"]);
  const people = users.map(u => { const roles=u.roles.map(r=>r.role.key); const faculty=roles.some(r=>facultyKeys.has(r.toLowerCase())) || entries.some(e=>e.facultyId===u.id); return { id:u.id,name:u.name,role:u.roles.map(r=>r.role.name).join(", ")||"Unassigned",faculty,department:u.staffProfile?.department??"Unassigned",designation:u.staffProfile?.designation??u.profile?.title??"Not recorded",employmentStatus:u.staffProfile?.employmentStatus??"PROFILE MISSING",joiningDate:u.staffProfile?.joiningDate?.toISOString()??null,certificates:u.teacherProfile?.certificates.length??0,profileId:u.staffProfile?.id??null,status:u.status }; });
  const allocationMap=new Map<string,{id:string;name:string;department:string;entries:number;courses:Set<string>;batches:Set<string>}>(); entries.forEach(e=>{if(!e.facultyId)return;const r=allocationMap.get(e.facultyId)??{id:e.facultyId,name:e.faculty?.name??"Unassigned",department:e.faculty?.staffProfile?.department??"Unassigned",entries:0,courses:new Set(),batches:new Set()};r.entries++;r.courses.add(e.course.name);r.batches.add(e.batch.name);allocationMap.set(e.facultyId,r)}); const allocation=[...allocationMap.values()].map(r=>({...r,courses:r.courses.size,batches:r.batches.size})).sort((a,b)=>b.entries-a.entries);
  const balances=users.flatMap(u=>u.staffProfile?.leaveBalances.map(b=>({staffId:u.id,name:u.name,leaveType:b.leaveType,balance:Number(b.balance),used:Number(b.used)}))??[]);
  const departmentNames=[...new Set(people.map(p=>p.department))]; const departments=departmentNames.map(name=>({name,total:people.filter(p=>p.department===name).length,faculty:people.filter(p=>p.department===name&&p.faculty).length,scheduledEntries:allocation.filter(a=>a.department===name).reduce((n,a)=>n+a.entries,0)})).sort((a,b)=>b.total-a.total);
  const summary={workforce:people.length,faculty:people.filter(p=>p.faculty).length,nonTeaching:people.filter(p=>!p.faculty).length,active:people.filter(p=>p.employmentStatus==="ACTIVE").length,onLeave:people.filter(p=>p.employmentStatus==="ON_LEAVE").length,pendingLeave:leaves.filter(l=>l.status==="PENDING").length,scheduledEntries:entries.length,profileCoverage:people.length?Math.round(people.filter(p=>p.profileId).length/people.length*100):0};
  const saved=setting?.value && typeof setting.value === "object" && !Array.isArray(setting.value) ? setting.value as { scheduledEntryAlert?: unknown; compact?: unknown; format?: unknown } : {};
  const settings={scheduledEntryAlert:typeof saved.scheduledEntryAlert==="number"?Math.min(20,Math.max(2,saved.scheduledEntryAlert)):5,compact:typeof saved.compact==="boolean"?saved.compact:false,format:saved.format==="json"?"json":"csv"};
  const actions=[...(summary.profileCoverage<90?[{severity:"WATCH",signal:"Profile coverage",evidence:`${summary.profileCoverage}% of institution users have StaffProfile records`,action:"Attach staff profiles to existing institution identities; do not create duplicate users.",owner:"People operations",due:"This month"}]:[]),...(summary.pendingLeave?[{severity:summary.pendingLeave>5?"HIGH":"WATCH",signal:"Leave decisions",evidence:`${summary.pendingLeave} leave requests await a decision`,action:"Review oldest pending requests against scheduled teaching allocation.",owner:"Leave approver",due:"48 hours"}]:[]),...(allocation[0]?[{severity:"OPPORTUNITY",signal:"Scheduled allocation",evidence:`${allocation[0].name} has ${allocation[0].entries} recurring timetable entries`,action:"Validate distribution; entry counts are allocations, not working hours or capacity.",owner:"Academic operations",due:"Next timetable review"}]:[])];
  return {institution:institution?.name??"Authorized institution",people,leaves:leaves.map(l=>({...l,fromDate:l.fromDate.toISOString(),toDate:l.toDate.toISOString(),createdAt:l.createdAt.toISOString()})),balances,holidays:holidays.map(h=>({...h,startsAt:h.startsAt.toISOString(),endsAt:h.endsAt.toISOString()})),allocation,summary,departments,actions,settings};
}
