import { prisma } from "@/lib/db";

const confirmedStages = new Set(["ADMISSION_APPROVED", "FEE_PENDING", "ENROLLED", "STUDENT_CREATED"]);
const applicationStages = new Set(["APPLICATION_SUBMITTED", "DOCUMENT_VERIFICATION", ...confirmedStages]);

export async function getDirectorAdmissionsIntelligence({ institutionId }: { institutionId?: string | null }) {
  const empty = { institution: "No authorized institution", generatedAt: new Date().toISOString(), summary: { enquiries: 0, activeLeads: 0, applications: 0, confirmed: 0, conversion: 0 }, stages: [], counsellors: [], programs: [], campaigns: [], sources: [], followUps: { pending: 0, missed: 0 }, forecast: { predicted: 0, monthlyRunRate: 0, sampleMonths: 0, coverage: 0, method: "Insufficient evidence", monthly: [] }, actions: [], notifications: [], pendingApplications: [], approvals: [], followUpQueue: [], departments: [], partnerships: { referrals: 0, attributedAdmissions: 0, commissions: 0, commissionAmount: 0 } };
  if (!institutionId) return empty;
  const [institution, leads, applications, admissions, courses, campaigns, notifications, referrals, commissions] = await Promise.all([
    prisma.institution.findUnique({ where: { id: institutionId }, select: { name: true } }),
    prisma.lead.findMany({ where: { institutionId }, select: { id: true, name: true, stage: true, priority: true, createdAt: true, assignedExecutive: { select: { id: true, name: true } }, interestedCourseId: true, source: { select: { name: true } }, campaignId: true, followUps: { select: { status: true, scheduledAt: true } }, activities: { select: { title: true, createdAt: true }, orderBy: { createdAt: "desc" }, take: 1 } } }),
    prisma.application.findMany({ where: { institutionId }, select: { id: true, status: true, courseId: true, createdAt: true } }),
    prisma.admission.findMany({ where: { institutionId }, select: { id: true, status: true, courseId: true, createdAt: true } }),
    prisma.course.findMany({ where: { institutionId }, select: { id: true, name: true, department: { select: { name: true } }, batches: { select: { capacity: true, maximumStrength: true, students: { select: { id: true } } } } } }),
    prisma.campaign.findMany({ where: { institutionId }, select: { id: true, name: true, source: { select: { name: true } } } }),
    prisma.notification.findMany({ where: { institutionId }, select: { id: true, title: true, body: true, status: true, createdAt: true }, orderBy: { createdAt: "desc" }, take: 12 }),
    prisma.partnerReferral.findMany({ where: { partner: { institutionId } }, select: { leadId: true } }),
    prisma.partnerCommission.findMany({ where: { partner: { institutionId } }, select: { amount: true, status: true } }),
  ]);
  const now = new Date();
  const confirmed = admissions.filter(a => a.status === "APPROVED" || a.status === "ENROLLED");
  const activeLeads = leads.filter(l => !["ENROLLED", "STUDENT_CREATED"].includes(l.stage)).length;
  const stages = ["NEW_LEAD", "CONTACTED", "INTERESTED", "DEMO_SCHEDULED", "DEMO_ATTENDED", "APPLICATION_SUBMITTED", "DOCUMENT_VERIFICATION", "ADMISSION_APPROVED", "FEE_PENDING", "ENROLLED", "STUDENT_CREATED"].map(stage => ({ stage, count: leads.filter(l => l.stage === stage).length }));
  const people = new Map<string, { id: string; name: string; assigned: number; contacted: number; admissions: number; followUps: number; missed: number; recent: string }>();
  leads.forEach(l => { if (!l.assignedExecutive) return; const p = people.get(l.assignedExecutive.id) ?? { id: l.assignedExecutive.id, name: l.assignedExecutive.name, assigned: 0, contacted: 0, admissions: 0, followUps: 0, missed: 0, recent: "No recorded activity" }; p.assigned++; if (l.stage !== "NEW_LEAD") p.contacted++; if (confirmedStages.has(l.stage)) p.admissions++; p.followUps += l.followUps.filter(f => f.status === "COMPLETED").length; p.missed += l.followUps.filter(f => f.status === "MISSED" || (f.status === "PENDING" && f.scheduledAt < now)).length; p.recent = l.activities[0]?.title ?? p.recent; people.set(p.id, p); });
  const counsellors = [...people.values()].map(p => ({ ...p, conversion: p.assigned ? Math.round(p.admissions / p.assigned * 1000) / 10 : 0 })).sort((a,b) => b.conversion-a.conversion);
  const programs = courses.map(c => { const demand = leads.filter(l => l.interestedCourseId === c.id).length, admitted = confirmed.filter(a => a.courseId === c.id).length, capacity = c.batches.reduce((n,b)=>n+(b.maximumStrength || b.capacity),0), enrolled = c.batches.reduce((n,b)=>n+b.students.length,0); return { id:c.id,name:c.name,department:c.department?.name??"Unassigned",demand,admitted,capacity,enrolled,utilization:capacity?Math.round(enrolled/capacity*1000)/10:null }; }).sort((a,b)=>b.demand-a.demand);
  const campaignsRows = campaigns.map(c => { const ls=leads.filter(l=>l.campaignId===c.id), won=ls.filter(l=>confirmedStages.has(l.stage)).length; return { id:c.id,name:c.name,source:c.source?.name??"Unclassified",leads:ls.length,admissions:won,conversion:ls.length?Math.round(won/ls.length*1000)/10:0 }; }).sort((a,b)=>b.leads-a.leads);
  const sourceNames=[...new Set(leads.map(l=>l.source?.name??"Unattributed"))]; const sources=sourceNames.map(name=>{const ls=leads.filter(l=>(l.source?.name??"Unattributed")===name); return {name,leads:ls.length,admissions:ls.filter(l=>confirmedStages.has(l.stage)).length};}).sort((a,b)=>b.leads-a.leads);
  const admissionDates=confirmed.map(a=>a.createdAt), oldest=admissionDates.reduce<Date|null>((d,v)=>!d||v<d?v:d,null), months=oldest?Math.max(1,Math.ceil((now.getTime()-oldest.getTime())/2629800000)):0, runRate=months?confirmed.length/months:0, predicted=Math.round(runRate*3), monthly=[...Array(Math.min(12,months))].map((_,i)=>{const d=new Date(now.getFullYear(),now.getMonth()-i,1), next=new Date(d.getFullYear(),d.getMonth()+1,1);return {month:d.toLocaleString("en",{month:"short",year:"2-digit"}),admissions:confirmed.filter(a=>a.createdAt>=d&&a.createdAt<next).length}}).reverse(), missed=leads.flatMap(l=>l.followUps).filter(f=>f.status==="MISSED"||(f.status==="PENDING"&&f.scheduledAt<now)).length, pending=applications.filter(a=>["SUBMITTED","UNDER_REVIEW"].includes(a.status)).length;
  const actions=[...(missed?[{id:"follow-up",severity:missed>10?"HIGH":"WATCH",signal:"Follow-up leakage",evidence:`${missed} missed or overdue follow-ups`,action:"Clear the oldest follow-ups and rebalance counsellor queues.",owner:"Admissions lead",due:"48 hours",report:"actions"}]:[]),...(pending?[{id:"applications",severity:pending>10?"HIGH":"WATCH",signal:"Application queue",evidence:`${pending} submitted or under-review applications`,action:"Run a document and approval ageing review.",owner:"Admissions committee",due:"3 days",report:"actions"}]:[]),...(campaignsRows[0]?[{id:"campaign",severity:"OPPORTUNITY",signal:"Campaign quality",evidence:`${campaignsRows[0].name}: ${campaignsRows[0].leads} leads, ${campaignsRows[0].conversion}% conversion`,action:"Protect the best-performing source mix and test one controlled variant.",owner:"Growth lead",due:"Next planning cycle",report:"actions"}]:[]),...(counsellors.find(c=>c.missed>5)?[{id:"load",severity:"HIGH",signal:"Counsellor load",evidence:`${counsellors.find(c=>c.missed>5)!.name} has ${counsellors.find(c=>c.missed>5)!.missed} overdue follow-ups`,action:"Redistribute pending follow-ups and review workload.",owner:"Admissions lead",due:"Today",report:"actions"}]:[])];
  const pendingApplications=applications.filter(a=>["SUBMITTED","UNDER_REVIEW"].includes(a.status)).map(a=>({id:a.id,status:a.status,course:programs.find(p=>p.id===a.courseId)?.name??"Course unassigned",ageDays:Math.floor((now.getTime()-a.createdAt.getTime())/86400000)})); const approvals=admissions.filter(a=>a.status==="PENDING").map(a=>({id:a.id,status:a.status,course:programs.find(p=>p.id===a.courseId)?.name??"Course unassigned",ageDays:Math.floor((now.getTime()-a.createdAt.getTime())/86400000)})); const followUpQueue=leads.flatMap(l=>l.followUps.filter(f=>f.status==="PENDING"||f.status==="MISSED").map(f=>({id:`${l.id}-${f.scheduledAt.toISOString()}`,status:f.status==="PENDING"&&f.scheduledAt<now?"OVERDUE":f.status,scheduledAt:f.scheduledAt.toISOString(),priority:l.priority,stage:l.stage,owner:l.assignedExecutive?.name??"Unassigned"}))).sort((a,b)=>a.scheduledAt.localeCompare(b.scheduledAt)).slice(0,100); const departmentNames=[...new Set(programs.map(p=>p.department))]; const departments=departmentNames.map(name=>{const rows=programs.filter(p=>p.department===name);const capacity=rows.reduce((n,p)=>n+p.capacity,0),enrolled=rows.reduce((n,p)=>n+p.enrolled,0);return {name,programs:rows.length,demand:rows.reduce((n,p)=>n+p.demand,0),admitted:rows.reduce((n,p)=>n+p.admitted,0),capacity,enrolled,utilization:capacity?Math.round(enrolled/capacity*1000)/10:null}}); const referred=new Set(referrals.map(r=>r.leadId).filter(Boolean)); return { institution: institution?.name??"Authorized institution", generatedAt: now.toISOString(), summary:{enquiries:leads.length,activeLeads,applications:applications.length,confirmed:confirmed.length,conversion:leads.length?Math.round(confirmed.length/leads.length*1000)/10:0}, stages,counsellors,programs,departments,campaigns:campaignsRows,sources,pendingApplications,approvals,followUpQueue,followUps:{pending:followUpQueue.filter(f=>f.status==="PENDING").length,missed:followUpQueue.filter(f=>f.status==="MISSED"||f.status==="OVERDUE").length},forecast:{predicted,monthlyRunRate:Math.round(runRate*10)/10,sampleMonths:months,coverage:confirmed.length,method:"Run rate from confirmed admissions over their observed calendar months",monthly},partnerships:{referrals:referrals.length,attributedAdmissions:leads.filter(l=>referred.has(l.id)&&confirmedStages.has(l.stage)).length,commissions:commissions.length,commissionAmount:Number(commissions.reduce((n,c)=>n+Number(c.amount),0).toFixed(2))},actions,notifications };
}
