import { prisma } from "@/lib/db";

const banned = [/(?:https?:\/\/|www\.)/i,/\b(?:phone|whatsapp|telegram|instagram|snapchat|email me)\b/i,/\b(?:answer key|leak(?:ed)? paper|cheat(?:ing)?)\b/i,/\b(?:buy|sell|payment|upi|crypto)\b/i];
const metadata = (value: unknown) => value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {};
export type StudentCommunityActor = Awaited<ReturnType<typeof requireStudentCommunityActor>>;

export async function requireStudentCommunityActor(userId?: string, institutionId?: string | null) {
  if (!userId || !institutionId) throw new Error("Student community access required.");
  const user = await prisma.user.findFirst({ where: { id: userId, institutionId, status: "ACTIVE", roles: { some: { role: { key: "STUDENT" } } } }, select: { id: true, institutionId: true, name: true, institution:{select:{timezone:true}}, profile: { select: { avatarUrl: true } }, studentBatches: { select: { batch: { select: { id: true, courseId: true, course: { select: { subjects: { select: { id: true, name: true } } } } } } } } } });
  if (!user || !user.institutionId || !user.studentBatches.length) throw new Error("Active enrollment is required for the student community.");
  const subjects = [...new Map(user.studentBatches.flatMap(x => x.batch.course.subjects).map(x => [x.id, x])).values()];
  return { id: user.id, institutionId: user.institutionId, timezone:user.institution?.timezone??"Asia/Kolkata", alias: boundedAlias(user.name), avatar: approvedAvatar(user.profile?.avatarUrl??null), subjects, subjectIds: new Set(subjects.map(x => x.id)), courseIds: new Set(user.studentBatches.map(x => x.batch.courseId)), batchIds: new Set(user.studentBatches.map(x => x.batch.id)) };
}

export function boundedAlias(name: string) { const first = name.trim().split(/\s+/)[0] || "Student"; return `${first.slice(0, 24)} · learner`; }
export function approvedAvatar(value: string | null) { return value && /^https:\/\//.test(value) && value.length <= 500 ? value : null; }
export function safeMetadata(value: unknown) { const m = metadata(value); return { subjectId: typeof m.subjectId === "string" ? m.subjectId : null, academicCategory: typeof m.academicCategory === "string" ? m.academicCategory.slice(0, 40) : null, question: m.question === true }; }
export function moderateAcademicText(value: string, max = 2000) { const text = value.trim().replace(/\s+/g, " ").slice(0, max); if (text.length < 2) throw new Error("Academic content is required."); if (banned.some(rule => rule.test(text))) throw new Error("This community supports academic collaboration only. Links, contact sharing, solicitation, answer-key leaks, and cheating requests are not allowed."); return text; }
export function requireEnrolledSubject(actor: StudentCommunityActor, subjectId: string) { if (!actor.subjectIds.has(subjectId)) throw new Error("Choose a subject from your active enrollment."); return subjectId; }
export async function requireGroupAccess(actor: StudentCommunityActor, communityId: string, write = false) { const group = await prisma.community.findFirst({ where: { id: communityId, institutionId: actor.institutionId, type: "STUDY_GROUP", status: write ? "ACTIVE" : { in: ["ACTIVE", "LOCKED"] } }, select: { id: true, name: true, visibility: true, status: true, createdById: true, metadata: true, members: { where: { userId: actor.id }, select: { role: true } } } }); if (!group) throw new Error("Study group unavailable."); const m=safeMetadata(group.metadata); if(!m.subjectId || !actor.subjectIds.has(m.subjectId)) throw new Error("This group is outside your enrolled academic scope."); if (!group.members.length && group.visibility !== "PUBLIC") throw new Error("Active group membership is required."); if (write && !group.members.length) throw new Error("Join the group before contributing."); return { ...group, subjectId:m.subjectId, role:group.members[0]?.role??null }; }
export async function requireDiscussionAccess(actor: StudentCommunityActor, discussionId: string, write = false) { const discussion=await prisma.genericDiscussion.findFirst({where:{id:discussionId,institutionId:actor.institutionId,status:{not:"ARCHIVED"}},select:{id:true,authorId:true,communityId:true,isLocked:true,metadata:true}}); if(!discussion)throw new Error("Discussion unavailable."); const m=safeMetadata(discussion.metadata); if(!m.subjectId||!actor.subjectIds.has(m.subjectId))throw new Error("Discussion is outside your enrolled scope."); if(discussion.communityId)await requireGroupAccess(actor,discussion.communityId,write); if(write&&discussion.isLocked)throw new Error("Discussion is locked."); return{...discussion,subjectId:m.subjectId}; }
export async function assertNotBlocked(actor: StudentCommunityActor, peerId: string){if(peerId===actor.id)throw new Error("Choose another eligible learner.");const block=await prisma.studentCommunityBlock.findFirst({where:{institutionId:actor.institutionId,OR:[{blockerId:actor.id,blockedId:peerId},{blockerId:peerId,blockedId:actor.id}]},select:{id:true}});if(block)throw new Error("Collaboration is unavailable.");}
export async function requireAcceptedPeerRequest(actor: StudentCommunityActor, requestId:string){const request=await prisma.studentCommunityRequest.findFirst({where:{id:requestId,institutionId:actor.institutionId,kind:"PEER_COLLABORATION",status:"ACCEPTED",expiresAt:{gt:new Date()},OR:[{requesterId:actor.id},{recipientId:actor.id}]},select:{id:true,requesterId:true,recipientId:true,subjectId:true}});if(!request?.recipientId)throw new Error("An accepted, unexpired collaboration request is required.");requireEnrolledSubject(actor,request.subjectId);const peerId=request.requesterId===actor.id?request.recipientId:request.requesterId;await assertNotBlocked(actor,peerId);const peer=await requireStudentCommunityActor(peerId,actor.institutionId);requireEnrolledSubject(peer,request.subjectId);return{...request,peerId};}
export async function requireConversationParticipant(actor:StudentCommunityActor,conversationId:string){const participant=await prisma.directConversationParticipant.findFirst({where:{conversationId,userId:actor.id,conversation:{institutionId:actor.institutionId,status:"ACTIVE",type:{in:["STUDENT_PEER","STUDY_GROUP"]}}},select:{id:true,conversation:{select:{id:true,type:true,context:true,participants:{select:{userId:true}}}}}});if(!participant)throw new Error("Active conversation participation is required.");for(const p of participant.conversation.participants)if(p.userId!==actor.id)await assertNotBlocked(actor,p.userId);const context=metadata(participant.conversation.context);if(participant.conversation.type==="STUDY_GROUP"){const communityId=typeof context.communityId==="string"?context.communityId:"";await requireGroupAccess(actor,communityId,true)}else if(participant.conversation.type==="STUDENT_PEER"){const requestId=typeof context.requestId==="string"?context.requestId:"",request=await requireAcceptedPeerRequest(actor,requestId);if(!participant.conversation.participants.some(p=>p.userId===request.peerId))throw new Error("Peer conversation participants no longer match the accepted request.")}return participant.conversation;}