import { prisma } from "@/lib/db";

export const ANALYTICS_SETTINGS_KEY = "learnx.analytics.settings";
export type AnalyticsPeriod = "7" | "30" | "90" | "all";
export type AnalyticsSettings = { reportFormat: "csv" | "json"; digest: boolean; trackGoals: boolean; aiRecommendations: boolean; includeAIActivity: boolean; includeAchievements: boolean };
export type AnalyticsPoint = { date: string; score: number | null; accuracy: number | null; speedSeconds: number | null; minutes: number; assessments: number };
export type AnalyticsSubject = { name: string; parent?: string; score: number | null; accuracy: number | null; completion: number | null; objectiveQuestions: number; assessments: number; studyMinutes: number; trend: {date:string;accuracy:number|null}[] };
export type AnalyticsData = {
  learnerName: string; generatedAt: string; period: AnalyticsPeriod; coverageStart: string | null;
  overall: { score: number | null; accuracy: number | null; assessments: number; objectiveQuestions: number; studyMinutes: number; activeDays: number; eligibleDays: number; consistency: number | null; streak: number; speedSeconds: number | null; improvement: number | null; scoreMethod:string };
  subjects: AnalyticsSubject[]; chapters: AnalyticsSubject[]; topics: AnalyticsSubject[]; trends: AnalyticsPoint[];
  concepts: { name: string; subject: string; correct: number; incorrect: number; skipped: number; accuracy: number | null }[];
  goals: { id: string; title: string; type: string; progress: number; status: string; source: string }[];
  achievements: { title: string; date: string | null; source: string }[];
  sessions: { date: string; type: string; title: string; subject?:string; minutes: number; score: number | null }[];
  ai: { sessions: number; activeDays: number; tokens: number; features: string[] };
  insights: { title: string; body: string; action: string; tone: "good" | "attention" | "neutral" }[];
  prediction: { value: number; evidence: number; label: string } | null;
  habitSummary:{dailyMinutes:number;weeklyMinutes:number;monthlyMinutes:number;preferredHours:string|null};
  goalHistory:{date:string|null;title:string;status:string;type:string}[];
  achievementGroups:{milestones:number;badges:number;certificates:number};
  settings: AnalyticsSettings;
  definitions: string[];
};
const obj=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==="object"&&!Array.isArray(v);
const day=(d:Date)=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Calcutta",year:"numeric",month:"2-digit",day:"2-digit"}).format(d);
const clamp=(n:number)=>Math.max(0,Math.min(100,Math.round(n)));
const mean=(xs:number[])=>xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:null;
const defaults:AnalyticsSettings={reportFormat:"csv",digest:false,trackGoals:true,aiRecommendations:true,includeAIActivity:true,includeAchievements:true};

export async function getStudentLearningAnalytics(userId:string|undefined, period:AnalyticsPeriod="30"):Promise<AnalyticsData>{
  const now=new Date(), days=period==="all"?null:Number(period), since=days?new Date(now.getTime()-(days-1)*86400000):undefined;
  const empty:AnalyticsData={learnerName:"Learner",generatedAt:now.toISOString(),period,coverageStart:null,overall:{score:null,accuracy:null,assessments:0,objectiveQuestions:0,studyMinutes:0,activeDays:0,eligibleDays:days??0,consistency:null,streak:0,speedSeconds:null,improvement:null,scoreMethod:"No completed assessment score evidence"},subjects:[],chapters:[],topics:[],trends:[],concepts:[],goals:[],achievements:[],sessions:[],ai:{sessions:0,activeDays:0,tokens:0,features:[]},insights:[{title:"Build your evidence baseline",body:"Complete a lesson or assessment to unlock performance insights.",action:"Start with one focused learning session.",tone:"neutral"}],prediction:null,habitSummary:{dailyMinutes:0,weeklyMinutes:0,monthlyMinutes:0,preferredHours:null},goalHistory:[],achievementGroups:{milestones:0,badges:0,certificates:0},settings:defaults,definitions:["Scores use completed assessments only.","Study time is watch engagement plus submitted assessment active time.","Content completion is a progress proxy, not assessed mastery."]};
  if(!userId)return empty;
  const [user,enrolments,attempts,progress,watches,recent,prefs,conversations,usage]=await Promise.all([
    prisma.user.findUnique({where:{id:userId},select:{name:true,institutionId:true}}),
    prisma.batchStudent.findMany({where:{studentId:userId},select:{batch:{select:{courseId:true}}}}),
    prisma.examAttempt.findMany({where:{studentId:userId,status:{in:["SUBMITTED","AUTO_SUBMITTED","EVALUATED"]},...(since?{submittedAt:{gte:since}}:{})},select:{id:true,submittedAt:true,timeTakenSeconds:true,result:{select:{score:true,percentage:true,correct:true,wrong:true,skipped:true}},exam:{select:{name:true,totalMarks:true,courseId:true,subject:{select:{name:true}}}},answers:{select:{isCorrect:true,status:true,timeSpentSeconds:true,marksAwarded:true,question:{select:{marks:true,type:true,subject:{select:{name:true}},chapter:{select:{name:true}},topic:{select:{name:true}}}}}}},orderBy:{submittedAt:"asc"}}),
    prisma.learningProgress.findMany({where:{studentId:userId},select:{completion:true,studyStreak:true,lastActivityAt:true,achievements:true,subject:{select:{name:true}}}}),
    prisma.watchHistory.findMany({where:{userId,...(since?{updatedAt:{gte:since}}:{})},select:{watchTimeSeconds:true,updatedAt:true,item:{select:{title:true}}}}),
    prisma.recentItem.findMany({where:{userId,type:{startsWith:"learnx.library"},link:{startsWith:"/student/learn"},...(since?{viewedAt:{gte:since}}:{})},select:{title:true,type:true,link:true,viewedAt:true},orderBy:{viewedAt:"desc"},take:100}),
    prisma.userPreference.findMany({where:{userId,key:{in:[ANALYTICS_SETTINGS_KEY,"learnx.practice.sessions","learnx.roadmap.goals","learnx.goals","learnx.roadmap.milestones","learnx.practice.achievements","learnx.roadmap.history","learnx.roadmap.settings","learnx.library.certificates"]}}}),
    prisma.aIConversation.findMany({where:{userId,...(since?{createdAt:{gte:since}}:{})},select:{id:true,createdAt:true}}),
    prisma.aIUsage.findMany({where:{userId,...(since?{createdAt:{gte:since}}:{})},select:{feature:true,totalTokens:true,createdAt:true}})
  ]);
  if(!user)return empty;
  const courseIds=new Set(enrolments.map(e=>e.batch.courseId));
  const safeAttempts=attempts.filter(a=>courseIds.has(a.exam.courseId));
  const map=new Map(prefs.map(p=>[p.key,p.value])), rawSettings=map.get(ANALYTICS_SETTINGS_KEY);
  const settings={...defaults,...(obj(rawSettings)?rawSettings:{})} as AnalyticsSettings;
  type Session={id?:unknown;title?:unknown;state?:unknown;updatedAt?:unknown;elapsed?:unknown;result?:unknown;questionIds?:unknown};
  const custom=(Array.isArray(map.get("learnx.practice.sessions"))?map.get("learnx.practice.sessions") as Session[]:[]).filter(s=>s.state==="submitted"&&obj(s.result)&&(!since||new Date(String(s.updatedAt))>=since));
  const customQuestionIds=[...new Set(custom.flatMap(s=>Array.isArray(s.questionIds)?s.questionIds.map(String):[]))];
  const customQuestions=customQuestionIds.length?await prisma.question.findMany({where:{id:{in:customQuestionIds},courseId:{in:[...courseIds]}},select:{id:true,marks:true,subject:{select:{name:true}},chapter:{select:{name:true}},topic:{select:{name:true}}}}):[];
  const customQuestionMap=new Map(customQuestions.map(q=>[q.id,q]));
  const subjectMap=new Map<string,{earned:number;possible:number;correct:number;wrong:number;skipped:number;assess:Set<string>;time:number}>();
  const chapterMap=new Map<string,{name:string;parent:string;earned:number;possible:number;correct:number;wrong:number;skipped:number;assess:Set<string>;time:number}>();
  const topicMap=new Map<string,{name:string;parent:string;earned:number;possible:number;correct:number;wrong:number;skipped:number;assess:Set<string>;time:number}>();
  const areaDates=new Map<string,Map<string,{correct:number;total:number}>>();
  const concepts=new Map<string,{name:string;subject:string;correct:number;incorrect:number;skipped:number}>();
  const assessmentRows:{date:string;score:number;earned:number|null;possible:number|null;accuracy:number|null;speedSeconds:number|null;minutes:number;title:string;subject?:string}[]=[];
  const recordArea=(map:typeof chapterMap,key:string,name:string,parent:string,earned:number,possible:number,state:"correct"|"wrong"|"skipped",id:string,time:number,date:string)=>{const v=map.get(key)??{name,parent,earned:0,possible:0,correct:0,wrong:0,skipped:0,assess:new Set<string>(),time:0};v.earned+=earned;v.possible+=possible;v[state]++;v.assess.add(id);v.time+=time;map.set(key,v);const dm=areaDates.get(key)??new Map<string,{correct:number;total:number}>(),dp=dm.get(date)??{correct:0,total:0};dp.correct+=Number(state==="correct");dp.total++;dm.set(date,dp);areaDates.set(key,dm)};
  for(const a of safeAttempts){const date=day(a.submittedAt??now),r=a.result;if(!r)continue;const possible=Number(a.exam.totalMarks),earned=Number(r.score),score=possible>0&&Number.isFinite(earned)?earned/possible*100:Number(r.percentage);const objective=a.answers.filter(x=>x.isCorrect!==null||x.status==="SKIPPED");const acc=objective.length?objective.filter(x=>x.isCorrect).length/objective.length*100:null;assessmentRows.push({date,score:clamp(score),earned:possible>0?earned:null,possible:possible>0?possible:null,accuracy:acc===null?null:clamp(acc),speedSeconds:objective.length?Math.round(objective.reduce((n,x)=>n+x.timeSpentSeconds,0)/objective.length):null,minutes:Math.round(a.timeTakenSeconds/60),title:a.exam.name,subject:a.exam.subject?.name});for(const ans of objective){const subject=ans.question.subject.name, s=subjectMap.get(subject)??{earned:0,possible:0,correct:0,wrong:0,skipped:0,assess:new Set<string>(),time:0};s.earned+=Number(ans.marksAwarded);s.possible+=Number(ans.question.marks);s.correct+=Number(ans.isCorrect===true);s.wrong+=Number(ans.isCorrect===false);s.skipped+=Number(ans.status==="SKIPPED");s.time+=ans.timeSpentSeconds;s.assess.add(a.id);subjectMap.set(subject,s);const state=ans.status==="SKIPPED"?"skipped" as const:ans.isCorrect?"correct" as const:"wrong" as const;const dateMap=areaDates.get(subject)??new Map<string,{correct:number;total:number}>(),datePoint=dateMap.get(date)??{correct:0,total:0};datePoint.correct+=Number(state==="correct");datePoint.total++;dateMap.set(date,datePoint);areaDates.set(subject,dateMap);if(ans.question.chapter)recordArea(chapterMap,`${subject}:${ans.question.chapter.name}`,ans.question.chapter.name,subject,Number(ans.marksAwarded),Number(ans.question.marks),state,a.id,ans.timeSpentSeconds,date);if(ans.question.topic)recordArea(topicMap,`${subject}:${ans.question.topic.name}`,ans.question.topic.name,subject,Number(ans.marksAwarded),Number(ans.question.marks),state,a.id,ans.timeSpentSeconds,date);const cname=ans.question.topic?.name??ans.question.chapter?.name??"General";const key=`${subject}:${cname}`,c=concepts.get(key)??{name:cname,subject,correct:0,incorrect:0,skipped:0};c.correct+=Number(ans.isCorrect===true);c.incorrect+=Number(ans.isCorrect===false);c.skipped+=Number(ans.status==="SKIPPED");concepts.set(key,c)}}
  for(const s of custom){const r=s.result as Record<string,unknown>,date=day(new Date(String(s.updatedAt))),id=String(s.id??"custom"),correctIds=new Set(Array.isArray(r.correct)?r.correct.map(String):[]),wrongIds=new Set(Array.isArray(r.incorrect)?r.incorrect.map(String):[]),skippedIds=new Set(Array.isArray(r.skipped)?r.skipped.map(String):[]),manualIds=new Set(Array.isArray(r.manual)?r.manual.map(String):[]),questionIds=Array.isArray(s.questionIds)?s.questionIds.map(String):[],objectiveIds=questionIds.filter(q=>!manualIds.has(q)&&(correctIds.has(q)||wrongIds.has(q)||skippedIds.has(q))),elapsed=Math.max(0,Number(s.elapsed)||0),perQuestion=objectiveIds.length?elapsed/objectiveIds.length:0,earned=Number(r.earned),possible=Number(r.possible),weightedAvailable=possible>0&&Number.isFinite(earned),score=weightedAvailable?earned/possible*100:Number(r.score),accuracy=objectiveIds.length?correctIds.size/objectiveIds.length*100:null;const customSubjects=[...new Set(objectiveIds.map(qid=>customQuestionMap.get(qid)?.subject.name).filter((x):x is string=>Boolean(x)))];if(Number.isFinite(score))assessmentRows.push({date,score:clamp(score),earned:weightedAvailable?earned:null,possible:weightedAvailable?possible:null,accuracy:accuracy===null?null:clamp(accuracy),speedSeconds:objectiveIds.length?Math.round(perQuestion):null,minutes:Math.round(elapsed/60),title:String(s.title||"Custom practice"),subject:customSubjects.join(", ")||undefined});for(const qid of objectiveIds){const q=customQuestionMap.get(qid);if(!q)continue;const subject=q.subject.name,state=correctIds.has(qid)?"correct" as const:skippedIds.has(qid)?"skipped" as const:"wrong" as const,marks=Number(q.marks),awarded=state==="correct"?marks:0,v=subjectMap.get(subject)??{earned:0,possible:0,correct:0,wrong:0,skipped:0,assess:new Set<string>(),time:0};v.earned+=awarded;v.possible+=marks;v[state]++;v.assess.add(id);v.time+=perQuestion;subjectMap.set(subject,v);const dm=areaDates.get(subject)??new Map<string,{correct:number;total:number}>(),dp=dm.get(date)??{correct:0,total:0};dp.correct+=Number(state==="correct");dp.total++;dm.set(date,dp);areaDates.set(subject,dm);if(q.chapter)recordArea(chapterMap,`${subject}:${q.chapter.name}`,q.chapter.name,subject,awarded,marks,state,id,perQuestion,date);if(q.topic)recordArea(topicMap,`${subject}:${q.topic.name}`,q.topic.name,subject,awarded,marks,state,id,perQuestion,date);const cname=q.topic?.name??q.chapter?.name??"General",key=`${subject}:${cname}`,cv=concepts.get(key)??{name:cname,subject,correct:0,incorrect:0,skipped:0};cv.correct+=Number(state==="correct");cv.incorrect+=Number(state==="wrong");cv.skipped+=Number(state==="skipped");concepts.set(key,cv)}}
  assessmentRows.sort((a,b)=>a.date.localeCompare(b.date));const completion=new Map(progress.filter(p=>p.subject).map(p=>[p.subject!.name,p.completion]));
  const trendFor=(key:string)=>[...(areaDates.get(key)?.entries()??[])].sort((a,b)=>a[0].localeCompare(b[0])).map(([date,v])=>({date,accuracy:v.total?clamp(v.correct/v.total*100):null}));const subjects=[...new Set([...subjectMap.keys(),...completion.keys()])].map(name=>{const s=subjectMap.get(name),denom=s?s.correct+s.wrong+s.skipped:0;return{name,score:s&&s.possible>0?clamp(s.earned/s.possible*100):null,accuracy:s&&denom?clamp(s.correct/denom*100):null,completion:completion.get(name)??null,objectiveQuestions:denom,assessments:s?.assess.size??0,studyMinutes:s?Math.round(s.time/60):0,trend:trendFor(name)}}).sort((a,b)=>(b.objectiveQuestions-a.objectiveQuestions));const toAreas=(map:typeof chapterMap):AnalyticsSubject[]=>[...map.entries()].map(([key,s])=>{const denom=s.correct+s.wrong+s.skipped;return{name:s.name,parent:s.parent,score:s.possible>0?clamp(s.earned/s.possible*100):null,accuracy:denom?clamp(s.correct/denom*100):null,completion:null,objectiveQuestions:denom,assessments:s.assess.size,studyMinutes:Math.round(s.time/60),trend:trendFor(key)}}).sort((a,b)=>b.objectiveQuestions-a.objectiveQuestions),chapters=toAreas(chapterMap),topics=toAreas(topicMap);
  const dates=new Map<string,AnalyticsPoint>();const touch=(d:string)=>{if(!dates.has(d))dates.set(d,{date:d,score:null,accuracy:null,speedSeconds:null,minutes:0,assessments:0});return dates.get(d)!};
  assessmentRows.forEach(a=>{const p=touch(a.date);p.minutes+=a.minutes;p.assessments++;});watches.forEach(w=>touch(day(w.updatedAt)).minutes+=Math.round(w.watchTimeSeconds/60));recent.forEach(x=>touch(day(x.viewedAt)));if(settings.includeAIActivity){conversations.forEach(x=>touch(day(x.createdAt)));usage.forEach(x=>touch(day(x.createdAt)))}
  for(const [d,p] of dates){const rows=assessmentRows.filter(x=>x.date===d);p.score=mean(rows.map(x=>x.score));p.accuracy=mean(rows.flatMap(x=>x.accuracy===null?[]:[x.accuracy]));p.speedSeconds=mean(rows.flatMap(x=>x.speedSeconds===null?[]:[x.speedSeconds]));}
  const trends=[...dates.values()].sort((a,b)=>a.date.localeCompare(b.date)),active=[...dates.keys()].sort(),eligible=days??(active.length?Math.max(1,Math.ceil((now.getTime()-new Date(active[0]).getTime())/86400000)+1):0);
  let streak=0,cursor=new Date(now);if(!active.includes(day(cursor)))cursor=new Date(now.getTime()-86400000);while(active.includes(day(cursor))){streak++;cursor=new Date(cursor.getTime()-86400000)}
  const scores=assessmentRows.map(x=>x.score),scorable=assessmentRows.filter(x=>x.earned!==null&&x.possible!==null&&x.possible>0),allWeighted=assessmentRows.length>0&&scorable.length===assessmentRows.length,assessmentEarned=scorable.reduce((n,x)=>n+x.earned!,0),assessmentPossible=scorable.reduce((n,x)=>n+x.possible!,0),overallScore=allWeighted&&assessmentPossible>0?clamp(assessmentEarned/assessmentPossible*100):mean(scores)===null?null:clamp(mean(scores)!),scoreMethod=allWeighted?`Weighted earned/possible across ${assessmentRows.length} completed assessments`:`Mean of ${assessmentRows.length} completed-assessment percentages because compatible totals are not available for every assessment`,half=Math.floor(scores.length/2), improvement=half&&scores.length-half?mean(scores.slice(half))!-mean(scores.slice(0,half))!:null,recentAssessments=assessmentRows.slice(-3),recentWeighted=recentAssessments.length===3&&recentAssessments.every(x=>x.earned!==null&&x.possible!==null&&x.possible>0),recentPossible=recentAssessments.reduce((n,x)=>n+(x.possible??0),0),recentEstimate=recentAssessments.length===3?(recentWeighted&&recentPossible>0?clamp(recentAssessments.reduce((n,x)=>n+(x.earned??0),0)/recentPossible*100):clamp(mean(recentAssessments.map(x=>x.score))!)):null,recentLabel=recentWeighted?"Earned marks divided by possible marks across the latest 3 completed assessments - not a guarantee":"Average of the latest 3 completed-assessment percentages - not a guarantee";
  const objective=[...subjectMap.values()].reduce((n,s)=>n+s.correct+s.wrong+s.skipped,0),correct=[...subjectMap.values()].reduce((n,s)=>n+s.correct,0),totalSeconds=[...subjectMap.values()].reduce((n,s)=>n+s.time,0);
  const toRecords=(v:unknown)=>Array.isArray(v)?v.filter(obj):[];const goalRaw=[...toRecords(map.get("learnx.roadmap.goals")),...toRecords(map.get("learnx.goals"))];
  const goals=goalRaw.map((g,i)=>({id:String(g.id??i),title:String(g.title??"Untitled goal"),type:String(g.type??"Uncategorized"),progress:clamp(Number(g.progress)||0),status:String(g.status??"active"),source:"Student goal (self-reported progress)"}));
  const achievementRows:AnalyticsData["achievements"]=[];for(const p of progress)for(const a of Array.isArray(p.achievements)?p.achievements:[])achievementRows.push({title:String(a),date:null,source:"Learning progress"});for(const a of toRecords(map.get("learnx.roadmap.milestones")).filter(x=>x.status==="completed"))achievementRows.push({title:String(a.title),date:typeof a.completedAt==="string"?a.completedAt:null,source:"Roadmap milestone"});for(const a of Array.isArray(map.get("learnx.practice.achievements"))?map.get("learnx.practice.achievements") as unknown[]:[])achievementRows.push({title:String(a),date:null,source:"Practice achievement"});
  const weakest=subjects.filter(s=>s.objectiveQuestions>=3&&s.accuracy!==null).sort((a,b)=>a.accuracy!-b.accuracy!)[0], strongest=subjects.filter(s=>s.objectiveQuestions>=3&&s.accuracy!==null).sort((a,b)=>b.accuracy!-a.accuracy!)[0];
  const insights:AnalyticsData["insights"]=weakest?[{title:`Prioritize ${weakest.name}`,body:`${weakest.accuracy}% accuracy across ${weakest.objectiveQuestions} objective questions provides enough evidence for a focused review.`,action:`Revise one ${weakest.name} concept, then retry a short practice set.`,tone:"attention"},...(strongest?[{title:`Momentum in ${strongest.name}`,body:`${strongest.accuracy}% accuracy is your strongest evidence-backed area.`,action:"Use spaced revision to retain this strength.",tone:"good" as const}]:[])]:empty.insights;
  const certificateRaw=Array.isArray(map.get("learnx.library.certificates"))?map.get("learnx.library.certificates") as unknown[]:[];for(const a of certificateRaw){achievementRows.push({title:obj(a)?String(a.title??a.name??"Course certificate"):String(a),date:obj(a)&&typeof a.completedAt==="string"?a.completedAt:null,source:"Stored course certificate"})}const goalHistory=toRecords(map.get("learnx.roadmap.history")).filter(x=>String(x.type??"").toLowerCase().includes("goal")).map(x=>({date:typeof x.at==="string"?x.at:null,title:String(x.title??"Goal updated"),status:String(x.status??x.type??"updated"),type:String(x.type??"Uncategorized")}));const roadmapSettings=map.get("learnx.roadmap.settings"),preferredHours=obj(roadmapSettings)&&typeof roadmapSettings.preferredHours==="string"?roadmapSettings.preferredHours:null,nowDay=day(now),weekStart=day(new Date(now.getTime()-6*86400000)),monthStart=day(new Date(now.getTime()-29*86400000)),last7=trends.filter(x=>x.date>=weekStart&&x.date<=nowDay),last30=trends.filter(x=>x.date>=monthStart&&x.date<=nowDay),habitSummary={dailyMinutes:trends.find(x=>x.date===nowDay)?.minutes??0,weeklyMinutes:last7.reduce((n,x)=>n+x.minutes,0),monthlyMinutes:last30.reduce((n,x)=>n+x.minutes,0),preferredHours};const aiDays=new Set([...conversations.map(x=>day(x.createdAt)),...usage.map(x=>day(x.createdAt))]);
  return{learnerName:user.name??"Learner",generatedAt:now.toISOString(),period,coverageStart:active[0]??null,overall:{score:overallScore,accuracy:objective?clamp(correct/objective*100):null,assessments:assessmentRows.length,objectiveQuestions:objective,studyMinutes:trends.reduce((n,p)=>n+p.minutes,0),activeDays:active.length,eligibleDays:eligible,consistency:eligible?clamp(active.length/eligible*100):null,streak,speedSeconds:objective&&totalSeconds?Math.round(totalSeconds/objective):null,improvement:improvement===null?null:Math.round(improvement),scoreMethod},subjects,chapters,topics,trends,concepts:[...concepts.values()].map(c=>({...c,accuracy:c.correct+c.incorrect+c.skipped?clamp(c.correct/(c.correct+c.incorrect+c.skipped)*100):null})).sort((a,b)=>b.incorrect-a.incorrect),goals,achievements:settings.includeAchievements?achievementRows:[],sessions:[...assessmentRows.map(x=>({date:x.date,type:"Assessment",title:x.title,subject:x.subject,minutes:x.minutes,score:x.score})),...watches.map(x=>({date:day(x.updatedAt),type:"Lesson",title:x.item.title,minutes:Math.round(x.watchTimeSeconds/60),score:null}))].sort((a,b)=>b.date.localeCompare(a.date)),ai:settings.includeAIActivity?{sessions:conversations.length,activeDays:aiDays.size,tokens:usage.reduce((n,x)=>n+x.totalTokens,0),features:[...new Set(usage.map(x=>x.feature))]}:{sessions:0,activeDays:0,tokens:0,features:[]},insights:settings.aiRecommendations?insights:[],prediction:recentEstimate===null?null:{value:recentEstimate,evidence:3,label:recentLabel},habitSummary,goalHistory,achievementGroups:settings.includeAchievements?{milestones:achievementRows.filter(x=>x.source==="Roadmap milestone").length,badges:achievementRows.filter(x=>x.source==="Learning progress"||x.source==="Practice achievement").length,certificates:achievementRows.filter(x=>x.source==="Stored course certificate").length}:{milestones:0,badges:0,certificates:0},settings,definitions:[scoreMethod,"Accuracy is correct divided by (correct + wrong + skipped) for objective answers; manual/ungraded answers are excluded.","Study time is recorded watch engagement plus submitted assessment active time.","Consistency is active days divided by eligible local days. AI activity is included only when opted in.","Content completion is displayed separately as a progress proxy, not assessed mastery."]};
}
