import { createHash } from "crypto";
import { prisma } from "@/lib/db";

export const GAMIFICATION_KEYS={settings:"learnx.gamification.settings",redemptions:"learnx.gamification.redemptions"} as const;
export const REWARD_RULE_VERSION="learnx-gamification-v1";
export type GamificationSettings={challenges:boolean;notifications:boolean;leaderboard:boolean;achievements:boolean;celebrations:boolean;rewardPreference:"balanced"|"academic"|"consistency"};
export type RewardEvent={key:string;sourceType:string;sourceId:string;title:string;category:string;at:string|null;xp:number;coins:number;provenance:string};
export type Redemption={id:string;catalogId:string;title:string;cost:number;at:string};
export type GamificationData={
 learnerName:string; timezone:string; generatedAt:string; ruleVersion:string;
 totals:{xp:number;coinsEarned:number;coinsSpent:number;coinsBalance:number;level:number;levelName:string;nextLevelXp:number|null;levelFloor:number;streak:number;bestStreak:number;activeDays:number;weeklyActiveDays:number;monthlyActiveDays:number};
 history:RewardEvent[]; redemptions:Redemption[];
 breakdown:{category:string;xp:number;coins:number;events:number;availability:string}[];
 badges:{id:string;title:string;category:string;earned:boolean;at:string|null;criteria:string;provenance:string}[];
 levels:{level:number;name:string;threshold:number;benefit:string;reached:boolean}[]; levelHistory:{level:number;name:string;at:string|null;xp:number}[];
 challenges:{id:string;title:string;kind:string;target:number;progress:number;unit:string;window:string;qualifyingEvidence:string;completed:boolean}[];
 leaderboard:{enabled:boolean;eligible:boolean;scope:string;rows:{rank:number;alias:string;score:number;assessments:number;current:boolean}[];friendsAvailable:false;message:string};
 catalog:{id:string;title:string;description:string;cost:number;unlocked:boolean}[];
 settings:GamificationSettings;
 evidence:{lesson:number;ai:number;practice:number;mock:number;revision:number|null;login:number|null;goals:number;course:number;milestones:number};
};
const object=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==="object"&&!Array.isArray(v);
const boundedString=(v:unknown,max=120)=>typeof v==="string"?v.slice(0,max):"";
const localDay=(date:Date,timeZone:string)=>{try{return new Intl.DateTimeFormat("en-CA",{timeZone,year:"numeric",month:"2-digit",day:"2-digit"}).format(date)}catch{return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata",year:"numeric",month:"2-digit",day:"2-digit"}).format(date)}};
const defaults:GamificationSettings={challenges:true,notifications:false,leaderboard:false,achievements:true,celebrations:true,rewardPreference:"balanced"};
const levels=[{level:1,name:"Navigator",threshold:0,benefit:"Learning orbit and evidence history"},{level:2,name:"Pathfinder",threshold:150,benefit:"Mint profile accent"},{level:3,name:"Scholar",threshold:400,benefit:"Amber achievement frame"},{level:4,name:"Luminary",threshold:800,benefit:"Observatory profile title"},{level:5,name:"Mentor",threshold:1400,benefit:"Mastery constellation theme"}];
export const rewardCatalog=[{id:"mint-accent",title:"Mint profile accent",description:"A non-commerce LearnX profile reward.",cost:80},{id:"amber-frame",title:"Amber achievement frame",description:"A non-commerce LearnX celebration frame.",cost:140},{id:"observatory-title",title:"Observatory title",description:"A LearnX motivation profile title.",cost:220}] as const;
const settingsFrom=(v:unknown):GamificationSettings=>{if(!object(v))return defaults;return{challenges:typeof v.challenges==="boolean"?v.challenges:defaults.challenges,notifications:typeof v.notifications==="boolean"?v.notifications:defaults.notifications,leaderboard:typeof v.leaderboard==="boolean"?v.leaderboard:false,achievements:typeof v.achievements==="boolean"?v.achievements:defaults.achievements,celebrations:typeof v.celebrations==="boolean"?v.celebrations:defaults.celebrations,rewardPreference:v.rewardPreference==="academic"||v.rewardPreference==="consistency"?v.rewardPreference:"balanced"}};
const redemptionRows=(v:unknown):Redemption[]=>{if(!Array.isArray(v))return[];const rows=v.slice(0,100).filter(object).flatMap(x=>{const catalogId=boundedString(x.catalogId,40),item=rewardCatalog.find(r=>r.id===catalogId),at=boundedString(x.at,40),date=new Date(at);return item&&at&&!Number.isNaN(date.getTime())?[{id:`redeem:${catalogId}`,catalogId,title:item.title,cost:item.cost,at:date.toISOString()}]:[]});return[...new Map(rows.map(x=>[x.catalogId,x])).values()]};
const event=(sourceType:string,sourceId:string,title:string,category:string,at:Date|null,xp:number,coins:number,provenance:string):RewardEvent=>({key:`${REWARD_RULE_VERSION}:${sourceType}:${sourceId}`,sourceType,sourceId,title,category,at:at?.toISOString()??null,xp,coins,provenance});
const streakFrom=(dates:string[],timezone:string)=>{const unique=[...new Set(dates)].sort(),set=new Set(unique),today=localDay(new Date(),timezone),yesterday=localDay(new Date(Date.now()-86400000),timezone);let cursor=set.has(today)?new Date():set.has(yesterday)?new Date(Date.now()-86400000):null,streak=0;if(cursor)while(set.has(localDay(cursor,timezone))){streak++;cursor=new Date(cursor.getTime()-86400000)}let best=0,run=0,prior="";for(const d of unique){const expected=prior?new Date(new Date(`${prior}T00:00:00Z`).getTime()+86400000).toISOString().slice(0,10):"";run=prior&&d===expected?run+1:1;best=Math.max(best,run);prior=d}return{streak,best}};

export async function getStudentGamification(userId:string|undefined,leaderboardWindow:"week"|"month"="week"):Promise<GamificationData>{
 const empty:GamificationData={learnerName:"Learner",timezone:"Asia/Kolkata",generatedAt:new Date().toISOString(),ruleVersion:REWARD_RULE_VERSION,totals:{xp:0,coinsEarned:0,coinsSpent:0,coinsBalance:0,level:1,levelName:"Navigator",nextLevelXp:150,levelFloor:0,streak:0,bestStreak:0,activeDays:0,weeklyActiveDays:0,monthlyActiveDays:0},history:[],redemptions:[],breakdown:[],badges:[],levels:levels.map(x=>({...x,reached:false})),levelHistory:[],challenges:[],leaderboard:{enabled:false,eligible:false,scope:leaderboardWindow,rows:[],friendsAvailable:false,message:"Leaderboard participation is private and off by default."},catalog:rewardCatalog.map(x=>({...x,unlocked:false})),settings:defaults,evidence:{lesson:0,ai:0,practice:0,mock:0,revision:null,login:null,goals:0,course:0,milestones:0}};
 if(!userId)return empty;
 const [user,enrollments,watches,attempts,usage,prefs,progress]=await Promise.all([
  prisma.user.findUnique({where:{id:userId},select:{name:true,institutionId:true,institution:{select:{timezone:true}}}}),
  prisma.batchStudent.findMany({where:{studentId:userId},select:{batchId:true,batch:{select:{courseId:true}}}}),
  prisma.watchHistory.findMany({where:{userId,completed:true},select:{id:true,itemId:true,updatedAt:true,item:{select:{title:true,courseId:true,institutionId:true}}},orderBy:{updatedAt:"asc"},take:500}),
  prisma.examAttempt.findMany({where:{studentId:userId,status:{in:["SUBMITTED","AUTO_SUBMITTED","EVALUATED"]},result:{isNot:null}},select:{id:true,submittedAt:true,updatedAt:true,result:{select:{percentage:true}},exam:{select:{name:true,type:true,courseId:true}}},orderBy:{updatedAt:"asc"},take:500}),
  prisma.aIUsage.findMany({where:{userId},select:{id:true,feature:true,createdAt:true},orderBy:{createdAt:"asc"},take:500}),
  prisma.userPreference.findMany({where:{userId,key:{in:[GAMIFICATION_KEYS.settings,GAMIFICATION_KEYS.redemptions,"learnx.roadmap.goals","learnx.goals","learnx.roadmap.milestones"]}}}),
  prisma.learningProgress.findMany({where:{studentId:userId},select:{id:true,courseId:true,completion:true,updatedAt:true,achievements:true,subject:{select:{name:true}},course:{select:{name:true}},classroom:{select:{institutionId:true}}}})
 ]);
 if(!user)return empty;const timezone=user.institution?.timezone||"Asia/Kolkata",courseIds=new Set(enrollments.map(x=>x.batch.courseId)),preferenceMap=new Map(prefs.map(x=>[x.key,x.value])),settings=settingsFrom(preferenceMap.get(GAMIFICATION_KEYS.settings)),redemptions=redemptionRows(preferenceMap.get(GAMIFICATION_KEYS.redemptions)),events:RewardEvent[]=[],safeAttempts=attempts.filter(x=>courseIds.has(x.exam.courseId)),safeWatches=watches.filter(x=>courseIds.has(x.item.courseId)&&x.item.institutionId===user.institutionId),safeProgress=progress.filter(x=>courseIds.has(x.courseId)&&x.classroom.institutionId===user.institutionId);
 safeWatches.forEach(x=>events.push(event("watch",x.id,`Completed ${x.item.title}`,"Lesson",x.updatedAt,20,2,"Completed WatchHistory")));
 safeAttempts.forEach(x=>{const score=Number(x.result?.percentage??0),mock=x.exam.type==="MOCK";events.push(event("exam",x.id,`Completed ${x.exam.name}`,mock?"Mock":"Practice",x.submittedAt??x.updatedAt,10+(score>=80?15:0),2+(score>=80?2:0),`Official completed assessment; ${Math.round(score)}%`))});
 usage.forEach(x=>events.push(event("ai",x.id,`Used ${boundedString(x.feature,60)||"AI learning"}`,"AI",x.createdAt,2,0,"Student AIUsage metadata; messages excluded")));
 const records=(v:unknown)=>Array.isArray(v)?v.filter(object).slice(0,200):[];
 const goals=[...records(preferenceMap.get("learnx.roadmap.goals")),...records(preferenceMap.get("learnx.goals"))].filter(x=>x.status==="completed"),milestones=records(preferenceMap.get("learnx.roadmap.milestones")).filter(x=>x.status==="completed");
 goals.forEach(x=>{const id=boundedString(x.id,80),raw=boundedString(x.completedAt,40),at=raw?new Date(raw):null;if(id&&at&&!Number.isNaN(at.getTime()))events.push(event("goal",id,`Completed ${boundedString(x.title)||"goal"}`,"Goal",at,30,4,"Persisted completed goal with source date"))});
 milestones.forEach(x=>{const id=boundedString(x.id,80),raw=boundedString(x.completedAt,40),at=raw?new Date(raw):null;if(id&&at&&!Number.isNaN(at.getTime()))events.push(event("milestone",id,boundedString(x.title)||"Completed milestone","Milestone",at,25,3,"Persisted completed roadmap milestone with source date"))});
 safeProgress.filter(x=>x.completion>=100).forEach(x=>events.push(event("course",x.id,`Completed ${x.course.name}${x.subject?` · ${x.subject.name}`:""}`,"Course",x.updatedAt,50,8,"LearningProgress reached 100%")));
 const unique=[...new Map(events.map(x=>[x.key,x])).values()].sort((a,b)=>(b.at??"").localeCompare(a.at??"")),xp=unique.reduce((n,x)=>n+x.xp,0),coinsEarned=unique.reduce((n,x)=>n+x.coins,0),coinsSpent=redemptions.reduce((n,x)=>n+x.cost,0),coinsBalance=Math.max(0,coinsEarned-coinsSpent),current=[...levels].reverse().find(x=>xp>=x.threshold)??levels[0],next=levels.find(x=>x.threshold>xp),dates=unique.flatMap(x=>x.at?[localDay(new Date(x.at),timezone)]:[]),streaks=streakFrom(dates,timezone);
 const legacy=safeProgress.flatMap(x=>Array.isArray(x.achievements)?x.achievements.map(String).slice(0,30):[]),badgeCandidates=[
  {id:"first-lesson",title:"First Light",category:"Academic",earned:safeWatches.length>=1,at:safeWatches[0]?.updatedAt??null,criteria:"Complete one lesson",provenance:"Completed WatchHistory"},
  {id:"practice-five",title:"Practice Pulse",category:"Practice",earned:safeAttempts.length>=5,at:[...safeAttempts.map(x=>x.submittedAt??x.updatedAt)].filter(x=>!Number.isNaN(x.getTime())).sort((a,b)=>a.getTime()-b.getTime())[4]??null,criteria:"Complete five submitted assessments",provenance:"Official completed enrolled assessments"},
  {id:"streak-seven",title:"Seven-Day Orbit",category:"Consistency",earned:streaks.best>=7,at:null,criteria:"Reach a verified seven-day activity streak",provenance:"Verified evidence dates; achievement date unavailable"},
  {id:"ai-ten",title:"Curious Mind",category:"AI",earned:usage.length>=10,at:usage[9]?.createdAt??null,criteria:"Use student AI learning ten times",provenance:"AIUsage metadata"},
  {id:"course-one",title:"Course Finisher",category:"Course",earned:safeProgress.some(x=>x.completion>=100),at:safeProgress.filter(x=>x.completion>=100).sort((a,b)=>a.updatedAt.getTime()-b.updatedAt.getTime())[0]?.updatedAt??null,criteria:"Reach 100% recorded course progress",provenance:"LearningProgress"}
 ].map(x=>({...x,at:x.at?.toISOString()??null}));
 milestones.forEach((x,i)=>{const raw=boundedString(x.completedAt,40),at=raw?new Date(raw):null;badgeCandidates.push({id:`milestone-${boundedString(x.id,60)||i}`,title:boundedString(x.title)||"Roadmap milestone",category:"Milestone",earned:true,at:at&&!Number.isNaN(at.getTime())?at.toISOString():null,criteria:"Persisted completed roadmap milestone",provenance:at&&!Number.isNaN(at.getTime())?"Roadmap milestone with source date":"Roadmap milestone; date unavailable"})});
 legacy.forEach((title,i)=>badgeCandidates.push({id:`legacy-${i}`,title,category:"Legacy",earned:true,at:null,criteria:"Legacy persisted achievement",provenance:"LearningProgress achievement; date unavailable"}));
 const byCategory=new Map<string,{xp:number;coins:number;events:number}>();unique.forEach(x=>{const v=byCategory.get(x.category)??{xp:0,coins:0,events:0};v.xp+=x.xp;v.coins+=x.coins;v.events++;byCategory.set(x.category,v)});
 const today=localDay(new Date(),timezone),weekStart=localDay(new Date(Date.now()-6*86400000),timezone),monthStart=localDay(new Date(Date.now()-29*86400000),timezone),dailyEvents=unique.filter(x=>x.at&&localDay(new Date(x.at),timezone)===today),weeklyEvents=unique.filter(x=>x.at&&localDay(new Date(x.at),timezone)>=weekStart),monthlyEvents=unique.filter(x=>x.at&&localDay(new Date(x.at),timezone)>=monthStart),challenges=[{id:"daily-xp",title:"Daily learning spark",kind:"Daily",target:20,progress:dailyEvents.reduce((n,x)=>n+x.xp,0),unit:"verified XP",window:`${today} local day`,qualifyingEvidence:"Any verified XP event",completed:false},{id:"weekly-practice",title:"Weekly practice rhythm",kind:"Weekly",target:3,progress:weeklyEvents.filter(x=>x.category==="Practice"||x.category==="Mock").length,unit:"submitted assessments",window:`Since ${weekStart}`,qualifyingEvidence:"Official or submitted L06 assessment",completed:false},{id:"monthly-lessons",title:"Monthly learning orbit",kind:"Monthly",target:12,progress:monthlyEvents.filter(x=>x.category==="Lesson").length,unit:"completed lessons",window:`Since ${monthStart}`,qualifyingEvidence:"Completed WatchHistory",completed:false},{id:"subject-focus",title:"Subject focus",kind:"Subject",target:1,progress:0,unit:"subject goal",window:"Current month",qualifyingEvidence:"No subject-scoped challenge evidence is persisted",completed:false},{id:"ai-week",title:"AI curiosity",kind:"AI",target:3,progress:weeklyEvents.filter(x=>x.category==="AI").length,unit:"AI learning uses",window:`Since ${weekStart}`,qualifyingEvidence:"Student AIUsage metadata",completed:false}].map(x=>({...x,progress:Math.min(x.target,x.progress),completed:x.progress>=x.target})).sort((a,b)=>{const preferred=settings.rewardPreference==="academic"?["Subject","Weekly","Monthly","Daily","AI"]:settings.rewardPreference==="consistency"?["Daily","Monthly","Weekly","AI","Subject"]:["Daily","Weekly","Monthly","Subject","AI"];return preferred.indexOf(a.kind)-preferred.indexOf(b.kind)});
 let leaderboard:GamificationData["leaderboard"]={enabled:settings.leaderboard,eligible:!!user.institutionId&&courseIds.size>0,scope:leaderboardWindow,rows:[],friendsAvailable:false,message:settings.leaderboard?"No eligible opted-in peers have assessment evidence in this window.":"Leaderboard participation is private and off by default."};
 if(settings.leaderboard&&user.institutionId&&courseIds.size){const since=leaderboardWindow==="week"?new Date(Date.now()-7*86400000):new Date(Date.now()-30*86400000),peerEnrollments=await prisma.batchStudent.findMany({where:{batchId:{in:enrollments.map(x=>x.batchId)}},select:{studentId:true}}),peerIds=[...new Set(peerEnrollments.map(x=>x.studentId))],peerPrefs=await prisma.userPreference.findMany({where:{userId:{in:peerIds},key:GAMIFICATION_KEYS.settings},select:{userId:true,value:true}}),opted=new Set(peerPrefs.filter(x=>settingsFrom(x.value).leaderboard).map(x=>x.userId));opted.add(userId);const peerAttempts=await prisma.examAttempt.findMany({where:{studentId:{in:[...opted]},status:{in:["SUBMITTED","AUTO_SUBMITTED","EVALUATED"]},submittedAt:{gte:since},exam:{institutionId:user.institutionId,courseId:{in:[...courseIds]}},result:{isNot:null}},select:{studentId:true,result:{select:{percentage:true}}}}),aggregate=new Map<string,number[]>();peerAttempts.forEach(x=>aggregate.set(x.studentId,[...(aggregate.get(x.studentId)??[]),Number(x.result?.percentage??0)]));const ranked=[...aggregate.entries()].map(([id,scores])=>({id,score:Math.round(scores.reduce((a,b)=>a+b,0)/scores.length),assessments:scores.length})).sort((a,b)=>b.score-a.score||b.assessments-a.assessments);leaderboard={...leaderboard,rows:ranked.map((x,i)=>({rank:i+1,alias:x.id===userId?"You":`Learner ${createHash("sha256").update(`${user.institutionId}:${x.id}`).digest("hex").slice(0,5).toUpperCase()}`,score:x.score,assessments:x.assessments,current:x.id===userId})),message:ranked.length?"Only opted-in learners in your enrolled classes are included.":"No eligible opted-in peers have assessment evidence in this window."}}
 const ruleCatalog=[{category:"Lesson",availability:"20 XP + 2 coins per enrolled completed WatchHistory"},{category:"AI",availability:"2 XP per student AIUsage metadata event"},{category:"Practice",availability:"10 XP + score bonus from official completed enrolled assessment"},{category:"Mock",availability:"10 XP + score bonus from official completed enrolled mock"},{category:"Revision",availability:"Unavailable: no dedicated revision event model"},{category:"Login",availability:"Unavailable: no authoritative login history"},{category:"Goal",availability:"30 XP + 4 coins for dated completed goal"},{category:"Course",availability:"50 XP + 8 coins at enrolled LearningProgress 100%"},{category:"Milestone",availability:"25 XP + 3 coins for dated completed roadmap milestone"}],ruleBreakdown=ruleCatalog.map(rule=>({category:rule.category,...(byCategory.get(rule.category)??{xp:0,coins:0,events:0}),availability:rule.availability})),chronological=[...unique].filter(x=>x.at).sort((a,b)=>a.at!.localeCompare(b.at!)),levelHistory:GamificationData["levelHistory"]=[],running={xp:0};for(const reward of chronological){running.xp+=reward.xp;for(const level of levels)if(running.xp>=level.threshold&&!levelHistory.some(x=>x.level===level.level))levelHistory.push({level:level.level,name:level.name,at:reward.at,xp:running.xp})}const weeklyActiveDays=new Set(dates.filter(x=>x>=weekStart)).size,monthlyActiveDays=new Set(dates.filter(x=>x>=monthStart)).size;
 return{learnerName:user.name??"Learner",timezone,generatedAt:new Date().toISOString(),ruleVersion:REWARD_RULE_VERSION,totals:{xp,coinsEarned,coinsSpent,coinsBalance,level:xp>0?current.level:0,levelName:xp>0?current.name:"Not started",nextLevelXp:next?.threshold??null,levelFloor:current.threshold,streak:streaks.streak,bestStreak:streaks.best,activeDays:new Set(dates).size,weeklyActiveDays,monthlyActiveDays},history:unique,redemptions,breakdown:ruleBreakdown,badges:settings.achievements?badgeCandidates:[],levels:levels.map(x=>({...x,reached:xp>0&&xp>=x.threshold})),levelHistory,challenges:settings.challenges?challenges:[],leaderboard,catalog:rewardCatalog.map(x=>({...x,unlocked:redemptions.some(r=>r.catalogId===x.id)})),settings,evidence:{lesson:safeWatches.length,ai:usage.length,practice:safeAttempts.filter(x=>x.exam.type==="PRACTICE").length,mock:safeAttempts.filter(x=>x.exam.type==="MOCK").length,revision:null,login:null,goals:goals.length,course:safeProgress.filter(x=>x.completion>=100).length,milestones:milestones.length}};
}
