import { cache } from "react";
import { z } from "zod";

import { prisma } from "@/lib/db";

const WHITE_LABEL_KEY = "white_label";

export const whiteLabelSchema = z.object({
  institutionName: z.string().min(2),
  logoUrl: z.string().url().optional().or(z.literal("")),
  faviconUrl: z.string().url().optional().or(z.literal("")),
  primaryColor: z.string().min(4),
  secondaryColor: z.string().min(4),
  accentColor: z.string().min(4),
  theme: z.enum(["light", "calm", "contrast"]).default("light"),
  contactEmail: z.string().email().optional().or(z.literal("")),
  contactPhone: z.string().optional(),
  applicationTitle: z.string().min(2),
  browserTitle: z.string().min(2),
  footerText: z.string().optional(),
  socialLinks: z.array(z.object({ label: z.string(), url: z.string().url() })).default([]),
  emailTemplate: z.string().optional(),
  certificateTemplate: z.string().optional(),
  invoiceTemplate: z.string().optional(),
  pdfBranding: z.object({
    showLogo: z.boolean().default(true),
    showAddress: z.boolean().default(true),
    footerNote: z.string().optional()
  }).default({ showLogo: true, showAddress: true })
});

export type WhiteLabelConfig = z.infer<typeof whiteLabelSchema>;

export function defaultWhiteLabelConfig(institutionName = "Education OS"): WhiteLabelConfig {
  return {
    institutionName,
    logoUrl: "",
    faviconUrl: "",
    primaryColor: "#111827",
    secondaryColor: "#64748b",
    accentColor: "#0f766e",
    theme: "light",
    contactEmail: "",
    contactPhone: "",
    applicationTitle: institutionName,
    browserTitle: `${institutionName} | Education OS`,
    footerText: "Powered by Education OS",
    socialLinks: [],
    emailTemplate: "Simple branded email",
    certificateTemplate: "Standard certificate",
    invoiceTemplate: "Standard invoice",
    pdfBranding: { showLogo: true, showAddress: true, footerNote: "Generated by Education OS" }
  };
}

export const getWhiteLabelConfig = cache(async (institutionId?: string | null) => {
  if (!institutionId) return defaultWhiteLabelConfig();
  const institution = await prisma.institution.findUnique({ where: { id: institutionId }, include: { settings: { where: { key: WHITE_LABEL_KEY }, take: 1 } } });
  const fallback = defaultWhiteLabelConfig(institution?.name ?? "Education OS");
  const saved = institution?.settings[0]?.value;
  const parsed = whiteLabelSchema.safeParse(saved ?? fallback);
  return parsed.success ? parsed.data : fallback;
});

export async function saveWhiteLabelConfig(institutionId: string, input: unknown) {
  const parsed = whiteLabelSchema.parse(input);
  await prisma.setting.upsert({
    where: { institutionId_key: { institutionId, key: WHITE_LABEL_KEY } },
    update: { value: parsed },
    create: { institutionId, key: WHITE_LABEL_KEY, value: parsed }
  });
  return parsed;
}

export function colorToHslVariable(hex: string) {
  const value = hex.replace("#", "");
  const bigint = Number.parseInt(value.length === 3 ? value.split("").map((char) => char + char).join("") : value, 16);
  const r = ((bigint >> 16) & 255) / 255;
  const g = ((bigint >> 8) & 255) / 255;
  const b = (bigint & 255) / 255;
  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  let h = 0;
  let s = 0;
  const l = (max + min) / 2;
  if (max !== min) {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    if (max === r) h = (g - b) / d + (g < b ? 6 : 0);
    if (max === g) h = (b - r) / d + 2;
    if (max === b) h = (r - g) / d + 4;
    h /= 6;
  }
  return `${Math.round(h * 360)} ${Math.round(s * 100)}% ${Math.round(l * 100)}%`;
}
