"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { Activity, Bell, Bot, Check, Download, FileText, Globe2, Network, Search, Settings2, UsersRound } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { markCloudNotificationReadAction, saveCloudPreferencesAction } from "@/features/edux-cloud/actions";
import type { getEduXCloudData } from "@/services/edux-cloud-service";

type Data = Awaited<ReturnType<typeof getEduXCloudData>>;
type Tab = "overview" | "search" | "inbox" | "documents" | "memory" | "settings";
const tabs: Array<[Tab, string, typeof Globe2]> = [["overview", "Cloud home", Globe2], ["search", "Unified search", Search], ["inbox", "Inbox", Bell], ["documents", "Documents", FileText], ["memory", "AI memory", Bot], ["settings", "Settings", Settings2]];
const stamp = (date: Date) => new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(date));
const download = (name: string, rows: unknown[]) => { const blob = new Blob([JSON.stringify(rows, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${name}.json`; anchor.click(); URL.revokeObjectURL(url); };

export function EduXCloudWorkspace({ data }: { data: Data }) {
  const [tab, setTab] = useState<Tab>("overview"); const [query, setQuery] = useState(""); const [filter, setFilter] = useState("ALL");
  const terms = query.toLowerCase().trim();
  const search = useMemo(() => [
    ...data.recents.map((x) => ({ id: `recent-${x.id}`, source: x.type, title: x.title, detail: "Recently opened", link: x.link })),
    ...data.favorites.map((x) => ({ id: `favorite-${x.id}`, source: x.type, title: x.title, detail: "Saved workspace item", link: x.link })),
    ...data.documents.map((x) => ({ id: `document-${x.id}`, source: "Document", title: x.title, detail: x.description ?? `${x.type} resource`, link: x.fileUrl ?? x.externalUrl })),
    ...data.conversations.map((x) => ({ id: `memory-${x.id}`, source: "AI", title: x.title, detail: `${x.scope} conversation`, link: "/ai" })),
  ].filter((x) => (!terms || `${x.source} ${x.title} ${x.detail}`.toLowerCase().includes(terms)) && (filter === "ALL" || x.source === filter)), [data, terms, filter]);
  const settings = data.preferences.find((item) => item.key === "edux.cloud.settings")?.value as { theme?: string; language?: string; privacy?: string } | undefined;
  const body = tab === "overview" ? <Overview data={data} setTab={setTab} /> : tab === "search" ? <SearchPanel data={data} query={query} setQuery={setQuery} filter={filter} setFilter={setFilter} rows={search} /> : tab === "inbox" ? <Inbox data={data} /> : tab === "documents" ? <Documents data={data} query={query} setQuery={setQuery} /> : tab === "memory" ? <Memory data={data} /> : <Settings data={data} settings={settings} />;
  return <main className="space-y-6"><section className="relative overflow-hidden rounded-[2rem] border border-sky-100 bg-[linear-gradient(120deg,#ecfeff_0%,#eff6ff_47%,#ffffff_100%)] p-6 shadow-soft sm:p-8"><div className="absolute -right-16 -top-20 h-56 w-56 rounded-full bg-teal-200/35 blur-3xl"/><Badge>EduX Cloud · shared foundation</Badge><div className="relative mt-4 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">One person. One institution. Connected context.</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-muted-foreground sm:text-base">A protected, read-only integration layer over your existing platform identity, AI, documents, activity, and notification records.</p></div><div className="rounded-2xl border border-teal-100 bg-white/80 px-4 py-3 text-sm"><span className="block font-semibold">{data.user?.institution?.name ?? "Personal workspace"}</span><span className="text-muted-foreground">{data.user?.roles.map((x) => x.role.name).join(" · ") || "No assigned role"}</span></div></div></section><nav className="flex gap-2 overflow-x-auto pb-1" aria-label="EduX Cloud sections">{tabs.map(([id, label, Icon]) => <button key={id} onClick={() => setTab(id)} className={`inline-flex shrink-0 items-center gap-2 rounded-xl px-3 py-2 text-sm font-medium transition ${tab === id ? "bg-slate-900 text-white" : "border bg-background hover:bg-sky-50"}`}><Icon className="h-4 w-4"/>{label}</button>)}</nav>{body}</main>;
}

function Overview({ data, setTab }: { data: Data; setTab: (tab: Tab) => void }) { const unread = data.notifications.filter((x) => x.status === "UNREAD").length; return <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Identity" value={data.user?.name ?? "Unavailable"} note={data.user?.email ?? "No profile record"}/><Metric label="Institution" value={data.user?.institution?.name ?? "Not assigned"} note={`${data.peers.length} active relationship signals`}/><Metric label="Unread alerts" value={String(unread)} note="Shared notification timeline"/><Metric label="AI context" value={String(data.conversations.length)} note={`${data.analytics.tokenCount.toLocaleString()} recorded tokens`}/></div><div className="grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><Card className="p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="font-semibold">Cross-product timeline</h2><p className="mt-1 text-sm text-muted-foreground">Your latest notifications, activity, and AI context.</p></div><Button variant="secondary" onClick={() => setTab("inbox")}>Open inbox</Button></div><Timeline rows={data.timeline.slice(0, 7)} empty="No shared activity has been recorded yet."/></Card><Card className="p-5"><h2 className="font-semibold">Knowledge relationships</h2><p className="mt-1 text-sm text-muted-foreground">Evidence available through existing membership and role records.</p><div className="mt-4 space-y-3"><div className="rounded-xl bg-sky-50 p-3 text-sm"><strong>{data.user?.name ?? "You"}</strong><span className="block text-muted-foreground">↔ {data.user?.institution?.name ?? "Personal workspace"} · institution membership</span></div>{data.peers.slice(0, 4).map((peer) => <div className="rounded-xl border p-3 text-sm" key={peer.id}><strong>{peer.name}</strong><span className="block text-muted-foreground">{peer.userType ?? (peer.roles.map((role) => role.role.name).join(", ") || "Member")}</span></div>)}{!data.peers.length && <p className="rounded-xl border border-dashed p-3 text-sm text-muted-foreground">{data.readiness.graph}</p>}</div></Card></div><div className="grid gap-4 lg:grid-cols-3"><Shortcut title="Find everything" description="Search your recent, saved, document, and AI context evidence." icon={Search} onClick={() => setTab("search")}/><Shortcut title="Shared documents" description="Resources currently available through existing content records." icon={FileText} onClick={() => setTab("documents")}/><Shortcut title="AI memory index" description="Conversation titles and scope, without exposing message bodies." icon={Bot} onClick={() => setTab("memory")}/></div></div>; }
function SearchPanel({ data, query, setQuery, filter, setFilter, rows }: { data: Data; query: string; setQuery: (v: string) => void; filter: string; setFilter: (v: string) => void; rows: Array<{ id: string; source: string; title: string; detail: string; link: string | null }> }) { const sources = [...new Set(["ALL", ...data.recents.map((x) => x.type), ...data.favorites.map((x) => x.type), "Document", "AI"])]; return <div className="space-y-4"><Card className="p-5"><div className="grid gap-3 md:grid-cols-[1fr_180px_auto]"><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search resources, saved work, recent items, and AI conversations"/><Select value={filter} onChange={(event) => setFilter(event.target.value)}>{sources.map((source) => <option key={source}>{source}</option>)}</Select><Button variant="secondary" onClick={() => download("edux-cloud-search", rows)}><Download className="mr-2 h-4 w-4"/>Export</Button></div><p className="mt-3 text-xs text-muted-foreground">Search is scoped to data you can already access. Results link back to their source workflow where available.</p></Card>{rows.length ? <div className="space-y-2">{rows.map((row) => <Card className="p-4" key={row.id}><div className="flex items-start justify-between gap-3"><div><Badge>{row.source}</Badge><h2 className="mt-2 font-semibold">{row.title}</h2><p className="mt-1 text-sm text-muted-foreground">{row.detail}</p></div>{row.link ? <Link className="text-sm font-semibold text-teal-700" href={row.link}>Open</Link> : null}</div></Card>)}</div> : <EmptyState icon={<Search/>} title="No shared results" description="Try a broader term or switch the result source."/>}</div>; }
function Inbox({ data }: { data: Data }) { const [state, setState] = useState("ALL"); const rows = data.notifications.filter((x) => state === "ALL" || x.status === state); return <div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><Select className="w-44" value={state} onChange={(event) => setState(event.target.value)}><option>ALL</option><option>UNREAD</option><option>READ</option><option>ARCHIVED</option></Select><Button variant="secondary" onClick={() => download("edux-cloud-notifications", rows)}>Export timeline</Button></div>{rows.length ? rows.map((row) => <Card className={`p-4 ${row.status === "UNREAD" ? "border-teal-200 bg-teal-50/50" : ""}`} key={row.id}><div className="flex flex-wrap items-start justify-between gap-4"><div><Badge>{row.status}</Badge><h2 className="mt-2 font-semibold">{row.title}</h2>{row.body && <p className="mt-1 text-sm text-muted-foreground">{row.body}</p>}<p className="mt-2 text-xs text-muted-foreground">{stamp(row.createdAt)}</p></div><div className="flex items-center gap-2">{row.status === "UNREAD" && <form action={markCloudNotificationReadAction}><input type="hidden" name="id" value={row.id}/><Button className="h-9 px-3 text-sm" variant="secondary"><Check className="mr-1 h-3 w-3"/>Mark read</Button></form>}{row.link && <Link href={row.link} className="text-sm font-semibold text-teal-700">Open</Link>}</div></div></Card>) : <EmptyState icon={<Bell/>} title="No notifications in this view" description="There are no matching platform or institution notifications."/>}</div>; }
function Documents({ data, query, setQuery }: { data: Data; query: string; setQuery: (v: string) => void }) { const rows = data.documents.filter((x) => `${x.title} ${x.description ?? ""} ${x.type}`.toLowerCase().includes(query.toLowerCase())); return <div className="space-y-4"><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Filter shared resources and documents"/>{rows.length ? <div className="grid gap-3 md:grid-cols-2">{rows.map((row) => <Card className="p-5" key={row.id}><Badge>{row.type}</Badge><h2 className="mt-3 font-semibold">{row.title}</h2><p className="mt-1 min-h-10 text-sm text-muted-foreground">{row.description ?? "No description recorded."}</p><p className="mt-3 text-xs text-muted-foreground">{row.mimeType ?? "File type unavailable"} · {(row.sizeBytes / 1024).toFixed(1)} KB</p>{(row.fileUrl ?? row.externalUrl) && <Link className="mt-4 inline-block text-sm font-semibold text-teal-700" href={row.fileUrl ?? row.externalUrl ?? "#"}>Open source</Link>}</Card>)}</div> : <EmptyState icon={<FileText/>} title="No shared documents available" description={data.readiness.files}/>}</div>; }
function Memory({ data }: { data: Data }) { return <div className="space-y-4"><Card className="p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="font-semibold">AI memory index</h2><p className="mt-1 text-sm text-muted-foreground">Conversation metadata is shared as context. Messages, prompts, and generated content remain inside their original AI workflow.</p></div><Button variant="secondary" onClick={() => download("edux-cloud-ai-memory", data.conversations)}>Export index</Button></div></Card>{data.conversations.length ? <div className="grid gap-3 md:grid-cols-2">{data.conversations.map((row) => <Card className="p-5" key={row.id}><Badge>{row.scope}</Badge><h2 className="mt-3 font-semibold">{row.title}</h2><p className="mt-1 text-sm text-muted-foreground">{row.model ?? "Platform default model"}</p><p className="mt-3 text-xs text-muted-foreground">Updated {stamp(row.updatedAt)}</p><Link href="/ai" className="mt-4 inline-block text-sm font-semibold text-teal-700">Open AI workspace</Link></Card>)}</div> : <EmptyState icon={<Bot/>} title="No AI memory is recorded" description="Start an AI conversation in an existing product workspace to build a personal context index."/>}<Card className="p-5"><h2 className="font-semibold">AI usage evidence</h2><div className="mt-4 grid gap-3 sm:grid-cols-3"><Metric label="Recorded requests" value={String(data.analytics.requestCount)}/><Metric label="Recorded tokens" value={data.analytics.tokenCount.toLocaleString()}/><Metric label="Features" value={String(data.analytics.byFeature.length)}/></div></Card></div>; }
function Settings({ data, settings }: { data: Data; settings?: { theme?: string; language?: string; privacy?: string } }) { return <div className="grid gap-4 lg:grid-cols-2"><Card className="p-5"><h2 className="font-semibold">Cloud preferences</h2><p className="mt-1 text-sm text-muted-foreground">Stored in your existing shared preference record; product-specific settings remain in their own workspaces.</p><form action={saveCloudPreferencesAction} className="mt-5 space-y-4"><label className="block text-sm font-medium">Appearance<Select className="mt-2" name="theme" defaultValue={settings?.theme ?? "system"}><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></Select></label><label className="block text-sm font-medium">Language<Select className="mt-2" name="language" defaultValue={settings?.language ?? "English"}><option>English</option><option>Hindi</option><option>Marathi</option><option>Tamil</option></Select></label><label className="block text-sm font-medium">Profile visibility<Select className="mt-2" name="privacy" defaultValue={settings?.privacy ?? "institution"}><option value="institution">Institution members</option><option value="private">Private</option><option value="professional">Professional network</option></Select></label><Button type="submit">Save preferences</Button></form></Card><Card className="p-5"><h2 className="font-semibold">Identity & security boundary</h2><dl className="mt-4 space-y-4 text-sm"><div><dt className="font-medium">Global identity</dt><dd className="text-muted-foreground">{data.user?.email ?? "No identity record"}</dd></div><div><dt className="font-medium">Institution role mapping</dt><dd className="text-muted-foreground">{data.user?.roles.map((x) => x.role.name).join(", ") || "No role mapping"}</dd></div><div><dt className="font-medium">Devices and sessions</dt><dd className="text-muted-foreground">{data.readiness.devices}</dd></div></dl></Card></div>; }
function Timeline({ rows, empty }: { rows: Data["timeline"]; empty: string }) { return <div className="mt-4 space-y-3">{rows.length ? rows.map((row) => <div className="border-l-2 border-teal-200 pl-4" key={row.id}><div className="flex flex-wrap items-center gap-2"><Badge>{row.product}</Badge><strong className="text-sm">{row.title}</strong></div><p className="mt-1 text-sm text-muted-foreground">{row.detail}</p><p className="mt-1 text-xs text-muted-foreground">{stamp(row.at)}</p></div>) : <p className="rounded-xl border border-dashed p-4 text-sm text-muted-foreground">{empty}</p>}</div>; }
function Metric({ label, value, note }: { label: string; value: string; note?: string }) { return <Card className="p-4"><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-2 truncate text-xl font-semibold">{value}</p>{note && <p className="mt-1 text-xs text-muted-foreground">{note}</p>}</Card>; }
function Shortcut({ title, description, icon: Icon, onClick }: { title: string; description: string; icon: typeof Search; onClick: () => void }) { return <button onClick={onClick} className="text-left"><Card className="h-full p-5 transition hover:-translate-y-0.5 hover:border-teal-300"><Icon className="h-5 w-5 text-teal-700"/><h2 className="mt-3 font-semibold">{title}</h2><p className="mt-1 text-sm text-muted-foreground">{description}</p></Card></button>; }
