"use server";

import { revalidatePath } from "next/cache";
import { z } from "zod";

import { auth } from "@/auth";
import { prisma } from "@/lib/db";
import { defaultWhiteLabelConfig, saveWhiteLabelConfig, whiteLabelSchema } from "@/services/white-label-service";

const institutionSchema = z.object({
  name: z.string().min(2),
  logoUrl: z.string().url().optional().or(z.literal("")),
  primaryColor: z.string().min(4),
  secondaryColor: z.string().min(4),
  address: z.string().optional(),
  phone: z.string().optional(),
  email: z.string().email().optional().or(z.literal("")),
  website: z.string().url().optional().or(z.literal("")),
  timezone: z.string().min(2),
  academicYear: z.string().optional(),
  currency: z.string().min(2)
});

export async function saveInstitutionSettings(_: string | undefined, formData: FormData) {
  const session = await auth();
  const parsed = institutionSchema.safeParse(Object.fromEntries(formData));

  if (!session?.user.institutionId) return "Institution is not available for this account.";
  if (!parsed.success) return "Please check the settings and try again.";

  await prisma.institution.update({
    where: { id: session.user.institutionId },
    data: {
      ...parsed.data,
      logoUrl: parsed.data.logoUrl || null,
      email: parsed.data.email || null,
      website: parsed.data.website || null
    }
  });

  const whiteLabel = whiteLabelSchema.safeParse({
    ...defaultWhiteLabelConfig(parsed.data.name),
    institutionName: parsed.data.name,
    logoUrl: parsed.data.logoUrl || "",
    primaryColor: parsed.data.primaryColor,
    secondaryColor: parsed.data.secondaryColor,
    accentColor: String(formData.get("accentColor") || "#0f766e"),
    faviconUrl: String(formData.get("faviconUrl") || ""),
    theme: String(formData.get("theme") || "light"),
    contactEmail: parsed.data.email || "",
    contactPhone: parsed.data.phone || "",
    applicationTitle: String(formData.get("applicationTitle") || parsed.data.name),
    browserTitle: String(formData.get("browserTitle") || `${parsed.data.name} | TeachX`),
    footerText: String(formData.get("footerText") || "Powered by TeachX"),
    emailTemplate: String(formData.get("emailTemplate") || "Simple branded email"),
    certificateTemplate: String(formData.get("certificateTemplate") || "Standard certificate"),
    invoiceTemplate: String(formData.get("invoiceTemplate") || "Standard invoice"),
    pdfBranding: {
      showLogo: formData.get("pdfShowLogo") === "on",
      showAddress: formData.get("pdfShowAddress") === "on",
      footerNote: String(formData.get("pdfFooterNote") || "Generated by TeachX")
    }
  });

  if (!whiteLabel.success) return "Institution saved, but branding details need review.";
  await saveWhiteLabelConfig(session.user.institutionId, whiteLabel.data);

  revalidatePath("/settings/institution");
  return "Settings saved.";
}
