"use server";
import type{Prisma}from"@prisma/client";import{revalidatePath}from"next/cache";import{auth}from"@/auth";import{prisma}from"@/lib/db";import{MARKETPLACE_SETTINGS_KEY,requireMarketplaceStudent}from"@/services/student-marketplace-service";import{acquireMarketplaceListing,addMarketplaceCartItem,createMarketplaceCartOrder,removeMarketplaceCartItem}from"@/services/marketplace-commerce-service";import{reportMarketplaceReview,saveMarketplaceReview,toggleMarketplaceHelpfulVote}from"@/services/marketplace-review-service";
async function student(){const s=await auth();if(!s?.user.id||!s.user.institutionId||!s.user.roles.includes("STUDENT"))throw new Error("Student access required.");await requireMarketplaceStudent(s.user.id,s.user.institutionId);return{userId:s.user.id,institutionId:s.user.institutionId}}
const value=(f:FormData,k:string,max=200)=>String(f.get(k)??"").trim().slice(0,max);
export async function acquireListingAction(_:string|undefined,f:FormData){try{const s=await student(),r=await acquireMarketplaceListing({...s,listingId:value(f,"listingId",100)});revalidatePath("/student/marketplace");return r.state==="FULFILLED"?"Resource acquired and added to your library.":r.message}catch(e){return e instanceof Error?e.message:"Acquisition failed."}}
export async function addCartAction(_:string|undefined,f:FormData){try{const s=await student(),r=await addMarketplaceCartItem({...s,listingId:value(f,"listingId",100)});revalidatePath("/student/marketplace");return r.status}catch(e){return e instanceof Error?e.message:"Cart update failed."}}
export async function removeCartAction(f:FormData){const s=await student();await removeMarketplaceCartItem({...s,listingId:value(f,"listingId",100)});revalidatePath("/student/marketplace")}
export async function checkoutCartAction(_:string|undefined){try{const s=await student(),r=await createMarketplaceCartOrder(s);revalidatePath("/student/marketplace");return r.message}catch(e){return e instanceof Error?e.message:"Checkout unavailable."}}
export async function toggleBookmarkAction(f:FormData){const s=await student(),listingId=value(f,"listingId",100),listing=await prisma.marketplaceListing.findFirst({where:{id:listingId,status:"ACTIVE",contentItem:{institutionId:s.institutionId,status:"PUBLISHED",visibility:"PUBLIC"}},select:{contentItem:{select:{id:true,title:true}}}});if(!listing)return;const key={userId_type_entityId:{userId:s.userId,type:"student-marketplace-bookmark",entityId:listing.contentItem.id}},old=await prisma.favoriteItem.findUnique({where:key});if(old)await prisma.favoriteItem.delete({where:{id:old.id}});else await prisma.favoriteItem.create({data:{userId:s.userId,type:"student-marketplace-bookmark",entityId:listing.contentItem.id,title:listing.contentItem.title,link:`/student/marketplace?product=${listingId}`}});revalidatePath("/student/marketplace")}
export async function saveWishlistAction(_:string|undefined,f:FormData){try{const s=await student(),listingId=value(f,"listingId",100),name=value(f,"collection",60)||"Saved learning",listing=await prisma.marketplaceListing.findFirst({where:{id:listingId,status:"ACTIVE",contentItem:{institutionId:s.institutionId,status:"PUBLISHED",visibility:"PUBLIC"}},select:{id:true,price:true,previousPrice:true,contentItemId:true}});if(!listing)throw new Error("Listing unavailable.");const count=await prisma.marketplaceWishlistCollection.count({where:{userId:s.userId}});let collection=await prisma.marketplaceWishlistCollection.findUnique({where:{userId_name:{userId:s.userId,name}}});if(!collection&&count>=10)throw new Error("Up to ten wishlist collections are supported.");collection??=await prisma.marketplaceWishlistCollection.create({data:{userId:s.userId,name}});await prisma.marketplaceWishlistItem.upsert({where:{userId_listingId:{userId:s.userId,listingId}},create:{userId:s.userId,collectionId:collection.id,listingId,contentItemId:listing.contentItemId,availabilityAlert:false,priceAlert:false,priceAtSave:listing.price},update:{collectionId:collection.id,availabilityAlert:false,priceAlert:false,priceAtSave:listing.price}});revalidatePath("/student/marketplace");return"Saved to wishlist. Automated price and availability alerts are unavailable."}catch(e){return e instanceof Error?e.message:"Wishlist update failed."}}
export async function removeWishlistAction(f:FormData){const s=await student();await prisma.marketplaceWishlistItem.deleteMany({where:{userId:s.userId,listingId:value(f,"listingId",100),listing:{contentItem:{institutionId:s.institutionId}}}});revalidatePath("/student/marketplace")}
export async function saveMarketplaceSearchAction(f:FormData){const s=await student(),query=value(f,"query",120);if(query.length<2)return;const duplicate=await prisma.savedSearch.findFirst({where:{userId:s.userId,scope:"student-marketplace",query:{equals:query,mode:"insensitive"}}});if(duplicate)return;const saved=await prisma.savedSearch.findMany({where:{userId:s.userId,scope:"student-marketplace"},select:{id:true},orderBy:{createdAt:"asc"}});if(saved.length>=10)await prisma.savedSearch.deleteMany({where:{id:{in:saved.slice(0,saved.length-9).map(x=>x.id)}}});await prisma.savedSearch.create({data:{userId:s.userId,name:query.slice(0,60),query,scope:"student-marketplace"}});revalidatePath("/student/marketplace")}
export async function trackMarketplaceViewAction(f:FormData){const s=await student(),listingId=value(f,"listingId",100),listing=await prisma.marketplaceListing.findFirst({where:{id:listingId,status:"ACTIVE",contentItem:{institutionId:s.institutionId,status:"PUBLISHED",visibility:"PUBLIC"}},select:{contentItem:{select:{id:true,title:true}}}});if(!listing)return;await prisma.recentItem.upsert({where:{userId_type_entityId:{userId:s.userId,type:"student-marketplace",entityId:listing.contentItem.id}},create:{userId:s.userId,type:"student-marketplace",entityId:listing.contentItem.id,title:listing.contentItem.title,link:`/student/marketplace?product=${listingId}`},update:{title:listing.contentItem.title,viewedAt:new Date()}});revalidatePath("/student/marketplace")}
export async function saveReviewAction(_:string|undefined,f:FormData){try{const s=await student();await saveMarketplaceReview({...s,listingId:value(f,"listingId",100),rating:Number(value(f,"rating",2)),title:value(f,"title",100),body:value(f,"body",1500)});revalidatePath("/student/marketplace");return"Verified review submitted for moderation."}catch(e){return e instanceof Error?e.message:"Review unavailable."}}
export async function helpfulReviewAction(f:FormData){const s=await student();await toggleMarketplaceHelpfulVote({...s,reviewId:value(f,"reviewId",100)});revalidatePath("/student/marketplace")}
export async function reportReviewAction(_:string|undefined,f:FormData){try{const s=await student(),r=await reportMarketplaceReview({...s,reviewId:value(f,"reviewId",100),reason:value(f,"reason",300)});return r.status}catch(e){return e instanceof Error?e.message:"Report unavailable."}}
export async function saveMarketplaceSettingsAction(f:FormData){const s=await student(),settings={language:value(f,"language",30)||"English",purchaseNotifications:f.get("purchaseNotifications")==="on",downloadNotifications:f.get("downloadNotifications")==="on",recommendations:f.get("recommendations")==="on"};await prisma.userPreference.upsert({where:{userId_key:{userId:s.userId,key:MARKETPLACE_SETTINGS_KEY}},create:{userId:s.userId,key:MARKETPLACE_SETTINGS_KEY,value:settings as Prisma.InputJsonValue},update:{value:settings as Prisma.InputJsonValue}});revalidatePath("/student/marketplace")}