import { auth } from "@/auth";
import { getStudentLearningAnalytics,type AnalyticsPeriod } from "@/services/student-learning-analytics-service";
const cell=(value:unknown)=>{let s=String(value??"");if(/^[=+\-@]/.test(s))s=`'${s}`;return `"${s.replaceAll('"','""')}"`};
export async function GET(request:Request){
 const session=await auth();if(!session?.user.id||!session.user.roles.includes("STUDENT"))return new Response("Student access required",{status:403});
 const url=new URL(request.url),p=url.searchParams.get("period"),period:AnalyticsPeriod=p==="7"||p==="90"||p==="all"?p:"30",format=url.searchParams.get("format")==="json"?"json":"csv";
 const data=await getStudentLearningAnalytics(session.user.id,period),requestedSubject=url.searchParams.get("subject")??"all",subject=requestedSubject==="all"||data.subjects.some(x=>x.name===requestedSubject)?requestedSubject:"all",search=(url.searchParams.get("search")??"").slice(0,100).toLowerCase(),sort=["evidence","accuracy","name"].includes(url.searchParams.get("sort")??"")?url.searchParams.get("sort")!:"evidence",matches=(...values:(string|undefined)[])=>values.join(" ").toLowerCase().includes(search),areaFilter=(x:{name:string;parent?:string})=>(subject==="all"||x.name===subject||x.parent===subject)&&matches(x.name,x.parent),sortAreas=<T extends {name:string;accuracy:number|null;objectiveQuestions:number}>(xs:T[])=>xs.sort((a,b)=>sort==="name"?a.name.localeCompare(b.name):sort==="accuracy"?(b.accuracy??-1)-(a.accuracy??-1):b.objectiveQuestions-a.objectiveQuestions),safe={reports:["academic","practice","ai-learning","progress","study-habit"].filter(x=>matches(x)),filters:{period,subject,search,sort},generatedAt:data.generatedAt,coverageStart:data.coverageStart,scopes:{overall:"All subjects",habits:"All subjects",goals:"Global",aiActivity:"Global metadata",achievements:"Global",subjectFilter:"Applies to hierarchy, concepts and attributed sessions"},overall:data.overall,subjects:sortAreas(data.subjects.filter(areaFilter)),chapters:sortAreas(data.chapters.filter(areaFilter)),topics:sortAreas(data.topics.filter(areaFilter)),trends:data.trends,concepts:data.concepts.filter(x=>(subject==="all"||x.subject===subject)&&matches(x.name,x.subject)),sessions:data.sessions.filter(x=>(subject==="all"||x.subject?.includes(subject))&&matches(x.title,x.type,x.subject)),goals:data.settings.trackGoals?data.goals.filter(x=>matches(x.title,x.type,x.status)):[],goalHistory:data.settings.trackGoals?data.goalHistory.filter(x=>matches(x.title,x.type,x.status)):[],achievements:data.settings.includeAchievements?data.achievements.filter(x=>matches(x.title,x.source)):[],achievementGroups:data.settings.includeAchievements?data.achievementGroups:undefined,aiActivity:data.settings.includeAIActivity?data.ai:undefined,habitSummary:data.habitSummary,insights:data.settings.aiRecommendations?data.insights.filter(x=>matches(x.title,x.body,x.action)):[],definitions:data.definitions};
 const name=`learnx-analytics-${period}-days.${format}`;
 if(format==="json")return new Response(JSON.stringify(safe,null,2),{headers:{"Content-Type":"application/json; charset=utf-8","Content-Disposition":`attachment; filename="${name}"`,"Cache-Control":"private, no-store","X-Content-Type-Options":"nosniff"}});
 const rows:(unknown[])[]=[["section","item","metric","value","coverage_or_method"]];for(const [metric,value] of Object.entries(safe.overall))rows.push(["overall","All subjects",metric,value,safe.overall.scoreMethod]);for(const area of safe.subjects)for(const [metric,value] of [["score",area.score],["accuracy",area.accuracy],["completion_proxy",area.completion],["objective_questions",area.objectiveQuestions],["assessments",area.assessments],["study_minutes",area.studyMinutes]])rows.push(["subject",area.name,metric,value,`${area.objectiveQuestions} objective questions`]);for(const area of safe.chapters)for(const [metric,value] of [["score",area.score],["accuracy",area.accuracy],["objective_questions",area.objectiveQuestions]])rows.push(["chapter",`${area.parent} / ${area.name}`,metric,value,`${area.assessments} assessments`]);for(const area of safe.topics)for(const [metric,value] of [["score",area.score],["accuracy",area.accuracy],["objective_questions",area.objectiveQuestions]])rows.push(["topic",`${area.parent} / ${area.name}`,metric,value,`${area.assessments} assessments`]);for(const point of safe.trends)for(const [metric,value] of [["score",point.score],["accuracy",point.accuracy],["speed_seconds",point.speedSeconds],["study_minutes",point.minutes]])rows.push(["trend",point.date,metric,value,`${point.assessments} completed assessments`]);for(const x of safe.concepts)rows.push(["incorrect_concept",`${x.subject} / ${x.name}`,"incorrect_skipped_accuracy",`${x.incorrect} / ${x.skipped} / ${x.accuracy??"unavailable"}`,"Objective answers only"]);for(const x of safe.sessions)rows.push(["session",x.title,"date_type_minutes_score",`${x.date} / ${x.type} / ${x.minutes} / ${x.score??"unavailable"}`,x.subject??"All/unattributed"]);for(const x of safe.goals)rows.push(["goal",x.title,"type_status_progress",`${x.type} / ${x.status} / ${x.progress}%`,x.source]);for(const x of safe.goalHistory)rows.push(["goal_history",x.title,"date_type_status",`${x.date??"unavailable"} / ${x.type} / ${x.status}`,"Persisted history"]);for(const x of safe.achievements)rows.push(["achievement",x.title,"date",x.date??"unavailable",x.source]);if(safe.aiActivity)for(const [metric,value] of Object.entries(safe.aiActivity))rows.push(["ai_activity","Global metadata",metric,Array.isArray(value)?value.join("; "):value,"Message bodies and costs excluded"]);for(const [metric,value] of Object.entries(safe.habitSummary))rows.push(["study_habit","All subjects",metric,value,"Recognized engagement only"]);for(const report of safe.reports)rows.push(["report",report,"included",true,"Filtered aggregate report"]);for(const definition of safe.definitions)rows.push(["definition","methodology","definition",definition,"Metric semantics"]);
 return new Response(rows.map(r=>r.map(cell).join(",")).join("\r\n"),{headers:{"Content-Type":"text/csv; charset=utf-8","Content-Disposition":`attachment; filename="${name}"`,"Cache-Control":"private, no-store","X-Content-Type-Options":"nosniff"}});
}
