import Image from "next/image";
import Link from "next/link";
import { Building2, CircleUserRound, Goal, GraduationCap, HeartHandshake, Settings, Sparkles, Trash2 } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import { Input } from "@/components/ui/input";
import {
  cancelInstitutionRequestAction, cancelParentInvitationAction, deleteGoalAction, inviteParentAction, removeParentAction,
  requestInstitutionAction, saveGoalAction, savePersonalizationAction, saveStudentProfileAction, saveStudentSettingsAction, updateGoalAction
} from "@/features/student-foundation/actions";
import { InstitutionSearch, ProgressiveOnboarding } from "@/features/student-foundation/components/foundation-interactions";
import type { getStudentFoundation } from "@/services/student-foundation-service";

type Data = NonNullable<Awaited<ReturnType<typeof getStudentFoundation>>>;
type Module = "onboarding" | "profile" | "goals" | "connections" | "personalization" | "settings";
const tabs = [["onboarding","Learning map",Sparkles],["profile","My identity",CircleUserRound],["goals","Goals",Goal],["connections","Connections",HeartHandshake],["personalization","AI preferences",GraduationCap],["settings","Settings",Settings]] as const;
const field="space-y-2 text-sm font-medium";
const select="h-12 w-full rounded-lg border border-border bg-surface px-4 text-base outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100";

export function StudentFoundationPage({module,data}:{module:Module;data:Data}) {
  return <div className="space-y-6">
    <section className="rounded-[2rem] border border-indigo-100 bg-gradient-to-br from-indigo-50 via-white to-cyan-50 p-6 shadow-soft sm:p-8"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><Badge className="border-indigo-100 bg-indigo-50 text-indigo-700">LearnX Guru · Personal learning constellation</Badge><h1 className="mt-4 text-3xl font-semibold tracking-tight sm:text-4xl">{tabs.find(([key])=>key===module)?.[1]}</h1><p className="mt-2 max-w-2xl leading-7 text-muted-foreground">Shape the identity and preferences your AI companion uses in every study session.</p></div><div className="flex items-center gap-3 rounded-2xl border border-white bg-white/80 px-4 py-3 shadow-sm"><span className={`h-3 w-3 rounded-full ${data.onboardingComplete?"bg-emerald-500":"bg-amber-400"}`}/><div><p className="text-sm font-semibold">{data.onboardingComplete?"Learning map ready":"Setup in progress"}</p><p className="text-xs text-muted-foreground">{data.user.email}</p></div></div></div></section>
    <nav className="flex gap-2 overflow-x-auto pb-1" aria-label="LearnX identity navigation">{tabs.map(([key,label,Icon])=><Link className={`flex shrink-0 items-center gap-2 rounded-xl border px-4 py-3 text-sm font-medium ${key===module?"border-indigo-200 bg-indigo-50 text-indigo-700":"border-border bg-surface text-muted-foreground hover:bg-muted"}`} href={`/student/${key}`} key={key}><Icon className="h-4 w-4"/>{label}</Link>)}</nav>
    {module==="onboarding"&&<ProgressiveOnboarding complete={data.onboardingComplete} profile={data.foundation.profile}/>}
    {module==="profile"&&<Profile data={data}/>}
    {module==="goals"&&<Goals data={data}/>}
    {module==="connections"&&<Connections data={data}/>}
    {module==="personalization"&&<Personalization data={data}/>}
    {module==="settings"&&<StudentSettings data={data}/>}
  </div>;
}

function Profile({data}:{data:Data}) {
  const p=data.foundation.profile;
  return <Card className="p-6 shadow-soft sm:p-8"><div className="flex items-center gap-4">{data.baseProfile?.avatarUrl?<Image alt={`${data.user.name} profile`} className="h-16 w-16 rounded-2xl object-cover" height={64} src={data.baseProfile.avatarUrl} unoptimized width={64}/>:<div className="grid h-16 w-16 place-items-center rounded-2xl bg-gradient-to-br from-indigo-500 to-cyan-500 text-xl font-semibold text-white">{data.user.name.slice(0,2).toUpperCase()}</div>}<div><h2 className="text-2xl font-semibold">{data.user.name}</h2><p className="text-muted-foreground">{s(p.grade)||"Add your grade"} · {s(p.board)||"Add your board"}</p></div></div><form action={saveStudentProfileAction} className="mt-8 grid gap-5 md:grid-cols-2"><Field label="Full name" name="name" defaultValue={data.user.name} required/><Field label="Profile photo URL" name="avatarUrl" defaultValue={data.baseProfile?.avatarUrl??""} placeholder="https://example.com/photo.jpg"/><Field label="Phone" name="phone" defaultValue={data.baseProfile?.phone??""}/><Field label="Date of birth" name="dateOfBirth" defaultValue={s(p.dateOfBirth)} type="date"/><Field label="Grade" name="grade" defaultValue={s(p.grade)}/><Field label="School" name="school" defaultValue={s(p.school)}/><Field label="Board" name="board" defaultValue={s(p.board)}/><Field label="Language" name="language" defaultValue={s(p.language)}/><Field label="Academic interests" name="academicInterests" defaultValue={a(p.academicInterests)||data.studentProfile?.interests.join(", ")}/><Field label="Career goal" name="careerGoal" defaultValue={s(p.careerGoal)||data.studentProfile?.learningGoal||""}/><Field label="Learning style" name="learningStyle" defaultValue={s(p.learningStyle)}/><Field label="Parent information" name="parentInformation" defaultValue={s(p.parentInformation)}/><Button className="md:col-span-2 md:w-fit">Save profile</Button></form></Card>;
}

function Goals({data}:{data:Data}) {
  return <div className="grid gap-6 lg:grid-cols-[340px_1fr]"><Card className="h-fit p-6 shadow-soft"><h2 className="text-xl font-semibold">Create a goal</h2><form action={saveGoalAction} className="mt-5 space-y-4"><Select label="Goal type" name="type" options={["Short term","Long term","Weekly","Monthly","Exam","Personal"]}/><Field label="What will you achieve?" name="title" required/><Field label="Target date" name="targetDate" type="date"/><Button className="w-full">Add goal</Button></form></Card><section className="space-y-3"><h2 className="text-xl font-semibold">Your learning goals</h2>{data.foundation.goals.length?data.foundation.goals.map(goal=><Card className={`p-5 shadow-sm ${goal.completed?"border-emerald-200 bg-emerald-50/40":""}`} key={goal.id}><form action={updateGoalAction} className="grid gap-3 md:grid-cols-[140px_1fr_160px_auto]"><input name="id" type="hidden" value={goal.id}/><select className={select} defaultValue={goal.type} name="type">{["Short term","Long term","Weekly","Monthly","Exam","Personal"].map(x=><option key={x}>{x}</option>)}</select><Input defaultValue={goal.title} name="title"/><Input defaultValue={goal.targetDate} name="targetDate" type="date"/><Button variant="secondary">Save</Button></form><div className="mt-3 flex justify-between"><form action={updateGoalAction}><input name="id" type="hidden" value={goal.id}/><input name="completed" type="hidden" value="true"/><Button variant="ghost">{goal.completed?"Mark active":"Mark complete"}</Button></form><form action={deleteGoalAction}><input name="id" type="hidden" value={goal.id}/><Button aria-label={`Delete ${goal.title}`} className="px-4" variant="ghost"><Trash2 className="h-4 w-4"/></Button></form></div></Card>):<EmptyState icon={<Goal className="h-5 w-5"/>} title="Set your first learning goal" description="Choose a weekly, monthly, exam, or personal milestone to guide your mission."/>}</section></div>;
}

function Connections({data}:{data:Data}) {
  const request=data.foundation.institutionRequest;
  return <div className="grid gap-6 lg:grid-cols-2"><Card className="p-6 shadow-soft"><HeartHandshake className="h-6 w-6 text-indigo-600"/><h2 className="mt-4 text-xl font-semibold">Parent connection</h2><p className="mt-2 text-sm text-muted-foreground">Invitations remain pending until the parent approves them.</p><form action={inviteParentAction} className="mt-5 grid gap-4"><Field label="Parent email" name="email" type="email" required/><Field label="Relationship" name="relation" placeholder="Mother, Father, Guardian"/><label className="flex items-center gap-3 text-sm"><input name="isPrimary" type="checkbox"/>Primary contact</label><Button>Send invitation</Button></form><div className="mt-6 space-y-3">{data.parentInvitations.map(invite=><ConnectionRow key={invite.id} name={invite.name} detail={`${invite.relation} · ${invite.email}`} pending><form action={cancelParentInvitationAction}><input name="id" type="hidden" value={invite.id}/><Button variant="ghost">Cancel</Button></form></ConnectionRow>)}{data.parents.map(parent=><ConnectionRow key={parent.id} name={parent.name} detail={`${parent.relation} · ${parent.email}`}><form action={removeParentAction}><input name="id" type="hidden" value={parent.id}/><Button className="px-3" variant="ghost"><Trash2 className="h-4 w-4"/></Button></form></ConnectionRow>)}</div></Card><Card className="p-6 shadow-soft"><Building2 className="h-6 w-6 text-cyan-600"/><h2 className="mt-4 text-xl font-semibold">Institution connection</h2>{data.institution?<StatusBox name={data.institution.name}/>:request?<div className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4"><Badge className="border-amber-200 bg-white text-amber-700">Pending approval</Badge><p className="mt-2 font-semibold">{request.institutionName}</p><p className="mt-1 text-sm text-muted-foreground">An institution administrator has been notified.</p><form action={cancelInstitutionRequestAction} className="mt-3"><Button variant="secondary">Cancel request</Button></form></div>:<form action={requestInstitutionAction}><InstitutionSearch institutions={data.institutions}/><Button className="mt-4">Request to join</Button></form>}</Card></div>;
}

function Personalization({data}:{data:Data}) {const p=data.foundation.personalization;return <Card className="p-6 shadow-soft sm:p-8"><h2 className="text-2xl font-semibold">How should your AI companion teach?</h2><p className="mt-2 text-muted-foreground">LearnX adjusts pace, examples, practice, and revision using these choices.</p><form action={savePersonalizationAction} className="mt-8 grid gap-5 md:grid-cols-2"><Field label="Favourite subjects" name="favoriteSubjects" defaultValue={a(p.favoriteSubjects)}/><Field label="Weak subjects" name="weakSubjects" defaultValue={a(p.weakSubjects)}/>{[["learningSpeed","Learning speed",["Gentle","Steady","Fast"]],["studyPattern","Study pattern",["Focused sprints","Deep sessions","Flexible"]],["preferredDifficulty","Preferred difficulty",["Supportive","Adaptive","Challenging"]],["preferredStudyTime","Preferred study time",["Morning","Afternoon","Evening","Night"]],["learningStyle","Learning style",["Visual","Reading and writing","Practice based","Discussion based","Mixed"]],["revisionFrequency","Revision frequency",["Daily","Twice weekly","Weekly","Before exams"]]].map(([name,label,options])=><Select defaultValue={s(p[name as string])} key={name as string} label={label as string} name={name as string} options={options as string[]}/>)}<Button className="md:col-span-2 md:w-fit">Save AI preferences</Button></form></Card>}

function StudentSettings({data}:{data:Data}) {const p=data.foundation.settings;return <Card className="p-6 shadow-soft sm:p-8"><h2 className="text-2xl font-semibold">Account settings</h2><div className="mt-4 rounded-xl border border-border bg-muted/40 p-4 text-sm"><p className="font-medium">{data.user.email}</p><p className="mt-1 text-muted-foreground">Email {data.user.emailVerified?"verified":"verification pending"} · Account {data.user.status.toLowerCase()}</p></div><form action={saveStudentSettingsAction} className="mt-7 grid gap-5 md:grid-cols-2">{[["appearance","Appearance",["System","Light","Dark"]],["language","Language",["English","Hindi","Malayalam","Tamil"]],["privacy","Privacy",["Private","Institution","Connections"]]].map(([name,label,options])=><Select defaultValue={s(p[name as string])} key={name as string} label={label as string} name={name as string} options={options as string[]}/>)}<div className="space-y-4 md:col-span-2">{[["notifications","Learning and account notifications"],["securityAlerts","Security alerts"]].map(([name,label])=><label className="flex items-center justify-between rounded-xl border border-border p-4" key={name}><span className="font-medium">{label}</span><input defaultChecked={Boolean(p[name])} name={name} type="checkbox"/></label>)}</div><Button className="md:col-span-2 md:w-fit">Save settings</Button></form><div className="mt-7 border-t border-border pt-6"><h3 className="font-semibold">Connected accounts</h3>{data.accounts.length?<div className="mt-3 space-y-2">{data.accounts.map(account=><div className="rounded-xl border border-border p-4 text-sm" key={account.id}><span className="font-medium capitalize">{account.provider}</span><span className="ml-2 text-muted-foreground">{account.type}</span></div>)}</div>:<p className="mt-2 text-sm text-muted-foreground">No external accounts are connected. You currently sign in with LearnX credentials.</p>}</div><div className="mt-6 border-t border-border pt-6"><Link className="text-sm font-medium text-indigo-700 hover:underline" href="/forgot-password">Reset or change password securely</Link></div></Card>}

function ConnectionRow({name,detail,pending=false,children}:{name:string;detail:string;pending?:boolean;children:React.ReactNode}){return <div className={`flex items-center justify-between rounded-xl border p-4 ${pending?"border-amber-200 bg-amber-50":"border-emerald-200 bg-emerald-50"}`}><div><Badge className={pending?"border-amber-200 bg-white text-amber-700":"border-emerald-200 bg-white text-emerald-700"}>{pending?"Pending approval":"Approved"}</Badge><p className="mt-2 font-medium">{name}</p><p className="text-sm text-muted-foreground">{detail}</p></div>{children}</div>}
function StatusBox({name}:{name:string}){return <div className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4"><Badge className="border-emerald-200 bg-white text-emerald-700">Approved</Badge><p className="mt-2 font-semibold">{name}</p></div>}
function Field({label,name,...props}:{label:string;name:string}&React.ComponentProps<typeof Input>){return <label className={field}>{label}<Input name={name} {...props}/></label>}
function Select({label,name,options,defaultValue}:{label:string;name:string;options:string[];defaultValue?:string}){return <label className={field}>{label}<select className={select} defaultValue={defaultValue} name={name}>{options.map(item=><option key={item}>{item}</option>)}</select></label>}
const s=(value:unknown)=>typeof value==="string"?value:"";
const a=(value:unknown)=>Array.isArray(value)?value.join(", "):"";
