"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { Archive, BarChart3, BookOpen, BriefcaseBusiness, Copy, Download, Eye, FileText, Globe, Package, Pencil, Plus, Search, Star, Trash2, Upload, UserRound, WalletCards } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { changeSubscriptionAction } from "@/features/commerce/actions";
import {
  createBusinessResourceAction, deleteBusinessOrderAction, deleteBusinessResourceAction, deletePortfolioItemAction,
  deleteWalletTransactionAction, saveBusinessProfileAction, savePortfolioItemAction, setBusinessResourceStatusAction,
  setSubscriptionRenewalAction, updateBusinessResourceAction
} from "@/features/teacher-business/actions";
import type { getTeacherBusinessData, TeacherBusinessModule } from "@/services/teacher-business-service";

type Data = NonNullable<Awaited<ReturnType<typeof getTeacherBusinessData>>>;
const modules: { slug: TeacherBusinessModule; label: string; icon: typeof UserRound }[] = [
  { slug: "profile", label: "Professional Profile", icon: UserRound }, { slug: "portfolio", label: "Portfolio", icon: BriefcaseBusiness },
  { slug: "publishing", label: "Publishing", icon: Upload }, { slug: "marketplace", label: "Marketplace", icon: Package },
  { slug: "earnings", label: "Earnings", icon: BarChart3 }, { slug: "orders", label: "Orders", icon: FileText },
  { slug: "downloads", label: "Downloads", icon: Download }, { slug: "analytics", label: "Analytics", icon: BarChart3 },
  { slug: "wallet", label: "Wallet", icon: WalletCards }, { slug: "subscription", label: "Subscription", icon: Star }
];
const copy: Record<TeacherBusinessModule, string> = {
  profile: "Build and preview your public professional identity.", portfolio: "Curate and share evidence of your teaching practice.",
  publishing: "Create, price, version, publish, archive, and manage knowledge products.", marketplace: "Manage products, approvals, performance, ratings, and reviews.",
  earnings: "Understand revenue, pending earnings, balances, and trends.", orders: "Search customer orders, status, downloads, and refunds.",
  downloads: "Find purchased resources and re-download files.", analytics: "Measure profile reach, resources, followers, sales, AI usage, and engagement.",
  wallet: "Track balance, credits, earnings, transactions, purchases, withdrawals, and statements.", subscription: "Manage plan usage, billing, renewal, invoices, upgrades, and downgrades."
};
function money(value: number, currency = "INR") { return new Intl.NumberFormat("en-IN", { style: "currency", currency }).format(value); }
function when(value?: string | null) { return value ? new Date(value).toLocaleString() : "Not scheduled"; }
function csv(name: string, rows: (string | number)[][]) {
  const content = rows.map((row) => row.map((cell) => `"${String(cell).replaceAll('"', '""')}"`).join(",")).join("\n");
  const url = URL.createObjectURL(new Blob([content], { type: "text/csv;charset=utf-8" })); const link = document.createElement("a");
  link.href = url; link.download = `${name}.csv`; link.click(); URL.revokeObjectURL(url);
}
function exportModule(name: string, data: unknown) {
  const url = URL.createObjectURL(new Blob([JSON.stringify(data, null, 2)], { type: "application/json" }));
  const link = document.createElement("a"); link.href = url; link.download = `teachx-${name}.json`; link.click(); URL.revokeObjectURL(url);
}
function SmallButton({ children, danger = false }: { children: React.ReactNode; danger?: boolean }) { return <button className={`rounded-full border border-border px-3 py-1.5 text-xs font-medium hover:bg-muted ${danger ? "text-red-600" : ""}`} type="submit">{children}</button>; }
function Metrics({ items }: { items: [string, string | number][] }) { return <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{items.map(([label, value]) => <Card className="p-4" key={label}><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></Card>)}</div>; }

function Profile({ data }: { data: Data }) {
  const p = data.profile;
  return <div className="grid gap-6 xl:grid-cols-[1fr_360px]"><Card className="p-5"><h2 className="text-xl font-semibold">Professional details</h2><form action={saveBusinessProfileAction} className="mt-5 grid gap-4 md:grid-cols-2">
    <div><Label>Profile picture URL</Label><Input defaultValue={p.avatarUrl ?? ""} name="avatarUrl" type="url" /></div><div><Label>Profile banner URL</Label><Input defaultValue={p.banner ?? ""} name="coverUrl" type="url" /></div>
    <div><Label>Professional headline</Label><Input defaultValue={p.headline ?? ""} name="headline" /></div><div><Label>Experience (years)</Label><Input defaultValue={p.experienceYears ?? ""} min="0" name="experienceYears" type="number" /></div>
    <div><Label>Qualification</Label><Input defaultValue={p.qualification ?? ""} name="qualification" /></div><div><Label>Certifications</Label><Input defaultValue={p.certifications.join(", ")} name="certifications" placeholder="Comma separated" /></div>
    <div><Label>Skills</Label><Input defaultValue={p.skills.join(", ")} name="skills" /></div><div><Label>Subjects</Label><Input defaultValue={p.subjects.join(", ")} name="subjects" /></div>
    <div><Label>Grades</Label><Input defaultValue={p.grades.join(", ")} name="grades" /></div><div><Label>Languages</Label><Input defaultValue={p.languages.join(", ")} name="languages" /></div>
    <div><Label>Teaching mode</Label><Select defaultValue={p.teachingMode ?? ""} name="teachingMode"><option value="">Select</option><option>Online</option><option>Offline</option><option>Hybrid</option></Select></div><div><Label>Location</Label><Input defaultValue={p.location ?? ""} name="location" /></div>
    <div className="md:col-span-2"><Label>Bio</Label><Textarea defaultValue={p.bio ?? ""} name="bio" /></div><div className="md:col-span-2"><Label>Availability</Label><Textarea defaultValue={p.availability} name="availability" /></div>
    <div><Label>Website</Label><Input defaultValue={p.website} name="website" type="url" /></div><div><Label>Contact preferences</Label><Input defaultValue={p.contactPreferences} name="contactPreferences" /></div>
    <div><Label>LinkedIn</Label><Input defaultValue={String(p.socialLinks.linkedin ?? "")} name="linkedin" type="url" /></div><div><Label>YouTube</Label><Input defaultValue={String(p.socialLinks.youtube ?? "")} name="youtube" type="url" /></div>
    <div><Label>Instagram</Label><Input defaultValue={String(p.socialLinks.instagram ?? "")} name="instagram" type="url" /></div><label className="flex items-center gap-2 self-end pb-3"><input defaultChecked={p.public} name="public" type="checkbox" /> Public profile enabled</label>
    <Button className="md:col-span-2 md:w-fit" type="submit">Save professional profile</Button></form></Card>
    <Card className="h-fit overflow-hidden"><div className="h-28 bg-sky-100 bg-cover bg-center" style={p.banner ? { backgroundImage: `url(${p.banner})` } : undefined} /><div className="p-5"><div className="-mt-12 h-20 w-20 rounded-2xl border-4 border-white bg-sky-200 bg-cover bg-center" style={p.avatarUrl ? { backgroundImage: `url(${p.avatarUrl})` } : undefined} /><h2 className="mt-3 text-xl font-semibold">{p.name}</h2><p className="text-sm text-muted-foreground">{p.headline || "Professional Teacher"}</p><p className="mt-3 text-sm">{p.bio || "Add your professional bio."}</p>{p.id ? <Link className="mt-5 inline-flex w-full justify-center rounded-xl bg-primary px-4 py-3 text-sm font-medium text-primary-foreground" href={`/marketplace/teachers/${p.id}`}><Eye className="mr-2 h-4 w-4" />Public Profile Preview</Link> : null}</div></Card></div>;
}

function Portfolio({ data }: { data: Data }) {
  const [query, setQuery] = useState(""); const items = data.portfolio.filter((item) => `${item.title} ${item.type} ${item.description}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="space-y-5"><details className="rounded-2xl border border-border bg-surface p-5"><summary className="cursor-pointer font-semibold"><Plus className="mr-2 inline h-4 w-4" />Add portfolio item</summary><PortfolioForm /></details><Input className="max-w-xl" onChange={(e) => setQuery(e.target.value)} placeholder="Search portfolio…" value={query} />{items.length ? <div className="grid gap-4 md:grid-cols-2">{items.map((item) => <Card className="p-5" key={item.id as string}><Badge>{String(item.type ?? "WORK")}</Badge><h2 className="mt-2 text-xl font-semibold">{String(item.title ?? "Untitled")}</h2><p className="mt-2 text-sm text-muted-foreground">{String(item.description ?? "")}</p>{item.url ? <Link className="mt-3 inline-flex text-sm font-semibold text-sky-700" href={String(item.url)} target="_blank">View work</Link> : null}<details className="my-4"><summary className="cursor-pointer text-sm font-medium">Edit</summary><PortfolioForm item={item} /></details><form action={deletePortfolioItemAction}><input name="id" type="hidden" value={item.id as string} /><SmallButton danger>Delete</SmallButton></form></Card>)}</div> : <EmptyState icon={<BriefcaseBusiness className="h-5 w-5" />} title="No portfolio items" description="Add sample lessons, worksheets, assessments, philosophy, achievements, awards, publications, gallery images, videos, or documents." />}<Button onClick={() => navigator.clipboard.writeText(`${location.origin}/marketplace/teachers/${data.profile.id}`)} type="button" variant="secondary"><Copy className="mr-2 h-4 w-4" />Copy public portfolio link</Button></div>;
}
function PortfolioForm({ item }: { item?: Data["portfolio"][number] }) { return <form action={savePortfolioItemAction} className="mt-4 grid gap-3 md:grid-cols-2">{item ? <input name="id" type="hidden" value={item.id as string} /> : null}<Input defaultValue={String(item?.title ?? "")} name="title" placeholder="Title" required /><Select defaultValue={String(item?.type ?? "SAMPLE_LESSON")} name="type">{["SAMPLE_LESSON","SAMPLE_WORKSHEET","SAMPLE_ASSESSMENT","TEACHING_PHILOSOPHY","ACHIEVEMENT","AWARD","PUBLICATION","GALLERY","VIDEO","DOCUMENT"].map((x) => <option key={x}>{x}</option>)}</Select><Textarea className="md:col-span-2" defaultValue={String(item?.description ?? "")} name="description" placeholder="Description" /><Input defaultValue={String(item?.url ?? "")} name="url" placeholder="Public URL" type="url" /><Input defaultValue={String(item?.thumbnail ?? "")} name="thumbnail" placeholder="Thumbnail URL" type="url" /><label className="flex items-center gap-2"><input defaultChecked={Boolean(item?.public)} name="public" type="checkbox" /> Public</label><Button type="submit">{item ? "Save changes" : "Add item"}</Button></form>; }

function Publishing({ data }: { data: Data }) {
  const [query, setQuery] = useState(""); const [status, setStatus] = useState("ALL");
  const items = data.resources.filter((x) => `${x.title} ${x.category} ${x.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase())).filter((x) => status === "ALL" || x.status === status);
  return <div className="space-y-5"><details className="rounded-2xl border border-border bg-surface p-5"><summary className="cursor-pointer font-semibold"><Upload className="mr-2 inline h-4 w-4" />Upload resource</summary><ResourceForm data={data} /></details><div className="grid gap-3 md:grid-cols-[1fr_240px]"><Input onChange={(e) => setQuery(e.target.value)} placeholder="Search listings, categories, tags…" value={query} /><Select onChange={(e) => setStatus(e.target.value)} value={status}><option>ALL</option><option>DRAFT</option><option>SUBMITTED</option><option>ACADEMIC_APPROVAL</option><option>PUBLISHED</option><option>ARCHIVED</option></Select></div>{items.length ? <div className="grid gap-4 lg:grid-cols-2">{items.map((item) => <ResourceCard data={data} item={item} key={item.id} />)}</div> : <EmptyState icon={<Package className="h-5 w-5" />} title="No resources found" description="Upload a resource or adjust filters." />}</div>;
}
function ResourceForm({ data, item }: { data: Data; item?: Data["resources"][number] }) { const action = item ? updateBusinessResourceAction : createBusinessResourceAction; return <form action={action} className="mt-4 grid gap-3 md:grid-cols-2">{item ? <input name="id" type="hidden" value={item.id} /> : null}<Input defaultValue={item?.title} name="title" placeholder="Resource title" required />{!item ? <Select name="courseId" required><option value="">Course / grade</option>{data.courses.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</Select> : null}{!item ? <Select name="subjectId"><option value="">Subject</option>{data.subjects.map((x) => <option key={x.id} value={x.id}>{x.name} · {x.course}</option>)}</Select> : null}<Select defaultValue={item?.type ?? "DOCUMENT"} name="type">{["DOCUMENT","NOTES","WORKSHEET","QUESTION_PAPER","PPT","PDF","VIDEO","IMAGE","ZIP","REFERENCE"].map((x) => <option key={x}>{x}</option>)}</Select><Input defaultValue={item?.category} name="category" placeholder="Category" required /><Input defaultValue={item?.tags.join(", ")} name="tags" placeholder="Tags, comma separated" /><Select defaultValue={item?.priceType ?? "Free"} name="priceType"><option>Free</option><option>Premium</option></Select><Input defaultValue={item?.price} min="0" name="price" placeholder="Price" type="number" /><Input defaultValue={item?.thumbnail ?? ""} name="thumbnail" placeholder="Thumbnail URL" type="url" /><Input defaultValue={item?.fileUrl ?? ""} name="fileUrl" placeholder="Resource file URL" type="url" /><Input defaultValue={item?.attachments.join(", ")} name="attachments" placeholder="Attachment URLs, comma separated" /><Textarea className="md:col-span-2" defaultValue={item?.description ?? ""} name="description" placeholder="Description" /><Textarea className="md:col-span-2" name="preview" placeholder="Preview content" />{item ? <Input className="md:col-span-2" name="changeNote" placeholder="Version change note" /> : <label className="flex items-center gap-2"><input name="publish" type="checkbox" /> Publish immediately</label>}<Button type="submit">{item ? "Save listing and version" : "Create resource"}</Button></form>; }
function ResourceCard({ data, item }: { data: Data; item: Data["resources"][number] }) { return <Card className="p-5"><div className="flex justify-between gap-3"><div><Badge>{item.status}</Badge><h2 className="mt-2 text-xl font-semibold">{item.title}</h2><p className="text-sm text-muted-foreground">{item.category} · {item.priceType === "Premium" ? money(item.price) : "Free"} · v{item.version}</p></div>{item.thumbnail ? <div className="h-16 w-20 rounded-lg bg-cover bg-center" style={{ backgroundImage: `url(${item.thumbnail})` }} /> : null}</div><p className="mt-3 line-clamp-3 text-sm">{item.description}</p><details className="my-4 rounded-xl bg-background p-3"><summary className="cursor-pointer text-sm font-medium">Preview, edit, attachments, versions</summary>{item.fileUrl ? <Link className="mt-3 block text-sm font-semibold text-sky-700" href={item.fileUrl} target="_blank">Open resource</Link> : null}<ResourceForm data={data} item={item} /><div className="mt-4 space-y-2">{item.versions.map((v) => <p className="text-xs text-muted-foreground" key={v.version}>v{v.version} · {v.note || "Version saved"} · {when(v.createdAt)}</p>)}</div></details><div className="flex flex-wrap gap-2">{item.status !== "PUBLISHED" ? <StatusForm id={item.id} label="Publish" status="PUBLISHED" /> : <StatusForm id={item.id} label="Move to draft" status="DRAFT" />}{item.status !== "ARCHIVED" ? <StatusForm id={item.id} label="Archive" status="ARCHIVED" /> : <StatusForm id={item.id} label="Restore" status="DRAFT" />}<form action={deleteBusinessResourceAction}><input name="id" type="hidden" value={item.id} /><SmallButton danger>Delete</SmallButton></form></div></Card>; }
function StatusForm({ id, status, label }: { id: string; status: string; label: string }) { return <form action={setBusinessResourceStatusAction}><input name="id" type="hidden" value={id} /><input name="status" type="hidden" value={status} /><SmallButton>{label}</SmallButton></form>; }

function Marketplace({ data }: { data: Data }) {
  const [status, setStatus] = useState("ALL"); const products = data.resources.filter((x) => status === "ALL" || x.status === status);
  return <div className="space-y-5"><Metrics items={[["Products", data.resources.length],["Published", data.resources.filter(x=>x.status==="PUBLISHED").length],["Pending approval", data.resources.filter(x=>["SUBMITTED","ACADEMIC_APPROVAL"].includes(x.status)).length],["Sales",data.sales.length]]}/><Select className="max-w-xs" onChange={(e)=>setStatus(e.target.value)} value={status}><option>ALL</option><option>PUBLISHED</option><option>DRAFT</option><option>SUBMITTED</option><option>ACADEMIC_APPROVAL</option></Select><div className="grid gap-4 lg:grid-cols-2">{products.map((x)=><Card className="p-5" key={x.id}><h2 className="font-semibold">{x.title}</h2><p className="mt-1 text-sm text-muted-foreground">{x.views} views · {x.downloads} downloads · {x.rating ? `${x.rating}/5 (${x.reviewCount})` : "No ratings yet"}</p>{x.workflowReviews.length ? <details className="mt-3"><summary className="text-sm font-medium">Approval feedback</summary>{x.workflowReviews.map((r,i)=><p className="mt-2 text-sm" key={i}>{r.decision}: {r.notes || "No notes"}</p>)}</details>:null}<Link className="mt-4 inline-flex text-sm font-semibold text-sky-700" href="/teacher/business/publishing">Edit listing</Link></Card>)}</div></div>;
}
function Earnings({ data }: { data: Data }) { const e=data.earnings; return <div className="space-y-6"><Metrics items={[["Total Revenue",money(e.total)],["Monthly Revenue",money(e.monthly)],["Daily Revenue",money(e.daily)],["Withdrawable",money(e.withdrawable)],["Product Sales",money(e.product)],["AI Credit Revenue",money(e.aiCredits)],["Subscription Revenue",money(e.subscription)],["Pending Earnings",money(e.pending)]]}/><Card className="p-5"><h2 className="text-xl font-semibold">Revenue Trends</h2><div className="mt-5 flex h-48 items-end gap-3">{e.trend.map(x=>{const max=Math.max(...e.trend.map(y=>y.value),1);return <div className="flex flex-1 flex-col items-center gap-2" key={x.label}><span className="text-xs">{money(x.value)}</span><div className="w-full rounded-t bg-sky-600" style={{height:`${Math.max(4,(x.value/max)*130)}px`}}/><span className="text-xs text-muted-foreground">{x.label}</span></div>})}</div></Card><Button onClick={()=>csv("earnings-statement",[["Month","Revenue"],...e.trend.map(x=>[x.label,x.value])])} type="button" variant="secondary"><Download className="mr-2 h-4 w-4"/>Export revenue</Button></div>; }
function Orders({ data }: { data: Data }) { const [q,setQ]=useState("");const [s,setS]=useState("ALL");const rows=data.sales.filter(x=>`${x.product} ${x.customer} ${x.email} ${x.orderId}`.toLowerCase().includes(q.toLowerCase())).filter(x=>s==="ALL"||x.status===s);return <div className="space-y-5"><div className="grid gap-3 md:grid-cols-[1fr_240px]"><Input onChange={e=>setQ(e.target.value)} placeholder="Search orders or customers…" value={q}/><Select onChange={e=>setS(e.target.value)} value={s}><option>ALL</option>{[...new Set(data.sales.map(x=>x.status))].map(x=><option key={x}>{x}</option>)}</Select></div>{rows.length?<div className="space-y-3">{rows.map(x=><Card className="p-4" key={x.id}><div className="flex flex-wrap justify-between gap-3"><div><Badge>{x.status}</Badge><h2 className="mt-2 font-semibold">{x.product}</h2><p className="text-sm text-muted-foreground">{x.customer} · {x.email} · {when(x.createdAt)}</p></div><div className="text-right"><p className="font-semibold">{money(x.amount,x.currency)}</p><p className="text-xs text-muted-foreground">{x.downloads} downloads · {x.refundStatus}</p></div></div></Card>)}</div>:<EmptyState icon={<FileText className="h-5 w-5"/>} title="No orders found" description="Sales orders will appear here."/>}<Button onClick={()=>csv("orders",[["Order","Product","Customer","Status","Amount"],...rows.map(x=>[x.orderId,x.product,x.customer,x.status,x.amount])])} type="button" variant="secondary">Export orders</Button></div>; }
function Downloads({ data }: { data: Data }) { const [q,setQ]=useState("");const rows=data.downloads.filter(x=>`${x.title} ${x.course} ${x.subject}`.toLowerCase().includes(q.toLowerCase()));return <div className="space-y-5"><Input className="max-w-xl" onChange={e=>setQ(e.target.value)} placeholder="Search purchased resources and downloads…" value={q}/><h2 className="text-xl font-semibold">Purchased Resources</h2><div className="grid gap-3 md:grid-cols-2">{data.purchases.flatMap(o=>o.items.filter(i=>i.resourceId)).map((x,i)=><Card className="p-4" key={`${x.resourceId}-${i}`}><h3 className="font-semibold">{x.title}</h3>{x.fileUrl?<Link className="mt-3 inline-flex text-sm font-semibold text-sky-700" href={x.fileUrl}>Re-download</Link>:<p className="mt-2 text-sm text-muted-foreground">File not attached.</p>}</Card>)}</div><h2 className="text-xl font-semibold">Download History</h2>{rows.length?<div className="space-y-3">{rows.map(x=><Card className="flex items-center justify-between gap-3 p-4" key={x.id}><div><h3 className="font-semibold">{x.title}</h3><p className="text-sm text-muted-foreground">{x.course} · {when(x.downloadedAt)}</p></div>{x.fileUrl?<Link className="rounded-full border border-border px-3 py-2 text-xs font-medium" href={x.fileUrl}>Re-download</Link>:null}</Card>)}</div>:<EmptyState icon={<Download className="h-5 w-5"/>} title="No downloads found" description="Downloaded resources appear here."/>}</div>; }
function Analytics({ data }: { data: Data }) { const a=data.analytics;return <div className="space-y-6"><Metrics items={[["Profile Views",a.profileViews],["Resource Views",a.resourceViews],["Downloads",a.downloads],["Sales",a.sales],["Followers",a.followers],["Engagement",`${a.engagement}%`],["AI Usage",a.aiUsage],["Activities",a.timeline.length]]}/><Card className="p-5"><h2 className="text-xl font-semibold">Activity Timeline & Monthly Insights</h2><div className="mt-4 space-y-2">{a.timeline.length?a.timeline.map(x=><div className="rounded-xl bg-background p-3 text-sm" key={x.id}><strong>{x.title}</strong><span className="ml-2 text-muted-foreground">{x.type} · {when(x.createdAt)}</span></div>):<p className="text-sm text-muted-foreground">No activity recorded yet.</p>}</div></Card><Button onClick={()=>csv("teacher-analytics",[["Metric","Value"],["Profile Views",a.profileViews],["Resource Views",a.resourceViews],["Downloads",a.downloads],["Sales",a.sales],["Followers",a.followers],["Engagement",a.engagement],["AI Usage",a.aiUsage]])} type="button" variant="secondary">Export analytics</Button></div>; }
function Wallet({ data }: { data: Data }) { const w=data.wallet;return <div className="space-y-6"><Metrics items={[["Wallet Balance",money(w.balance)],["Pending",money(w.pending)],["Lifetime Earnings",money(w.lifetimeEarnings)],["Lifetime Spending",money(w.lifetimeSpending)],["AI Credits",data.credits.balance],["Credits Used",data.credits.used],["Purchases",data.purchases.length],["Transactions",w.transactions.length]]}/><Card className="p-5"><h2 className="text-xl font-semibold">Transactions & Withdraw History</h2><div className="mt-4 space-y-2">{w.transactions.map(x=><div className="flex justify-between gap-3 rounded-xl bg-background p-3 text-sm" key={x.id}><div><strong>{x.description}</strong><span className="block text-muted-foreground">{x.type} · {when(x.createdAt)}</span></div><div className="text-right"><strong>{money(x.amount)}</strong>{x.pending&&x.type==="HOLD"?<form action={deleteWalletTransactionAction}><input name="id" type="hidden" value={x.id}/><button className="block text-xs text-red-600" type="submit">Remove pending hold</button></form>:null}</div></div>)}</div></Card><Card className="p-5"><h2 className="text-xl font-semibold">Purchase History</h2><div className="mt-4 space-y-2">{data.purchases.length?data.purchases.map(x=><div className="flex justify-between gap-3 rounded-xl bg-background p-3 text-sm" key={x.id}><div><strong>{x.items.map(i=>i.title).join(", ")}</strong><span className="block text-muted-foreground">{x.status} · {when(x.createdAt)}</span></div><div className="text-right"><strong>{money(x.total,x.currency)}</strong>{["DRAFT","CREATED","CANCELLED"].includes(x.status)?<form action={deleteBusinessOrderAction}><input name="id" type="hidden" value={x.id}/><button className="block text-xs text-red-600" type="submit">Delete order</button></form>:null}</div></div>):<p className="text-sm text-muted-foreground">No purchases yet.</p>}</div></Card><Button onClick={()=>csv("wallet-statement",[["Date","Type","Description","Amount"],...w.transactions.map(x=>[x.createdAt,x.type,x.description,x.amount])])} type="button" variant="secondary">Export statement</Button></div>; }
function Subscription({ data }: { data: Data }) { const s=data.subscription;const currentPrice=data.plans.find(x=>x.id===s?.planId)?.price??0;return <div className="space-y-6">{s?<Metrics items={[["Current Plan",s.name],["Renewal Status",s.cancelAtPeriodEnd?"Cancels at period end":"Auto-renewing"],["Resources",`${data.resources.length}/${s.resourceLimit}`],["Storage Limit",`${s.storageLimitMb} MB`],["AI Usage",`${data.credits.used}/${data.credits.allocation}`],["Renews",when(s.renewsAt)],["Invoices",data.invoices.length],["Status",s.status]]}/>:null}<Card className="border-sky-200 bg-sky-50/40 p-5"><h2 className="text-xl font-semibold">Launch billing rule</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Free plans activate immediately. Paid plans create a secure checkout order and open the checkout review page. Paid access starts only after Razorpay or Stripe payment confirmation is connected.</p></Card><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5">{data.plans.map(p=><Card className={`p-5 ${s?.planId===p.id?"border-sky-300 bg-sky-50/30":""}`} key={p.id}><Badge>{s?.planId===p.id?"Current":"Available"}</Badge><h2 className="mt-3 text-xl font-semibold">{p.name}</h2><p className="mt-2 text-2xl font-semibold">{p.name==="Institution"?"Custom":money(p.price,p.currency)}</p><p className="mt-2 text-sm text-muted-foreground">{p.credits} AI credits - {p.resourceLimit} resources - {p.storageLimitMb} MB</p><p className="mt-3 text-xs text-muted-foreground">{p.price>0?"Checkout required before activation":"Activates without payment."}</p>{s?.planId!==p.id?<form action={changeSubscriptionAction} className="mt-4"><input name="planId" type="hidden" value={p.id}/><Button className="w-full" type="submit">{p.price===0?"Choose Free":p.price>currentPrice?"Upgrade":"Change Plan"}</Button></form>:null}</Card>)}</div>{s?<form action={setSubscriptionRenewalAction}><input name="id" type="hidden" value={s.id}/><input name="cancel" type="hidden" value={String(!s.cancelAtPeriodEnd)}/><Button type="submit" variant="secondary">{s.cancelAtPeriodEnd?"Resume renewal":"Cancel at period end"}</Button></form>:null}<Card className="p-5"><h2 className="text-xl font-semibold">Billing History & Invoices</h2><div className="mt-4 space-y-2">{data.invoices.length?data.invoices.map(x=><div className="flex justify-between rounded-xl bg-background p-3 text-sm" key={x.id}><span>{x.number} - {x.status} - {when(x.createdAt)}</span><strong>{money(x.total)}</strong></div>):<p className="text-sm text-muted-foreground">No invoices yet. Paid checkout orders will appear after gateway payment and invoice finalization are enabled.</p>}</div></Card></div>; }

export function TeacherBusinessPage({ module, data }: { module: TeacherBusinessModule; data: Data }) {
  return <div className="space-y-6"><nav className="text-sm text-muted-foreground"><Link href="/teacher">Teacher Home</Link><span className="mx-2">/</span><span>Business OS</span><span className="mx-2">/</span><span className="text-foreground">{modules.find(x=>x.slug===module)?.label}</span></nav><section className="rounded-[2rem] border border-border bg-gradient-to-br from-sky-50 via-white to-blue-50 p-6 shadow-soft sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><Badge>Teacher Business OS</Badge><h1 className="mt-4 text-4xl font-semibold tracking-tight">{modules.find(x=>x.slug===module)?.label}</h1><p className="mt-3 max-w-3xl text-lg text-muted-foreground">{copy[module]}</p></div><Button onClick={()=>exportModule(module,data)} type="button" variant="secondary"><Download className="mr-2 h-4 w-4"/>Export</Button></div></section><nav className="flex gap-2 overflow-x-auto pb-2">{modules.map(x=>{const Icon=x.icon;return <Link className={`inline-flex shrink-0 items-center gap-2 rounded-full px-4 py-2 text-sm font-medium ${module===x.slug?"bg-primary text-primary-foreground":"border border-border bg-surface"}`} href={`/teacher/business/${x.slug}`} key={x.slug}><Icon className="h-4 w-4"/>{x.label}</Link>})}</nav>{module==="profile"?<Profile data={data}/>:module==="portfolio"?<Portfolio data={data}/>:module==="publishing"?<Publishing data={data}/>:module==="marketplace"?<Marketplace data={data}/>:module==="earnings"?<Earnings data={data}/>:module==="orders"?<Orders data={data}/>:module==="downloads"?<Downloads data={data}/>:module==="analytics"?<Analytics data={data}/>:module==="wallet"?<Wallet data={data}/>:<Subscription data={data}/>}</div>;
}
