import { NextRequest, NextResponse } from "next/server";
import { requireApiSession } from "@/lib/api-auth";
import { getDirectorAdmissionsIntelligence } from "@/services/director-admissions-intelligence-service";
const reports=new Set(["overview","pipeline","counsellors","programs","marketing","forecast","reports","alerts","admissions","conversion","growth","funnel","actions"]),formats=new Set(["csv","json"]),sorts=new Set(["volume","name"]);
const cell=(v:unknown)=>{let s=v==null?"":String(v);if(/^[=+\-@]/.test(s))s=`'${s}`;return `"${s.replaceAll('"','""')}"`};
export async function GET(request:NextRequest){
 const access=await requireApiSession("director.view");if("response" in access)return access.response;const institutionId=access.session.user.institutionId;if(!institutionId)return NextResponse.json({error:"Institution scope required"},{status:403});
 const p=request.nextUrl.searchParams,report=p.get("report")??"overview",format=p.get("format")??"csv",query=(p.get("query")??"").slice(0,100).toLowerCase(),sort=p.get("sort")??"volume",capacity=Number(p.get("capacity")??85),window=Number(p.get("window")??3),filter=p.get("filter")??"all";
 if(!reports.has(report)||!formats.has(format)||!sorts.has(sort)||!Number.isFinite(capacity)||capacity<60||capacity>100||![1,3,6].includes(window)||!["all","attention","converted","demand","unconverted"].includes(filter))return NextResponse.json({error:"Invalid export request"},{status:400});
 const d=await getDirectorAdmissionsIntelligence({institutionId});const capacityActions=d.programs.filter(p=>(p.utilization??0)>=capacity).map(p=>({id:`capacity-${p.id}`,severity:(p.utilization??0)>=95?"HIGH":"WATCH",signal:"Capacity pressure",evidence:`${p.name} is ${p.utilization}% utilized (${p.enrolled}/${p.capacity})`,action:"Review batch capacity before promoting further demand.",owner:"Academic operations",due:"Before next campaign",report:"actions"}));const allActions=[...d.actions,...capacityActions];const catalogs:Record<string,Record<string,unknown>[]>={overview:[{institution:d.institution,...d.summary}],admissions:[{institution:d.institution,...d.summary}],conversion:[{institution:d.institution,...d.summary}],pipeline:[...d.stages.map(r=>({section:"stage",stage:r.stage,count:r.count})),...d.followUpQueue.map(r=>({section:"follow-up",status:r.status,stage:r.stage,owner:r.owner,scheduledAt:r.scheduledAt,priority:r.priority}))],funnel:d.stages,counsellors:d.counsellors,programs:[...d.programs.map(r=>({section:"program",...r})),...d.departments.map(r=>({section:"department",...r}))],marketing:[...d.campaigns.map(r=>({section:"campaign",...r})),...d.sources.map(r=>({section:"source",...r})),{section:"partner",referrals:d.partnerships.referrals,attributedAdmissions:d.partnerships.attributedAdmissions,commissions:d.partnerships.commissions,commissionAmount:d.partnerships.commissionAmount}],growth:[{institution:d.institution,predictedAdmissions:Math.round(d.forecast.monthlyRunRate*window),forecastWindowMonths:window,...d.forecast}],forecast:[{section:"summary",institution:d.institution,predictedAdmissions:Math.round(d.forecast.monthlyRunRate*window),forecastWindowMonths:window,monthlyRunRate:d.forecast.monthlyRunRate,sampleMonths:d.forecast.sampleMonths,sampleAdmissions:d.forecast.coverage,method:d.forecast.method},...d.forecast.monthly.map(r=>({section:"monthly-history",month:r.month,admissions:r.admissions}))],actions:allActions,alerts:[{section:"headline",cohort:"Pending applications",count:d.pendingApplications.length},{section:"headline",cohort:"Pending admission approvals",count:d.approvals.length},{section:"headline",cohort:"Missed or overdue follow-ups",count:d.followUps.missed},{section:"headline",cohort:`Capacity at or above ${capacity}%`,count:capacityActions.length},...d.pendingApplications.map(r=>({section:"application-ageing",status:r.status,course:r.course,ageDays:r.ageDays})),...d.approvals.map(r=>({section:"approval-ageing",status:r.status,course:r.course,ageDays:r.ageDays}))],reports:[{institution:d.institution,...d.summary,...d.forecast}]};
 const rows=(catalogs[report]??catalogs.overview).filter(r=>!query||JSON.stringify(r).toLowerCase().includes(query)).filter(r=>filter==="all"||(filter==="attention"&&(Number(r.missed??0)>0||Number(r.utilization??0)>=capacity))||(filter==="converted"&&Number(r.admissions??0)>0)||(filter==="demand"&&Number(r.demand??0)>0)||(filter==="unconverted"&&Number(r.leads??0)>0&&Number(r.admissions??0)===0)).sort((a,b)=>sort==="name"?String(a.name??a.signal??"").localeCompare(String(b.name??b.signal??"")):Number(b.leads??b.demand??b.count??b.assigned??0)-Number(a.leads??a.demand??a.count??a.assigned??0));
 const payload={report,filters:{query,sort,filter,capacity,window},methodology:"Authenticated institution scope; confirmed admissions are APPROVED + ENROLLED; forecasts use observed monthly run rate; missing modeled data remains unavailable.",generatedAt:new Date().toISOString(),rows};const keys=rows.length?[...new Set(rows.flatMap(row=>Object.keys(row)))]:["status"],body=format==="json"?JSON.stringify(payload):[keys.map(cell).join(","),...rows.map(r=>keys.map(k=>cell(r[k])).join(","))].join("\r\n");
 return new NextResponse(body,{headers:{"Content-Type":format==="json"?"application/json; charset=utf-8":"text/csv; charset=utf-8","Content-Disposition":`attachment; filename="directorx-${report}.${format}"`,"Cache-Control":"private, no-store","X-Content-Type-Options":"nosniff"}})
}
