"use client";

import { useEffect, useMemo, useState } from "react";
import { BarChart3, BookOpen, Download, Search, ShieldCheck } from "lucide-react";
import type { getDirectorAcademicIntelligence } from "@/services/director-academic-intelligence-service";

type Data = Awaited<ReturnType<typeof getDirectorAcademicIntelligence>>;
type View = "Performance" | "Teachers" | "Students" | "Departments" | "Assessments" | "Recommendations" | "Compare" | "Reports" | "Risk" | "Settings";
const views: View[] = ["Performance", "Students", "Assessments", "Recommendations", "Reports"];
const value = (number: number | null) => number === null ? "Unknown" : `${number}%`;

function Empty({ title, detail }: { title: string; detail: string }) { return <div className="border border-dashed border-[#adb8b2] bg-white p-10 text-center"><ShieldCheck className="mx-auto h-7 w-7 text-[#19765b]"/><h3 className="mt-3 font-semibold">{title}</h3><p className="mx-auto mt-2 max-w-xl text-sm text-[#68736e]">{detail}</p></div>; }
function Heading({ overline, title, meta }: { overline: string; title: string; meta?: string }) { return <header className="mb-5 flex items-end justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#19765b]">{overline}</p><h2 className="mt-1 text-xl font-semibold tracking-tight">{title}</h2></div>{meta && <span className="text-xs text-[#68736e]">{meta}</span>}</header>; }
function Bars({ rows }: { rows: { name: string; score: number | null; evidence?: number }[] }) { return rows.length ? <div className="space-y-4">{rows.map(row => <div key={row.name}><div className="mb-2 flex justify-between text-sm"><span className="font-medium">{row.name}</span><span className="tabular-nums">{value(row.score)} · {row.evidence ?? 0} results</span></div><div className="h-2 bg-[#e8ebe7]"><div className="h-full bg-[#19765b]" style={{ width: `${row.score ?? 0}%` }}/></div></div>)}</div> : <Empty title="No measured results yet" detail="Published exam results will populate this comparison. Missing evidence is never treated as zero performance."/>; }

export function AcademicIntelligenceWorkspace({ data }: { data: Data }) {
  const [view, setView] = useState<View>("Performance"); const [query, setQuery] = useState(""); const [sort, setSort] = useState("score"); const [threshold, setThreshold] = useState(50);
  useEffect(() => { const saved = localStorage.getItem("directorx-academic-threshold"); if (saved) setThreshold(Number(saved)); }, []);
  const saveThreshold = (next: number) => { setThreshold(next); localStorage.setItem("directorx-academic-threshold", String(next)); };
  const teachers = useMemo(() => data.teachers.filter(t => `${t.name} ${t.email}`.toLowerCase().includes(query.toLowerCase())).sort((a,b) => sort === "name" ? a.name.localeCompare(b.name) : (b.score ?? -1) - (a.score ?? -1)), [data.teachers, query, sort]);
  const students = useMemo(() => data.students.filter(s => `${s.name} ${s.email}`.toLowerCase().includes(query.toLowerCase())).sort((a,b) => sort === "name" ? a.name.localeCompare(b.name) : sort === "risk" ? b.risk-a.risk : (b.score ?? -1)-(a.score ?? -1)), [data.students, query, sort]);
  const reportForView: Record<View, string | null> = { Performance: "academic", Teachers: "teachers", Students: "students", Departments: "departments", Assessments: "assessments", Recommendations: "actions", Compare: "classes", Reports: null, Risk: "risks", Settings: null };
  const download = (report: string, format: "csv" | "json" = "csv") => { const params = new URLSearchParams({ report, format, query, sort, threshold: String(threshold) }); window.location.href = `/api/director/academic-export?${params}`; };
  const visibleActions = data.actions
    .filter(action => action.domain !== "GRADE" || Number(action.evidence.match(/[0-9.]+/)?.[0] ?? 101) < threshold)
    .filter(action => `${action.domain} ${action.subject} ${action.owner} ${action.evidence} ${action.action}`.toLowerCase().includes(query.toLowerCase()))
    .sort((a, b) => sort === "name" ? a.subject.localeCompare(b.subject) : sort === "risk" ? ["CRITICAL", "HIGH", "WATCH"].indexOf(a.severity) - ["CRITICAL", "HIGH", "WATCH"].indexOf(b.severity) : a.domain.localeCompare(b.domain));
  const visibleDepartments = data.departments
    .filter(department => department.name.toLowerCase().includes(query.toLowerCase()))
    .sort((a, b) => sort === "name" ? a.name.localeCompare(b.name) : (b.score ?? -1) - (a.score ?? -1));
  let content;
  if (view === "Performance") content = <><div className="grid gap-px bg-[#d6d9d4] sm:grid-cols-2 lg:grid-cols-4">{[["Academic score",value(data.summary.academicScore)],["Pass rate",value(data.summary.passRate)],["Saved attendance",value(data.summary.attendance)],["Learning completion",value(data.summary.completion)]].map(([label,v])=><article className="bg-white p-5" key={label}><p className="text-[10px] font-bold uppercase tracking-[.15em] text-[#718079]">{label}</p><p className="mt-4 text-3xl font-semibold tabular-nums">{v}</p></article>)}</div><div className="mt-6 grid gap-5 lg:grid-cols-2"><article className="border bg-white p-6"><Heading overline="Department performance" title="Where outcomes stand"/><Bars rows={data.departments}/></article><article className="border bg-white p-6"><Heading overline="Subject performance" title="Measured subject outcomes"/><Bars rows={data.subjects}/></article></div><article className="mt-5 bg-[#14231f] p-6 text-white"><Heading overline="Course, class & year lens" title="Measured comparisons"/><div className="mb-6 grid gap-4 md:grid-cols-2"><div><p className="mb-3 text-xs font-bold uppercase tracking-wider text-[#79c9ad]">Courses</p>{data.courses.slice(0,5).map(course => <p className="border-b border-white/10 py-2 text-sm" key={course.id}>{course.name} · {course.year} <b className="float-right">{value(course.score)}</b></p>)}</div><div><p className="mb-3 text-xs font-bold uppercase tracking-wider text-[#79c9ad]">Classes</p>{data.classes.slice(0,5).map(item => <p className="border-b border-white/10 py-2 text-sm" key={item.id}>{item.name} · {item.students} students <b className="float-right">{value(item.score)}</b></p>)}</div></div><Heading overline="Evidence summary" title="What this briefing knows"/><p className="text-sm leading-6 text-white/70">Derived deterministically from {data.evidence.examResults} exam results, {data.evidence.savedAttendanceRecords} saved attendance records, {data.evidence.learningProgressRecords} progress records and {data.evidence.assignmentSubmissions} assignment submissions. No paid AI is invoked on render.</p></article></>;
  else if (view === "Teachers") content = <section><Heading overline="Teacher performance" title="Faculty evidence directory" meta={`${teachers.length} teachers`}/>{teachers.length ? <div className="divide-y border bg-white">{teachers.map(t=><article className="grid gap-4 p-5 md:grid-cols-[1fr_repeat(5,90px)]" key={t.id}><div><b>{t.name}</b><p className="text-xs text-[#718079]">{t.email}</p></div>{[["Composite",value(t.score)],["Outcomes",value(t.outcome)],["Activity",t.activities],["AI use",t.ai],["Resources",t.resources]].map(([l,v])=><dl key={l}><dt className="text-[9px] uppercase text-[#718079]">{l}</dt><dd className="mt-1 font-semibold tabular-nums">{v}</dd></dl>)}</article>)}</div> : <Empty title="No teachers match" detail="Adjust search or wait for faculty assignments to be recorded."/>}<p className="mt-4 text-xs text-[#68736e]">Composite: 70% student outcomes + up to 20 points resource contribution + up to 10 points assignment activity. Feedback is not collected in the academic schema (0% coverage).</p></section>;
  else if (view === "Students") content = <section><Heading overline="Student performance" title="Progress and risk evidence" meta={`${students.length} students`}/><div className="mb-5 grid grid-cols-4 gap-px bg-[#d6d9d4]">{[["Distinction",students.filter(item => (item.score ?? -1) >= 75).length],["On track",students.filter(item => (item.score ?? -1) >= 50 && (item.score ?? -1) < 75).length],["Intervention",students.filter(item => item.score !== null && item.score < 50).length],["Unknown",students.filter(item => item.score === null).length]].map(([label,count]) => <article className="bg-white p-4" key={label}><p className="text-[10px] uppercase text-[#718079]">{label}</p><p className="mt-2 text-2xl font-semibold">{count}</p></article>)}</div>{students.length ? <div className="divide-y border bg-white">{students.map(s=><article className="grid gap-4 p-5 md:grid-cols-[1fr_repeat(4,100px)]" key={s.id}><div><b>{s.name}</b><p className="text-xs text-[#718079]">{s.email}</p></div>{[["Grade",value(s.score)],["Attendance",value(s.attendance)],["Progress",value(s.completion)],["Risk",s.risk]].map(([l,v])=><dl key={l}><dt className="text-[9px] uppercase text-[#718079]">{l}</dt><dd className="mt-1 font-semibold tabular-nums">{v}</dd></dl>)}</article>)}</div> : <Empty title="No students match" detail="Adjust search or enroll students in the authorized institution."/>}</section>;
  else if (view === "Departments") content = <section><Heading overline="Department analytics" title="Scale, results and comparison"/><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{visibleDepartments.map((d,i)=><article className="border-t-4 border-[#19765b] bg-white p-5" key={d.id}><p className="text-xs text-[#718079]">Rank {i+1} · {d.evidence} results</p><h3 className="mt-2 text-xl font-semibold">{d.name}</h3><p className="mt-5 text-3xl font-semibold">{value(d.score)}</p><p className="mt-3 text-xs">{d.faculty} faculty · {d.students} students · {d.subjects} subjects</p></article>)}</div></section>;
  else if (view === "Assessments") content = <section><Heading overline="Exam & assessment analytics" title="Assessment coverage"/><div className="grid gap-px bg-[#d6d9d4] sm:grid-cols-5">{[["Published exams",data.assessments.total],["Internal exams",data.assessments.internal],["Mock tests",data.assessments.mocks],["Pass rate",value(data.assessments.passRate)],["Assignment completion",value(data.assessments.assignmentCompletion)]].map(([l,v])=><article className="bg-white p-5" key={l}><p className="text-xs text-[#718079]">{l}</p><p className="mt-3 text-2xl font-semibold">{v}</p></article>)}</div></section>;
  else if (view === "Recommendations" || view === "Risk") content = <section><Heading overline={view === "Risk" ? "Early warning system" : "Executive recommendations"} title="Leadership action rail" meta={`Threshold ${threshold}%`}/>{visibleActions.length ? <div className="space-y-3">{visibleActions.map(action=><article className="grid gap-4 border-l-4 border-[#c27729] bg-white p-5 lg:grid-cols-[1fr_1.5fr_150px_120px]" key={action.id}><div><p className="text-[10px] font-bold uppercase text-[#a45e19]">{action.severity} · {action.domain.replaceAll("_", " ")}</p><h3 className="mt-1 font-semibold">{action.subject}</h3></div><div><p className="text-xs text-[#68736e]">{action.evidence}</p><p className="mt-2 text-sm font-medium">{action.action}</p></div><p className="text-xs"><b>Owner · due</b><br/>{action.owner}<br/>{action.dueHorizon}</p><button onClick={()=>download("actions")} className="h-10 border border-[#19765b] px-3 text-xs font-bold text-[#19765b]">Export action</button></article>)}</div> : <Empty title="No active risk signals" detail="Signals appear only when measured grades fall below 50%, saved attendance below 75%, or learning completion below 50%."/>}</section>;
  else if (view === "Compare") content = <section><Heading overline="Comparative analytics" title="Authorized comparisons"/><div className="grid gap-5 lg:grid-cols-2"><article className="border bg-white p-6"><Heading overline="Department vs department" title="Outcome rank"/><Bars rows={data.departments}/></article><Empty title="Institution comparison unavailable" detail="Your account is authorized for one institution. DirectorX never queries institutions outside that tenant scope. Class, teacher and academic-year comparisons appear only where measured evidence exists."/></div></section>;
  else if (view === "Reports") content = <section><Heading overline="Executive reports" title="Safe academic exports"/><div className="grid gap-px bg-[#d6d9d4] sm:grid-cols-2 lg:grid-cols-4">{["academic","teachers","students","institution","executive-summary"].map(report=><article className="bg-white p-5" key={report}><BookOpen className="h-5 w-5 text-[#19765b]"/><h3 className="mt-4 capitalize font-semibold">{report} report</h3><div className="mt-5 flex gap-2"><button onClick={()=>download(report)} className="border px-3 py-2 text-xs font-bold">CSV</button><button onClick={()=>download(report,"json")} className="border px-3 py-2 text-xs font-bold">JSON</button></div></article>)}</div></section>;
  else content = <section><Heading overline="Academic settings" title="Thresholds and preferences" meta="Saved on this device"/><article className="max-w-xl bg-white p-6"><label className="text-sm font-semibold">Academic risk threshold: {threshold}%<input className="mt-4 w-full accent-[#19765b]" type="range" min="35" max="70" value={threshold} onChange={e=>saveThreshold(Number(e.target.value))}/></label><p className="mt-4 text-xs text-[#68736e]">Controls your dashboard preference. The disclosed early-warning baseline remains visible with every exported report.</p></article></section>;
  return <main className="min-w-0 bg-[#f6f4ee] text-[#14231f]"><header className="bg-[#14231f] px-5 py-6 text-white"><p className="text-[10px] font-bold uppercase tracking-[.22em] text-[#79c9ad]">DirectorX Guru · Academic intelligence</p><div className="mt-2 flex items-end justify-between"><div><h1 className="text-3xl font-semibold">Evidence into action.</h1><p className="mt-1 text-sm text-white/60">{data.institution} · Authorized scope</p></div><BarChart3 className="hidden h-8 w-8 text-[#79c9ad] sm:block"/></div></header><nav className="grid grid-cols-2 border-b bg-white sm:grid-cols-5">{views.map(item=><button className={`border-r px-2 py-3 text-xs font-semibold ${view===item ? "bg-[#e5f2ed] text-[#116047]" : "text-[#68736e] hover:bg-[#f2f2ed]"}`} onClick={()=>setView(item)} key={item}>{item}</button>)}</nav><div className="p-4 md:p-6"><div className="mb-6 flex flex-wrap gap-3"><select aria-label="Academic intelligence module" value={view} onChange={event=>setView(event.target.value as View)} className="h-10 border bg-white px-3 text-sm"><option>Performance</option><option>Departments</option><option>Teachers</option><option>Students</option><option>Assessments</option><option>Compare</option><option>Recommendations</option><option>Risk</option><option>Reports</option><option>Settings</option></select>{["Teachers","Students","Departments","Risk","Recommendations"].includes(view) && <label className="relative min-w-[220px] flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-[#718079]"/><input className="h-10 w-full border bg-white pl-9 pr-3 text-sm" value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${view.toLowerCase()}`}/></label>} {["Teachers","Students","Departments","Risk","Recommendations"].includes(view) && <select value={sort} onChange={e=>setSort(e.target.value)} className="h-10 border bg-white px-3 text-sm"><option value="score">Sort: performance</option><option value="risk">Sort: risk</option><option value="name">Sort: name</option></select>} {reportForView[view] && <button onClick={()=>download(reportForView[view]!)} className="flex h-10 items-center gap-2 bg-[#14231f] px-4 text-xs font-bold text-white"><Download className="h-4 w-4"/>Export</button>}</div>{content}</div></main>;
}
